export default {
  "ide-startup": "IDE startup options",
  "diagnostics": "Diagnostics",
  "advanced-debugging": "Turning on advanced debugging",
  "shortcuts": "Changing keyboard shortcuts",
  "file-extensions": "Changing default file extensions",
  "customize-syntax-colors": "Customizing syntax highlighting colors",
  "background-compilation": "Using background compilation",
  "instant-screen": "Using the Instant Screen",
  "screen-recording": "Recording the Emulator Screen",
  "always-on-top": "Keeping the Emulator always on top",
  "measure-t-states": "Measuring T-states",
  "sp48-custom-rom": "Using a Custom ROM with ZX Spectrum 48K",
  "trdos-disks": "Using TR-DOS Disks on the Pentagon 128",
  "spectrum-snapshots": "Using ZX Spectrum Snapshots",
  "rzx-recordings": "Playing and Recording RZX Files",
  "machine-state": "Saving and Restoring the Machine State",
  "debug-recordings": "Saving and Opening Debug Recordings",
  "z88-snapshots": "Using Z88 Snapshots",
  "zx81": "Using the ZX81 and ZX80"
};