/*
 * The ZX Spectrum Next registers as the IDE documents them: name, read/write-only flags and the bit
 * slices the Next Registers panel breaks a value into.
 *
 * Neutral data, read by `IZxNextIdeMachine.getNextRegDescriptors()`, the disassembler's NEXTREG
 * comments and the tests. It used to be built inside the TypeScript `NextRegDevice` constructor,
 * next to the read/write closures, so every consumer had to construct an emulated device to read
 * documentation. Generated from that constructor on 2026-09-19 and the single source since that
 * device was deleted; `test/zxnext-shared/nextRegDescriptors.test.ts` pins its shape.
 */

/** A bit field of a NextReg value, as the Next Registers panel shows it. */
export type NextRegValueSlice = {
  mask?: number;
  shift?: number;
  description?: string;
  valueSet?: Record<number, string>;
  view?: "flag" | "number";
};

/** The documentation of one NextReg. */
export type NextRegDescriptor = {
  id: number;
  description: string;
  isReadOnly?: boolean;
  isWriteOnly?: boolean;
  slices?: NextRegValueSlice[];
};

/** A register's state in the Next Registers panel: what a read returns, and what the CPU last wrote. */
export type RegValueState = {
  id: number;
  lastWrite?: number;
  value?: number;
};

/** The Next Registers panel's state: every documented register, and the `$243B` selection. */
export type NextRegDeviceState = {
  lastRegisterIndex: number;
  regs: RegValueState[];
};

/** Every documented NextReg, in register order. */
export const NEXT_REG_DESCRIPTORS: readonly NextRegDescriptor[] = [
  {
    id: 0x00,
    description: "Machine ID",
    isReadOnly: true,
    slices: [
      {
        valueSet: {
          8: "Emulators",
          10: "ZX Spectrum Next",
          154: "ZX Spectrum Next Core on UnAmiga Reloaded",
          170: "ZX Spectrum Next Core on UnAmiga",
          186: "ZX Spectrum Next Core on SiDi",
          202: "ZX Spectrum Next Core on MIST",
          218: "ZX Spectrum Next Core on MiSTer",
          234: "ZX Spectrum Next Core on ZX-DOS",
          250: "ZX Spectrum Next Anti-brick"
        }
      }
    ]
  },
  {
    id: 0x01,
    description: "Core Version",
    isReadOnly: true,
    slices: [
      { mask: 0xf0, shift: 4, description: "Major Version" },
      { mask: 0x0f, description: "Minor Version" }
    ]
  },
  {
    id: 0x02,
    description: "Reset",
    slices: [
      {
        mask: 0x80,
        shift: 7,
        description: "The reset signal to the expansion bus and ESP is asserted"
      },
      {
        mask: 0x10,
        shift: 4,
        description: "Multiface NMI was generated by an i/o trap (experimental, see nextreg 0xda)"
      },
      { mask: 0x08, shift: 3, description: "Multiface NMI was generated by this nextreg" },
      { mask: 0x04, shift: 2, description: "DivMMC nmi was generated by this nextreg" },
      { mask: 0x02, shift: 1, description: "The last reset was a hard reset" },
      { mask: 0x02, shift: 1, description: "The last reset was a soft reset" }
    ]
  },
  {
    id: 0x03,
    description: "Machine Type",
    slices: [
      { mask: 0x80, shift: 7, description: "NextReg 0x44 second byte indicator" },
      {
        mask: 0x70,
        shift: 4,
        description: "Display timing",
        valueSet: {
          0: "Internal use",
          1: "ZX 48K",
          2: "ZX 128K/+2",
          3: "ZX +2A/+2b/+3/Next",
          4: "Pentagon clones"
        }
      },
      { mask: 0x08, shift: 3, description: "User lock on display timing applied" },
      {
        mask: 0x07,
        description: "Machine type",
        valueSet: {
          0: "Configuration mode",
          1: "ZX 48K",
          2: "ZX 128K/+2",
          3: "ZX +2A/+2b/+3/Next",
          4: "Pentagon clones"
        }
      }
    ]
  },
  {
    id: 0x04,
    description: "Config Mapping",
    isWriteOnly: true,
    slices: [
      { mask: 0x7f, description: "16K SRAM bank mapped to 0x0000-0x3FFF (hard reset = 0)" }
    ]
  },
  {
    id: 0x05,
    description: "Peripheral 1 Setting",
    slices: [
      {
        mask: 0xc8,
        shift: 3,
        description: "Joystick 1 mode",
        valueSet: {
          0: "Sinclair 2 (12345)",
          1: "Kempston 2 port (0x37)",
          8: "Kempston 1 port (0x1f)",
          9: "MD 1 port (0x1f)",
          16: "Cursor (56780)",
          17: "MD 2 port (0x37)",
          24: "Sinclair 1 (67890)",
          25: "User-defined keys joystick"
        }
      },
      {
        mask: 0x32,
        shift: 1,
        description: "Joystick 2 mode",
        valueSet: {
          0: "Sinclair 2 (12345)",
          1: "Kempston 2 port (0x37)",
          8: "Kempston 1 port (0x1f)",
          9: "MD 1 port (0x1f)",
          16: "Cursor (56780)",
          17: "MD 2 port (0x37)",
          24: "Sinclair 1 (67890)",
          25: "User-defined keys joystick"
        }
      },
      { mask: 0x04, shift: 2, description: "0 = 50Hz, 1 = 60Hz, Pentagon forces 50Hz" },
      { mask: 0x01, description: "Enable scandoubler (1 = enabled for VGA, 0 for CRT)" }
    ]
  },
  {
    id: 0x06,
    description: "Peripheral 2 Setting",
    slices: [
      {
        mask: 0x80,
        shift: 7,
        description: "Enable F8 cpu speed hotkey and F5/F6 expansion bus hotkeys (soft reset = 1)"
      },
      { mask: 0x40, shift: 6, description: "Divert BEEP only to internal speaker (hard reset = 0)" },
      { mask: 0x20, shift: 5, description: "Enable F3 50/60 Hz hotkey (soft reset = 1)" },
      { mask: 0x10, shift: 4, description: "Enable DivMMC NMI by DRIVE button (hard reset = 0)" },
      { mask: 0x08, shift: 3, description: "Enable Multiface NMI by M1 button (hard reset = 0)" },
      {
        mask: 0x04,
        shift: 2,
        description: "PS/2 mode (0 = keyboard primary, 1 = mouse primary; config mode only)"
      },
      {
        mask: 0x03,
        description: "Audio chip mode",
        valueSet: {
          0: "YM",
          1: "AY",
          2: "ZXN-8950",
          3: "Hold all PSGs in reset"
        }
      }
    ]
  },
  {
    id: 0x07,
    description: "CPU speed",
    slices: [
      {
        mask: 0x30,
        shift: 4,
        description: "Current actual cpu speed",
        valueSet: {
          0: "3.5MHz",
          1: "7MHz",
          2: "14MHz",
          3: "28MHz"
        }
      },
      {
        mask: 0x03,
        description: "Programmed cpu speed",
        valueSet: {
          0: "3.5MHz",
          1: "7MHz",
          2: "14MHz",
          3: "28MHz"
        }
      }
    ]
  },
  {
    id: 0x08,
    description: "Peripheral 3 Setting",
    slices: [
      {
        mask: 0x80,
        shift: 7,
        description: "Unlock port 0x7ffd (read 1 indicates port 0x7ffd is not locked)"
      },
      { mask: 0x40, shift: 6, description: "Disable ram and port contention (soft reset = 0)" },
      { mask: 0x20, shift: 5, description: "AY stereo mode (0 = ABC, 1 = ACB) (hard reset = 0)" },
      { mask: 0x10, shift: 4, description: "Enable internal speaker (hard reset = 1)" },
      { mask: 0x08, shift: 3, description: "Enable 8-bit DACs (A,B,C,D) (hard reset = 0)" },
      {
        mask: 0x04,
        shift: 2,
        description: "Enable port 0xff Timex video mode read (hides floating bus on 0xff) (hard reset = 0)"
      },
      {
        mask: 0x02,
        shift: 1,
        description: "Enable turbosound (currently selected AY is frozen when disabled) (hard reset = 0)"
      },
      { mask: 0x01, description: "Implement issue 2 keyboard (hard reset = 0)" }
    ]
  },
  {
    id: 0x09,
    description: "Peripheral 4 Setting",
    slices: [
      { mask: 0x80, shift: 7, description: "Place AY 2 in mono mode (hard reset = 0)" },
      { mask: 0x40, shift: 6, description: "Place AY 1 in mono mode (hard reset = 0)" },
      { mask: 0x20, shift: 5, description: "Place AY 0 in mono mode (hard reset = 0)" },
      {
        mask: 0x10,
        shift: 4,
        description: "Sprite id lockstep (nextreg 0x34 and port 0x303B are in lockstep) (soft reset = 0)"
      },
      {
        mask: 0x08,
        shift: 3,
        description: "Reset DivMMC MAPRAM bit (port 0xe3 bit 6) (read returns 0)"
      },
      { mask: 0x04, shift: 2, description: "1 to silence hdmi audio (hard reset = 0)" },
      {
        mask: 0x03,
        description: "Scanline weight",
        valueSet: {
          0: "scanlines off",
          1: "scanlines 50%",
          2: "scanlines 25%",
          3: "scanlines 12.5%"
        }
      }
    ]
  },
  {
    id: 0x0a,
    description: "Peripheral 5 Setting",
    slices: [
      {
        mask: 0xc0,
        shift: 6,
        description: "Multiface type (hard reset = 00) (config mode only)",
        valueSet: {
          0: "Multiface +3 (enable port 0x3F, disable port 0xBF)",
          1: "Multiface 128 v87.2 (enable port 0xBF, disable port 0x3F)",
          2: "Multiface 128 v87.12 (enable port 0x9F, disable port 0x1F)",
          3: "Multiface 1 (enable port 0x9F, disable port 0x1F)"
        }
      },
      { mask: 0x20, shift: 5, description: "1 to swap SD card 0 and 1 (hard reset = 0)" },
      { mask: 0x10, shift: 4, description: "Enable DivMMC automap (hard reset = 0)" },
      {
        mask: 0x08,
        shift: 3,
        description: "1 to reverse left and right mouse buttons (hard reset = 0)"
      },
      {
        mask: 0x03,
        description: "Mouse DPI (hard reset = 01)",
        valueSet: {
          0: "Low DPI",
          1: "Default",
          2: "Medium DPI",
          3: "High DPI"
        }
      }
    ]
  },
  {
    id: 0x0b,
    description: "Joystick I/O Mode",
    slices: [
      { mask: 0x80, shift: 7, description: "1 to enable i/o mode" },
      {
        mask: 0x30,
        description: "I/O Mode",
        valueSet: {
          0: "bit bang",
          1: "clock",
          2: "uart on left joystick port",
          3: "uart on right joystick port"
        }
      },
      { mask: 0x01, description: "Parameter: bit bang" }
    ]
  },
  {
    id: 0x0e,
    description: "Core Version",
    isReadOnly: true
  },
  {
    id: 0x0f,
    description: "Board ID",
    isReadOnly: true,
    slices: [
      {
        mask: 0x0f,
        description: "Board ID",
        valueSet: {
          0: "ZXN Issue 2, XC6SLX16-2FTG256, 128Mbit W25Q128JV, 24bit spi, 64K*8 core size",
          1: "ZXN Issue 3, XC6SLX16-2FTG256, 128Mbit W25Q128JV, 24bit spi, 64K*8 core size",
          2: "ZXN Issue 4, XC7A15T-1CSG324, 256Mbit MX25L25645G, 32bit spi, 64K*34 core size"
        }
      }
    ]
  },
  {
    id: 0x10,
    description: "Core Boot",
    slices: [
      { mask: 0x7c, description: "Cored ID", view: "number" },
      { mask: 0x02, shift: 1, description: "Button DRIVE (DivMMC) is pressed" },
      { mask: 0x01, description: "Button M1 (Multiface) is pressed" }
    ]
  },
  {
    id: 0x11,
    description: "Video Timing",
    slices: [
      {
        mask: 0x07,
        description: "Mode (VGA = 0..6, HDMI = 7)",
        valueSet: {
          0: "Base VGA timing, clk28 = 28000000",
          1: "VGA setting 1, clk28 = 28571429",
          2: "VGA setting 2, clk28 = 29464286",
          3: "VGA setting 3, clk28 = 30000000",
          4: "VGA setting 4, clk28 = 31000000",
          5: "VGA setting 5, clk28 = 32000000",
          6: "VGA setting 6, clk28 = 33000000",
          7: "HDMI"
        }
      }
    ]
  },
  {
    id: 0x12,
    description: "Layer 2 Active RAM bank",
    slices: [
      { mask: 0x7f, description: "Starting 16K RAM bank (soft reset = 8)", view: "number" }
    ]
  },
  {
    id: 0x13,
    description: "Layer 2 Shadow RAM bank",
    slices: [
      { mask: 0x7f, description: "Starting 16K RAM bank (soft reset = 11)", view: "number" }
    ]
  },
  {
    id: 0x14,
    description: "Global Transparency Colour"
  },
  {
    id: 0x15,
    description: "Sprite and Layers System",
    slices: [
      { mask: 0x80, shift: 7, description: "Enable lores mode (soft reset = 0)" },
      {
        mask: 0x40,
        shift: 6,
        description: "Sprite priority (1 = sprite 0 on top, 0 = sprite 127 on top) (soft reset = 0)"
      },
      {
        mask: 0x20,
        shift: 5,
        description: "Enable sprite clipping in over border mode (soft reset = 0)"
      },
      {
        mask: 0x1c,
        shift: 2,
        description: "layer priority (eg SLU = sprites over layer 2 over ula) (soft reset = 000)",
        valueSet: {
          0: "SLU",
          1: "LSU",
          2: "SUL",
          3: "LUS",
          4: "USL",
          5: "ULS",
          6: "(U|T)S(T|U)(B+L) Blending layer and Layer 2 combined, colours clamped to [0,7]",
          7: "(U|T)S(T|U)(B+L-5) Blending layer and Layer 2 combined, colours clamped to [0,7]"
        }
      },
      { mask: 0x02, shift: 1, description: "Enable sprites over border (soft reset = 0)" },
      { mask: 0x01, description: "Enable sprites (soft reset = 0)" }
    ]
  },
  {
    id: 0x16,
    description: "Layer2 X Scroll LSB"
  },
  {
    id: 0x17,
    description: "Layer2 Y Scroll"
  },
  {
    id: 0x18,
    description: "Clip Window Layer 2"
  },
  {
    id: 0x19,
    description: "Clip Window Sprites"
  },
  {
    id: 0x1a,
    description: "Clip Window ULA"
  },
  {
    id: 0x1b,
    description: "Clip Window Tilemap"
  },
  {
    id: 0x1c,
    description: "Clip Window control",
    slices: [
      { mask: 0xc0, shift: 6, description: "Tilemap clip index" },
      { mask: 0x30, shift: 4, description: "ULA/Lores clip index" },
      { mask: 0x0c, shift: 2, description: "Sprite clip index" },
      { mask: 0x03, description: "Layer 2 clip index" }
    ]
  },
  {
    id: 0x1e,
    description: "Active video line MSB",
    isReadOnly: true,
    slices: [
      { mask: 0x01, description: "Active line MSB" }
    ]
  },
  {
    id: 0x1f,
    description: "Active video line LSB",
    isReadOnly: true
  },
  {
    id: 0x20,
    description: "Generate Maskable Interrupt",
    slices: [
      { mask: 0x80, shift: 7, description: "Line" },
      { mask: 0x40, shift: 6, description: "ULA" },
      { mask: 0x0f, description: "CTC 3:0" }
    ]
  },
  {
    id: 0x22,
    description: "Line Interrupt control",
    slices: [
      {
        mask: 0x80,
        shift: 7,
        description: "Indicates if the ula is asserting an interrupt (even if disabled)"
      },
      { mask: 0x04, shift: 2, description: "Disables ula interrupt (soft reset = 0)" },
      { mask: 0x02, shift: 1, description: "Enables line Interrupt (soft reset = 0)" },
      { mask: 0x01, description: "MSB of line interrupt value (soft reset = 0)" }
    ]
  },
  {
    id: 0x23,
    description: "Line Interrupt Value LSB"
  },
  {
    id: 0x24,
    description: "Reserved"
  },
  {
    id: 0x26,
    description: "ULA X Scroll"
  },
  {
    id: 0x27,
    description: "ULA Y Scroll"
  },
  {
    id: 0x28,
    description: "PS/2 Keymap Address MSB"
  },
  {
    id: 0x29,
    description: "PS/2 Keymap Address LSB"
  },
  {
    id: 0x2a,
    description: "PS/2 Keymap Data MSB",
    slices: [
      { mask: 0x01, description: "MSB data" }
    ]
  },
  {
    id: 0x2b,
    description: "PS/2 Keymap Data LSB"
  },
  {
    id: 0x2c,
    description: "DAC B Mirror (left)"
  },
  {
    id: 0x2d,
    description: "DAC A+D Mirror (mono)"
  },
  {
    id: 0x2e,
    description: "DAC C Mirror (right)"
  },
  {
    id: 0x2f,
    description: "Tilemap X Scroll MSB",
    slices: [
      { mask: 0x03, description: "MSB X Offset (soft reset = 0)" }
    ]
  },
  {
    id: 0x30,
    description: "Tilemap X Scroll LSB"
  },
  {
    id: 0x31,
    description: "Tilemap Offset Y"
  },
  {
    id: 0x32,
    description: "LoRes X Scroll"
  },
  {
    id: 0x33,
    description: "LoRes Y Scroll"
  },
  {
    id: 0x34,
    description: "Sprite Number",
    slices: [
      { mask: 0x7f, description: "Sprite number 0-127" }
    ]
  },
  {
    id: 0x35,
    description: "Sprite Attribute 0",
    isWriteOnly: true
  },
  {
    id: 0x36,
    description: "Sprite Attribute 1",
    isWriteOnly: true
  },
  {
    id: 0x37,
    description: "Sprite Attribute 2",
    isWriteOnly: true
  },
  {
    id: 0x38,
    description: "Sprite Attribute 3",
    isWriteOnly: true
  },
  {
    id: 0x39,
    description: "Sprite Attribute 4",
    isWriteOnly: true
  },
  {
    id: 0x40,
    description: "Palette Index"
  },
  {
    id: 0x41,
    description: "Palette Value (8 bit)"
  },
  {
    id: 0x42,
    description: "ULANext Attribute Byte Format"
  },
  {
    id: 0x43,
    description: "Palette Control",
    slices: [
      { mask: 0x80, shift: 7, description: "Disable palette write auto-increment (soft reset = 0)" },
      {
        mask: 0x70,
        shift: 4,
        description: "Select palette for reading or writing (soft reset = 000)",
        valueSet: {
          0: "ULA first palette",
          1: "Layer 2 first palette",
          2: "Sprites first palette",
          3: "Tilemap first palette",
          4: "ULA second palette",
          5: "Layer 2 second palette",
          6: "Sprites second palette",
          7: "Tilemap second palette"
        }
      },
      {
        mask: 0x08,
        shift: 3,
        description: "Select sprites palette (0 = first palette, 1 = second palette) (soft reset = 0)"
      },
      {
        mask: 0x04,
        shift: 2,
        description: "Select Layer 2 palette (0 = first palette, 1 = second palette) (soft reset = 0)"
      },
      {
        mask: 0x02,
        shift: 1,
        description: "Select ULA palette (0 = first palette, 1 = second palette) (soft reset = 0)"
      },
      { mask: 0x01, description: "Enabe ULANext mode (soft reset = 0)" }
    ]
  },
  {
    id: 0x44,
    description: "Palette Value (9 bit)"
  },
  {
    id: 0x4a,
    description: "Fallback Colour"
  },
  {
    id: 0x4b,
    description: "Sprite Transparency Index"
  },
  {
    id: 0x4c,
    description: "Tilemap Transparency Index"
  },
  {
    id: 0x50,
    description: "MMU 0"
  },
  {
    id: 0x51,
    description: "MMU 1"
  },
  {
    id: 0x52,
    description: "MMU 2"
  },
  {
    id: 0x53,
    description: "MMU 3"
  },
  {
    id: 0x54,
    description: "MMU 4"
  },
  {
    id: 0x55,
    description: "MMU 5"
  },
  {
    id: 0x56,
    description: "MMU 6"
  },
  {
    id: 0x57,
    description: "MMU 7"
  },
  {
    id: 0x60,
    description: "Copper Data 8-bit Write",
    isWriteOnly: true
  },
  {
    id: 0x61,
    description: "Copper Address LSB"
  },
  {
    id: 0x62,
    description: "Copper Control",
    slices: [
      {
        mask: 0xc0,
        shift: 6,
        description: "Start control (soft reset = 00)",
        valueSet: {
          0: "Copper fully stopped",
          1: "Copper start, execute the list from index 0, and loop to the start",
          2: "Copper start, execute the list from last point, and loop to the start",
          3: "Copper start, execute the list from index 0, and restart the list when the raster reaches position (0,0)"
        }
      },
      { mask: 0x07, description: "Copper instruction memory address MSB (soft reset = 0)" }
    ]
  },
  {
    id: 0x63,
    description: "Copper Data 16-bit Write",
    isWriteOnly: true
  },
  {
    id: 0x64,
    description: "Vertical Line Count Offset"
  },
  {
    id: 0x68,
    description: "ULA Control",
    slices: [
      { mask: 0x80, shift: 7, description: "Disable ULA output (soft reset = 0)" },
      {
        mask: 0x60,
        shift: 5,
        description: "Blending in SLU modes 6 & 7 (soft reset = 0)",
        valueSet: {
          0: "for ULA as blend colour",
          1: "for ULA/tilemap mix result as blend colour",
          2: "for tilemap as blend colour",
          3: "for no blending"
        }
      },
      { mask: 0x10, shift: 4, description: "Cancel entries in 8x5 matrix for extended keys" },
      { mask: 0x08, shift: 3, description: "ULA+ enable (soft reset = 0)" },
      { mask: 0x04, shift: 2, description: "ULA half pixel scroll (may change) (soft reset = 0)" },
      {
        mask: 0x01,
        description: "Enable stencil mode when both the ULA and tilemap are enabled (soft reset = 0)"
      }
    ]
  },
  {
    id: 0x69,
    description: "Display Control 1",
    slices: [
      { mask: 0x80, shift: 7, description: "Enable layer 2 (alias port 0x123B bit 1)" },
      { mask: 0x40, shift: 6, description: "Enable ULA shadow display (alias port 0x7FFD bit 3)" },
      { mask: 0x3f, description: "Port 0xFF bits 5:0 alias (Timex display modes)", view: "number" }
    ]
  },
  {
    id: 0x6a,
    description: "LoRes Control",
    slices: [
      {
        mask: 0x20,
        shift: 5,
        description: "LoRes is Radastan mode (128x96x4, 6144 bytes) (soft reset = 0)"
      },
      {
        mask: 0x10,
        shift: 4,
        description: "LoRes Radastan timex display file xor (soft reset = 0)"
      },
      {
        mask: 0x0f,
        description: "LoRes palette offset (bits 1:0 apply in ula+ mode) (soft reset = 0)",
        view: "number"
      }
    ]
  },
  {
    id: 0x6b,
    description: "Tilemap Control",
    slices: [
      { mask: 0x80, shift: 7, description: "1 Enable the tilemap (soft reset = 0)" },
      { mask: 0x40, shift: 6, description: "0 for 40x32, 1 for 80x32 (soft reset = 0)" },
      {
        mask: 0x20,
        shift: 5,
        description: "Eliminate the attribute entry in the tilemap (soft reset = 0)"
      },
      { mask: 0x10, shift: 4, description: "Palette select (soft reset = 0)" },
      { mask: 0x08, shift: 3, description: "Select textmode (soft reset = 0)" },
      { mask: 0x02, shift: 1, description: "Activate 512 tile mode (soft reset = 0)" },
      { mask: 0x01, description: "Force tilemap on top of ULA (soft reset = 0)" }
    ]
  },
  {
    id: 0x6c,
    description: "Default Tilemap Attribute",
    slices: [
      { mask: 0xf0, shift: 4, description: "Palette offset (soft reset = 0)" },
      { mask: 0x08, shift: 3, description: "X mirror (soft reset = 0)" },
      { mask: 0x04, shift: 2, description: "Y mirror (soft reset = 0)" },
      { mask: 0x02, shift: 1, description: "Rotate (soft reset = 0)" },
      { mask: 0x01, description: "ULA over tilemap (soft reset = 0)" }
    ]
  },
  {
    id: 0x6e,
    description: "Tilemap Base Address",
    slices: [
      { mask: 0x80, shift: 7, description: "1 to select bank 7, 0 to select bank 5" },
      { mask: 0x3f, description: "MSB of address of the tilemap in Bank 5", view: "number" }
    ]
  },
  {
    id: 0x6f,
    description: "Tile Definitions Base Address",
    slices: [
      { mask: 0x80, shift: 7, description: "1 to select bank 7, 0 to select bank 5" },
      { mask: 0x3f, description: "MSB of address of tile definitions in Bank 5", view: "number" }
    ]
  },
  {
    id: 0x70,
    description: "Layer 2 Control",
    slices: [
      {
        mask: 0x30,
        shift: 4,
        description: "Layer 2 resolution (soft reset = 0)",
        valueSet: {
          0: "256x192x8",
          1: "320x256x8",
          2: "640x256x4"
        }
      },
      { mask: 0x0f, description: "Palette offset (soft reset = 0)", view: "number" }
    ]
  },
  {
    id: 0x71,
    description: "Layer 2 X Scroll MSB",
    slices: [
      { mask: 0x01, description: "MSB of scroll amount" }
    ]
  },
  {
    id: 0x75,
    description: "Sprite Attribute 0 (automatic increment)",
    isWriteOnly: true
  },
  {
    id: 0x76,
    description: "Sprite Attribute 1  (automatic increment)",
    isWriteOnly: true
  },
  {
    id: 0x77,
    description: "Sprite Attribute 2 (automatic increment)",
    isWriteOnly: true
  },
  {
    id: 0x78,
    description: "Sprite Attribute 3 (automatic increment)",
    isWriteOnly: true
  },
  {
    id: 0x79,
    description: "Sprite Attribute 4 (automatic increment)",
    isWriteOnly: true
  },
  {
    id: 0x7f,
    description: "User Register 0"
  },
  {
    id: 0x80,
    description: "Expansion Bus Enable",
    slices: [
      { mask: 0x80, shift: 7, description: "Enable the expansion bus" },
      { mask: 0x40, shift: 6, description: "Enable romcs rom replacement from DivMMC banks 14/15" },
      { mask: 0x20, shift: 5, description: "Disable i/o cycles & ignore iorqula" },
      { mask: 0x10, shift: 4, description: "Disable memory cycles & ignore romcs" },
      { mask: 0x08, shift: 3, description: "Enable the expansion bus" },
      { mask: 0x04, shift: 2, description: "Enable romcs rom replacement from DivMMC banks 14/15" },
      { mask: 0x02, shift: 1, description: "Disable i/o cycles & ignore iorqula" },
      { mask: 0x01, description: "Disable memory cycles & ignore romcs" }
    ]
  },
  {
    id: 0x81,
    description: "Expansion Bus Control",
    slices: [
      { mask: 0x80, shift: 7, description: "ROMCS is asserted on the expansion bus (read only)" },
      {
        mask: 0x40,
        shift: 6,
        description: "Allow peripherals to override the ULA on some even port reads (rotronics wafadrive)"
      },
      { mask: 0x20, shift: 5, description: "Disable expansion bus nmi debounce (opus discovery)" },
      {
        mask: 0x10,
        shift: 4,
        description: "Propagate the max cpu clock at all times including when the expansion bus is off"
      },
      {
        mask: 0x03,
        description: "Max cpu speed when the expansion bus is on (currently fixed at 00 = 3.5MHz)"
      },
      { mask: 0x04, shift: 2, description: "Enable romcs rom replacement from DivMMC banks 14/15" },
      { mask: 0x02, shift: 1, description: "Disable i/o cycles & ignore iorqula" },
      { mask: 0x01, description: "Disable memory cycles & ignore romcs" }
    ]
  },
  {
    id: 0x82,
    description: "Internal Port Decoding Enables #1 (LSB)",
    slices: [
      { mask: 0x80, shift: 7, description: "Port 0x37 kempston 2 / md2" },
      { mask: 0x40, shift: 6, description: "Port 0x1f kempston / md1" },
      { mask: 0x20, shift: 5, description: "Port 0x6b zxn dma" },
      { mask: 0x10, shift: 4, description: "+3 floating bus" },
      { mask: 0x08, shift: 3, description: "Port 0x1ffd" },
      { mask: 0x04, shift: 2, description: "Port 0xdffd" },
      { mask: 0x02, shift: 1, description: "Port 0x7ffd" },
      { mask: 0x01, description: "Port 0xff" }
    ]
  },
  {
    id: 0x83,
    description: "Internal Port Decoding Enables #2",
    slices: [
      { mask: 0x80, shift: 7, description: "Port 0x123b layer2" },
      { mask: 0x40, shift: 6, description: "Port 0x57, 0x5b, 0x303b sprites" },
      {
        mask: 0x20,
        shift: 5,
        description: "Port 0xfadf, 0xfbdf, 0xffdf mouse (also disables kempston alias on port df)"
      },
      { mask: 0x10, shift: 4, description: "Port 0x133b, 0x143b, 0x153b, 0x163b uart" },
      { mask: 0x08, shift: 3, description: "Port 0xe7, 0xeb spi" },
      { mask: 0x04, shift: 2, description: "Port 0x103b, 0x113b i2c" },
      { mask: 0x02, shift: 1, description: "Multiface (two variable ports)" },
      { mask: 0x01, description: "Port 0xe3 DivMMC control" }
    ]
  },
  {
    id: 0x84,
    description: "Internal Port Decoding Enables #3",
    slices: [
      { mask: 0x80, shift: 7, description: "Port 0xdf dac mono specdrum, port 0x1f kempston alias" },
      { mask: 0x40, shift: 6, description: "Port 0xb3 dac mono gs covox" },
      { mask: 0x20, shift: 5, description: "Port 0xfb dac mono pentagon/atm (sd mode 2 off)" },
      { mask: 0x10, shift: 4, description: "Port 0x0f, 0x4f dac stereo covox" },
      { mask: 0x08, shift: 3, description: "Port 0x3f, 0x5f dac stereo profi covox" },
      { mask: 0x04, shift: 2, description: "Port 0xf1, 0xf3, 0xf9, 0xfb dac soundrive mode 2" },
      { mask: 0x02, shift: 1, description: "Port 0x0f, 0x1f, 0x4f, 0x5f dac soundrive mode 1" },
      { mask: 0x01, description: "Port 0xfffd, 0xbffd ay" }
    ]
  },
  {
    id: 0x85,
    description: "Internal Port Decoding Enables #4 (MSB)",
    slices: [
      { mask: 0x80, shift: 7, description: "Register reset mode (soft or hard reset selection)" },
      {
        mask: 0x08,
        shift: 3,
        description: "Port 0x183b, 0x193b, 0x1a3b, 0x1b3b, 0x1c3b, 0x1d3b, 0x1e3b, 0x1f3b z80 ctc"
      },
      { mask: 0x04, shift: 2, description: "Port 0xeff7 Pentagon 1024 memory" },
      { mask: 0x02, shift: 1, description: "Port 0x0b Z80 DMA" },
      { mask: 0x01, description: "Port 0xbf3b, 0xff3b ULA+" }
    ]
  },
  {
    id: 0x86,
    description: "Expansion Bus Decoding Enables #1 (LSB)",
    slices: [
      { mask: 0x80, shift: 7, description: "Port 0x37 kempston 2 / md2" },
      { mask: 0x40, shift: 6, description: "Port 0x1f kempston / md1" },
      { mask: 0x20, shift: 5, description: "Port 0x6b zxn dma" },
      { mask: 0x10, shift: 4, description: "+3 floating bus" },
      { mask: 0x08, shift: 3, description: "Port 0x1ffd" },
      { mask: 0x04, shift: 2, description: "Port 0xdffd" },
      { mask: 0x02, shift: 1, description: "Port 0x7ffd" },
      { mask: 0x01, description: "Port 0xff" }
    ]
  },
  {
    id: 0x87,
    description: "Expansion Bus Decoding Enables #2",
    slices: [
      { mask: 0x80, shift: 7, description: "Port 0x123b layer2" },
      { mask: 0x40, shift: 6, description: "Port 0x57, 0x5b, 0x303b sprites" },
      {
        mask: 0x20,
        shift: 5,
        description: "Port 0xfadf, 0xfbdf, 0xffdf mouse (also disables kempston alias on port df)"
      },
      { mask: 0x10, shift: 4, description: "Port 0x133b, 0x143b, 0x153b, 0x163b uart" },
      { mask: 0x08, shift: 3, description: "Port 0xe7, 0xeb spi" },
      { mask: 0x04, shift: 2, description: "Port 0x103b, 0x113b i2c" },
      { mask: 0x02, shift: 1, description: "Multiface (two variable ports)" },
      { mask: 0x01, description: "Port 0xe3 DivMMC control" }
    ]
  },
  {
    id: 0x88,
    description: "Expansion Bus Decoding Enables #3",
    slices: [
      { mask: 0x80, shift: 7, description: "Port 0xdf dac mono specdrum, port 0x1f kempston alias" },
      { mask: 0x40, shift: 6, description: "Port 0xb3 dac mono gs covox" },
      { mask: 0x20, shift: 5, description: "Port 0xfb dac mono pentagon/atm (sd mode 2 off)" },
      { mask: 0x10, shift: 4, description: "Port 0x0f, 0x4f dac stereo covox" },
      { mask: 0x08, shift: 3, description: "Port 0x3f, 0x5f dac stereo profi covox" },
      { mask: 0x04, shift: 2, description: "Port 0xf1, 0xf3, 0xf9, 0xfb dac soundrive mode 2" },
      { mask: 0x02, shift: 1, description: "Port 0x0f, 0x1f, 0x4f, 0x5f dac soundrive mode 1" },
      { mask: 0x01, description: "Port 0xfffd, 0xbffd ay" }
    ]
  },
  {
    id: 0x89,
    description: "Expansion Bus Decoding Enables #4 (MSB)",
    slices: [
      { mask: 0x80, shift: 7, description: "Register reset mode (soft or hard reset selection)" },
      {
        mask: 0x08,
        shift: 3,
        description: "Port 0x183b, 0x193b, 0x1a3b, 0x1b3b, 0x1c3b, 0x1d3b, 0x1e3b, 0x1f3b z80 ctc"
      },
      { mask: 0x04, shift: 2, description: "Port 0xeff7 Pentagon 1024 memory" },
      { mask: 0x02, shift: 1, description: "Port 0x0b Z80 DMA" },
      { mask: 0x01, description: "Port 0xbf3b, 0xff3b ULA+" }
    ]
  },
  {
    id: 0x8a,
    description: "Expansion Bus IO Propagate",
    slices: [
      { mask: 0x20, shift: 5, description: "Propagate port 0xeff7 io cycles (hard reset = 0)" },
      { mask: 0x10, shift: 4, description: "Propagate port 0xff io cycles (hard reset = 0)" },
      { mask: 0x08, shift: 3, description: "Propagate port 0x1ffd io cycles (hard reset = 0)" },
      { mask: 0x04, shift: 2, description: "Propagate port 0xdffd io cycles (hard reset = 0)" },
      { mask: 0x02, shift: 1, description: "Propagate port 0x7ffd io cycles (hard reset = 0)" },
      { mask: 0x01, description: "Propagate port 0xfe io cycles (hard reset = 0)" }
    ]
  },
  {
    id: 0x8c,
    description: "Alternate ROM",
    slices: [
      { mask: 0x80, shift: 7, description: "Enable alt rom" },
      {
        mask: 0x40,
        shift: 6,
        description: "Make alt rom visible only during writes, otherwise replaces rom during reads"
      },
      { mask: 0x20, shift: 5, description: "Lock ROM1 (48K rom)" },
      { mask: 0x10, shift: 4, description: "Lock ROM0 (128K rom)" },
      { mask: 0x08, shift: 3, description: "Enable alt rom" },
      {
        mask: 0x04,
        shift: 2,
        description: "Make alt rom visible only during writes, otherwise replaces rom during reads"
      },
      { mask: 0x02, shift: 1, description: "Lock ROM1 (48K rom)" },
      { mask: 0x01, description: "Lock ROM0 (128K rom)" }
    ]
  },
  {
    id: 0x8e,
    description: "Spectrum 128K Memory Mapping",
    slices: [
      { mask: 0x80, shift: 7, description: "Port 0xdffd bit 0" },
      { mask: 0x70, shift: 4, description: "Port 0x7ffd bits 2:0" },
      {
        mask: 0x08,
        shift: 3,
        description: "1 to change RAM bank, 0 = no change to mmu6 / mmu7 / RAM bank in ports 0x7ffd, 0xdffd"
      },
      { mask: 0x04, shift: 2, description: "Port 0x1ffd bit 0" },
      { mask: 0x02, shift: 1, description: "Port 0x1ffd bit 2" },
      {
        mask: 0x01,
        description: "If bit 2 = paging mode = 0 (normal) then port 0x7ffd bit 4, else port 0x1ffd bit 1"
      }
    ]
  },
  {
    id: 0x8f,
    description: "Memory Mapping Mode",
    slices: [
      {
        mask: 0x03,
        description: "Mapping mode applied",
        valueSet: {
          0: "Standard ZX 128k +3",
          1: "Reserved",
          2: "Pentagon 512K",
          3: "Pentagon 1024K (limited to 768K on 1MB machines)"
        }
      }
    ]
  },
  {
    id: 0x90,
    description: "PI GPIO Output Enable #1 (LSB)"
  },
  {
    id: 0x91,
    description: "PI GPIO Output Enable #2"
  },
  {
    id: 0x92,
    description: "PI GPIO Output Enable #3"
  },
  {
    id: 0x93,
    description: "PI GPIO Output Enable #4 (MSB)"
  },
  {
    id: 0x98,
    description: "PI GPIO #1 (LSB)"
  },
  {
    id: 0x99,
    description: "PI GPIO #2"
  },
  {
    id: 0x9a,
    description: "PI GPIO #3"
  },
  {
    id: 0x9b,
    description: "PI GPIO #4 (LSB)"
  },
  {
    id: 0xa0,
    description: "PI Peripheral Enable",
    slices: [
      {
        mask: 0x20,
        shift: 5,
        description: "Enable UART on GPIO 14,15 (overrides gpio)* (soft reset = 0)"
      },
      {
        mask: 0x10,
        shift: 4,
        description: "0 to connect Rx to GPIO 15, Tx to GPIO 14 (for comm with pi hats) (soft reset = 0); 1 to connect Rx to GPIO 14, Tx to GPIO 15 (for comm with pi)"
      },
      {
        mask: 0x08,
        shift: 3,
        description: "Enable I2C on GPIO 2,3 (override gpio) (soft reset = 0)"
      },
      {
        mask: 0x01,
        description: "Enable SPI on GPIO 7,8,9,10,11 (overrides gpio) (soft reset = 0)"
      }
    ]
  },
  {
    id: 0xa2,
    description: "PI I2S Audio Control",
    slices: [
      {
        mask: 0xc0,
        shift: 6,
        description: "I2S enable (soft reset = 00)",
        valueSet: {
          0: "i2s off",
          1: "i2s is mono source right",
          2: "i2s is mono source left",
          3: "i2s is stereo"
        }
      },
      {
        mask: 0x10,
        shift: 4,
        description: "0 PCM_DOUT to pi, PCM_DIN from pi (hats) (soft reset = 0); 1 PCM_DOUT from pi, PCM_DIN to pi (pi)"
      },
      { mask: 0x08, shift: 3, description: "Mute left side (soft reset = 0)" },
      { mask: 0x04, shift: 2, description: "Mute right side (soft reset = 0)" },
      { mask: 0x01, description: "Direct i2s audio to EAR on port 0xFE (soft reset = 0)" }
    ]
  },
  {
    id: 0xa8,
    description: "ESP Wifi GPIO Output Enable",
    slices: [
      { mask: 0x04, shift: 2, description: "GPIO2 output enable (fixed at 0, GPIO2 is read-only)" },
      { mask: 0x01, description: "GPIO0 output enable" }
    ]
  },
  {
    id: 0xa9,
    description: "ESP Wifi GPIO",
    slices: [
      { mask: 0x04, shift: 2, description: "Read / Write ESP GPIO2 (soft reset = 1)" },
      { mask: 0x01, description: "Read / Write ESP GPIO0 (soft reset = 1)" }
    ]
  },
  {
    id: 0xb0,
    description: "Extended Keys 0",
    isReadOnly: true,
    slices: [
      { mask: 0x80, shift: 7, description: "; pressed" },
      { mask: 0x40, shift: 6, description: "\" pressed" },
      { mask: 0x20, shift: 5, description: ", pressed" },
      { mask: 0x10, shift: 4, description: ". pressed" },
      { mask: 0x08, shift: 3, description: "UP pressed" },
      { mask: 0x04, shift: 2, description: "DOWN pressed" },
      { mask: 0x02, shift: 1, description: "LEFT pressed" },
      { mask: 0x01, description: "RIGHT pressed" }
    ]
  },
  {
    id: 0xb1,
    description: "Extended Keys 1",
    isReadOnly: true,
    slices: [
      { mask: 0x80, shift: 7, description: "DELETE pressed" },
      { mask: 0x40, shift: 6, description: "EDIT pressed" },
      { mask: 0x20, shift: 5, description: "BREAK pressed" },
      { mask: 0x10, shift: 4, description: "INV VIDEO pressed" },
      { mask: 0x08, shift: 3, description: "TRUE VIDEO pressed" },
      { mask: 0x04, shift: 2, description: "GRAPH pressed" },
      { mask: 0x02, shift: 1, description: "CAPS LOCK pressed" },
      { mask: 0x01, description: "EXTEND pressed" }
    ]
  },
  {
    id: 0xb2,
    description: "Extended MD Pad Buttons",
    isReadOnly: true,
    slices: [
      { mask: 0x80, shift: 7, description: "Right Pad X pressed" },
      { mask: 0x40, shift: 6, description: "Right Pad Z pressed" },
      { mask: 0x20, shift: 5, description: "Right Pad Y pressed" },
      { mask: 0x10, shift: 4, description: "Right Pad MODE pressed" },
      { mask: 0x08, shift: 3, description: "Left Pad X pressed" },
      { mask: 0x04, shift: 2, description: "Left Pad Y pressed" },
      { mask: 0x02, shift: 1, description: "Left Pad Z pressed" },
      { mask: 0x01, description: "Left Pad MODE pressed" }
    ]
  },
  {
    id: 0xb8,
    description: "DivMMC Entry Points 0",
    slices: [
      { mask: 0x80, shift: 7, description: "enable automap on address 0x0038 (instruction fetch)" },
      { mask: 0x40, shift: 6, description: "enable automap on address 0x0030 (instruction fetch)" },
      { mask: 0x20, shift: 5, description: "enable automap on address 0x0028 (instruction fetch)" },
      { mask: 0x10, shift: 4, description: "enable automap on address 0x0020 (instruction fetch)" },
      { mask: 0x08, shift: 3, description: "enable automap on address 0x0018 (instruction fetch)" },
      { mask: 0x04, shift: 2, description: "enable automap on address 0x0010 (instruction fetch)" },
      { mask: 0x02, shift: 1, description: "enable automap on address 0x0008 (instruction fetch)" },
      { mask: 0x01, description: "enable automap on address 0x0000 (instruction fetch)" }
    ]
  },
  {
    id: 0xb9,
    description: "DivMMC Entry Points Valid 0",
    slices: [
      { mask: 0x80, shift: 7, description: "1 for always else only when rom3 is present (0x0038)" },
      { mask: 0x40, shift: 6, description: "1 for always else only when rom3 is present (0x0030)" },
      { mask: 0x20, shift: 5, description: "1 for always else only when rom3 is present (0x0028)" },
      { mask: 0x10, shift: 4, description: "1 for always else only when rom3 is present (0x0020)" },
      { mask: 0x08, shift: 3, description: "1 for always else only when rom3 is present (0x0018)" },
      { mask: 0x04, shift: 2, description: "1 for always else only when rom3 is present (0x0010)" },
      { mask: 0x02, shift: 1, description: "1 for always else only when rom3 is present (0x0008)" },
      { mask: 0x01, description: "1 for always else only when rom3 is present (0x0000)" }
    ]
  },
  {
    id: 0xba,
    description: "DivMMC Entry Points Timing 0",
    slices: [
      { mask: 0x80, shift: 7, description: "1 for instant mapping else delayed (0x0038)" },
      { mask: 0x40, shift: 6, description: "1 for instant mapping else delayed (0x0030)" },
      { mask: 0x20, shift: 5, description: "1 for instant mapping else delayed (0x0028)" },
      { mask: 0x10, shift: 4, description: "1 for instant mapping else delayed (0x0020)" },
      { mask: 0x08, shift: 3, description: "1 for instant mapping else delayed (0x0018)" },
      { mask: 0x04, shift: 2, description: "1 for instant mapping else delayed (0x0010)" },
      { mask: 0x02, shift: 1, description: "1 for instant mapping else delayed (0x0008)" },
      { mask: 0x01, description: "1 for instant mapping else delayed (0x0000)" }
    ]
  },
  {
    id: 0xbb,
    description: "DivMMC Entry Points 1",
    slices: [
      {
        mask: 0x80,
        shift: 7,
        description: "1 to enable automap on addresses 0x3DXX (instruction fetch, instant, ROM3) > TRDOS"
      },
      {
        mask: 0x40,
        shift: 6,
        description: "1 to disable automap on addresses 0x1FF8-0x1FFF (instruction fetch, delayed)"
      },
      {
        mask: 0x20,
        shift: 5,
        description: "1 to enable automap on address 0x056A (instruction fetch, delayed, ROM3)"
      },
      {
        mask: 0x10,
        shift: 4,
        description: "to enable automap on address 0x04D7 (instruction fetch, delayed, ROM3)"
      },
      {
        mask: 0x08,
        shift: 3,
        description: "to enable automap on address 0x0562 (instruction fetch, delayed, ROM3)"
      },
      {
        mask: 0x04,
        shift: 2,
        description: "1 to enable automap on address 0x04C6 (instruction fetch, delayed, ROM3)"
      },
      {
        mask: 0x02,
        shift: 1,
        description: "1 to enable automap on address 0x0066 (instruction fetch + button, instant)"
      },
      {
        mask: 0x01,
        description: "1 to enable automap on address 0x0066 (instruction fetch + button, delayed)"
      }
    ]
  },
  {
    id: 0xc0,
    description: "Interrupt Control",
    slices: [
      { mask: 0xe0, shift: 5, description: "Programmable portion of im2 vector" },
      { mask: 0x08, shift: 3, description: "Enable stackless nmi response" },
      {
        mask: 0x06,
        shift: 1,
        description: "Current Z80 interrupt mode 0,1,2 (read only, write ignored)"
      },
      { mask: 0x01, description: "Maskable interrupt mode: pulse (0) or hw im2 mode (1)" }
    ]
  },
  {
    id: 0xc2,
    description: "NMI Return Address LSB"
  },
  {
    id: 0xc3,
    description: "NMI Return Address MSB"
  },
  {
    id: 0xc4,
    description: "Interrupt Enable 0",
    slices: [
      { mask: 0x80, shift: 7, description: "Expansion bus /INT" },
      { mask: 0x02, shift: 1, description: "Line" },
      { mask: 0x01, description: "ULA" }
    ]
  },
  {
    id: 0xc5,
    description: "Interrupt Enable 1",
    slices: [
      { mask: 0x80, shift: 7, description: "ctc channel 7 zc/to" },
      { mask: 0x40, shift: 6, description: "ctc channel 6 zc/to" },
      { mask: 0x20, shift: 5, description: "ctc channel 5 zc/to" },
      { mask: 0x10, shift: 4, description: "ctc channel 4 zc/to" },
      { mask: 0x08, shift: 3, description: "ctc channel 3 zc/to" },
      { mask: 0x04, shift: 2, description: "ctc channel 2 zc/to" },
      { mask: 0x02, shift: 1, description: "ctc channel 1 zc/to" },
      { mask: 0x01, description: "ctc channel 0 zc/to" }
    ]
  },
  {
    id: 0xc6,
    description: "Interrupt Enable 2",
    slices: [
      { mask: 0x40, shift: 6, description: "UART1 Tx empty" },
      { mask: 0x20, shift: 5, description: "UART1 Rx near full" },
      { mask: 0x10, shift: 4, description: "UART1 Rx available" },
      { mask: 0x04, shift: 2, description: "UART0 Tx empty" },
      { mask: 0x02, shift: 1, description: "UART0 Rx near full" },
      { mask: 0x01, description: "UART0 Rx available" }
    ]
  },
  {
    id: 0xc8,
    description: "Interrupt Status 0",
    slices: [
      { mask: 0x02, shift: 1, description: "Line" },
      { mask: 0x01, description: "ULA" }
    ]
  },
  {
    id: 0xc9,
    description: "Interrupt Status 1",
    slices: [
      { mask: 0x80, shift: 7, description: "ctc channel 7 zc/to" },
      { mask: 0x40, shift: 6, description: "ctc channel 6 zc/to" },
      { mask: 0x20, shift: 5, description: "ctc channel 5 zc/to" },
      { mask: 0x10, shift: 4, description: "ctc channel 4 zc/to" },
      { mask: 0x08, shift: 3, description: "ctc channel 3 zc/to" },
      { mask: 0x04, shift: 2, description: "ctc channel 2 zc/to" },
      { mask: 0x02, shift: 1, description: "ctc channel 1 zc/to" },
      { mask: 0x01, description: "ctc channel 0 zc/to" }
    ]
  },
  {
    id: 0xca,
    description: "Interrupt Status 2",
    slices: [
      { mask: 0x40, shift: 6, description: "UART1 Tx empty" },
      { mask: 0x20, shift: 5, description: "UART1 Rx near full" },
      { mask: 0x10, shift: 4, description: "UART1 Rx available" },
      { mask: 0x04, shift: 2, description: "UART0 Tx empty" },
      { mask: 0x02, shift: 1, description: "UART0 Rx near full" },
      { mask: 0x01, description: "UART0 Rx available" }
    ]
  },
  {
    id: 0xcc,
    description: "DMA Interrupt Enable 0",
    slices: [
      { mask: 0x80, shift: 7, description: "NMI" },
      { mask: 0x02, shift: 1, description: "Line" },
      { mask: 0x01, description: "ULA" }
    ]
  },
  {
    id: 0xcd,
    description: "DMA Interrupt Enable 1",
    slices: [
      { mask: 0x80, shift: 7, description: "ctc channel 7 zc/to" },
      { mask: 0x40, shift: 6, description: "ctc channel 6 zc/to" },
      { mask: 0x20, shift: 5, description: "ctc channel 5 zc/to" },
      { mask: 0x10, shift: 4, description: "ctc channel 4 zc/to" },
      { mask: 0x08, shift: 3, description: "ctc channel 3 zc/to" },
      { mask: 0x04, shift: 2, description: "ctc channel 2 zc/to" },
      { mask: 0x02, shift: 1, description: "ctc channel 1 zc/to" },
      { mask: 0x01, description: "ctc channel 0 zc/to" }
    ]
  },
  {
    id: 0xce,
    description: "DMA Interrupt Enable 2",
    slices: [
      { mask: 0x40, shift: 6, description: "UART1 Tx empty" },
      { mask: 0x20, shift: 5, description: "UART1 Rx near full" },
      { mask: 0x10, shift: 4, description: "UART1 Rx available" },
      { mask: 0x04, shift: 2, description: "UART0 Tx empty" },
      { mask: 0x02, shift: 1, description: "UART0 Rx near full" },
      { mask: 0x01, description: "UART0 Rx available" }
    ]
  },
  {
    id: 0xd8,
    description: "I/O Traps (experimental)",
    slices: [
      { mask: 0x01, description: "1 to enable +3 FDC traps on ports 0x2ffd and 0x3ffd" }
    ]
  },
  {
    id: 0xd9,
    description: "I/O Trap Write (experimental)"
  },
  {
    id: 0xda,
    description: "I/O Trap Cause (experimental)"
  },
  {
    id: 0xf0,
    description: "XDEV CMD"
  },
  {
    id: 0xf8,
    description: "XADC REG",
    slices: [
      {
        mask: 0x80,
        shift: 7,
        description: "1 to write to XADC DRP port, 0 to read from XADC DRP port"
      },
      { mask: 0x7f, description: "XADC DRP register address DADDR" }
    ]
  },
  {
    id: 0xf9,
    description: "XADC D0"
  },
  {
    id: 0xfa,
    description: "XADC D1"
  }
];

const byId = new Map(NEXT_REG_DESCRIPTORS.map((d) => [d.id, d]));

/**
 * The documentation of a NextReg, or `undefined` for a register the Next does not implement.
 * @param id The register number
 */
export function getNextRegDescriptor(id: number): NextRegDescriptor | undefined {
  return byId.get(id & 0xff);
}
