// --- Machine-specific command identifiers
export const CZ88_HARD_RESET = "cz88-hard-reset";
export const CZ88_SOFT_RESET = "cz88-soft-reset";
export const CZ88_PRESS_BOTH_SHIFTS = "cz88-press-both-shifts";
export const CZ88_BATTERY_LOW = "cz88-battery-low";
export const INSERT_CARD_SLOT1 = "cz88-insert-slot1";
export const INSERT_CARD_SLOT2 = "cz88-insert-slot2";
export const INSERT_CARD_SLOT3 = "cz88-insert-slot3";
export const REMOVE_CARD_SLOT1 = "cz88-remove-slot1";
export const REMOVE_CARD_SLOT2 = "cz88-remove-slot2";
export const REMOVE_CARD_SLOT3 = "cz88-remove-slot3";
