type CharDescriptor = {
  // --- Character value
  v?: string;

  c?: "ctrl" | "pr" | "graph" | "udg" | "token";

  // --- Character tooltip
  t?: string;
};
export const ZxSpectrumChars: Record<number, CharDescriptor> = {
  0x00: { c: "ctrl" },
  0x01: { c: "ctrl" },
  0x02: { c: "ctrl" },
  0x03: { c: "ctrl" },
  0x04: { c: "ctrl" },
  0x05: { c: "ctrl" },
  0x06: { c: "ctrl", t: "(tab)" },
  0x07: { c: "ctrl" },
  0x08: { c: "ctrl", t: "(left)" },
  0x09: { c: "ctrl", t: "(right)" },
  0x0a: { c: "ctrl" },
  0x0b: { c: "ctrl" },
  0x0c: { c: "ctrl" },
  0x0d: { c: "ctrl", t: "(cr)" },
  0x0e: { c: "ctrl" },
  0x0f: { c: "ctrl" },

  0x10: { c: "pr", t: "(ink)" },
  0x11: { c: "pr", t: "(paper)" },
  0x12: { c: "pr", t: "(flash)" },
  0x13: { c: "pr", t: "(bright)" },
  0x14: { c: "pr", t: "(inverse)" },
  0x15: { c: "pr", t: "(over)" },
  0x16: { c: "pr", t: "(at)" },
  0x17: { c: "pr", t: "(tab)" },
  0x18: { c: "ctrl" },
  0x19: { c: "ctrl" },
  0x1a: { c: "ctrl" },
  0x1b: { c: "ctrl" },
  0x1c: { c: "ctrl" },
  0x1d: { c: "ctrl" },
  0x1e: { c: "ctrl" },
  0x1f: { c: "ctrl" },

  0x20: { v: "\xa0", t: "(space)" },
  0x21: { v: "!" },
  0x22: { v: "\"" },
  0x23: { v: "#" },
  0x24: { v: "$" },
  0x25: { v: "%" },
  0x26: { v: "&" },
  0x27: { v: "'" },
  0x28: { v: "(" },
  0x29: { v: ")" },
  0x2a: { v: "*" },
  0x2b: { v: "+" },
  0x2c: { v: "," },
  0x2d: { v: "-" },
  0x2e: { v: ".", t: "(dot)" },
  0x2f: { v: "/" },

  0x30: { v: "0" },
  0x31: { v: "1" },
  0x32: { v: "2" },
  0x33: { v: "3" },
  0x34: { v: "4" },
  0x35: { v: "5" },
  0x36: { v: "6" },
  0x37: { v: "7" },
  0x38: { v: "8" },
  0x39: { v: "9" },
  0x3a: { v: ":" },
  0x3b: { v: ";" },
  0x3c: { v: "<" },
  0x3d: { v: "=" },
  0x3e: { v: ">" },
  0x3f: { v: "?" },

  0x40: { v: "@" },
  0x41: { v: "A" },
  0x42: { v: "B" },
  0x43: { v: "C" },
  0x44: { v: "D" },
  0x45: { v: "E" },
  0x46: { v: "F" },
  0x47: { v: "G" },
  0x48: { v: "H" },
  0x49: { v: "I" },
  0x4a: { v: "J" },
  0x4b: { v: "K" },
  0x4c: { v: "L" },
  0x4d: { v: "M" },
  0x4e: { v: "N" },
  0x4f: { v: "O" },

  0x50: { v: "P" },
  0x51: { v: "Q" },
  0x52: { v: "R" },
  0x53: { v: "S" },
  0x54: { v: "T" },
  0x55: { v: "U" },
  0x56: { v: "V" },
  0x57: { v: "W" },
  0x58: { v: "X" },
  0x59: { v: "Y" },
  0x5a: { v: "Z" },
  0x5b: { v: "[" },
  0x5c: { v: "\\" },
  0x5d: { v: "]" },
  0x5e: { v: "^" },
  0x5f: { v: "_" },

  0x60: { v: "£" },
  0x61: { v: "a" },
  0x62: { v: "b" },
  0x63: { v: "c" },
  0x64: { v: "d" },
  0x65: { v: "e" },
  0x66: { v: "f" },
  0x67: { v: "g" },
  0x68: { v: "h" },
  0x69: { v: "i" },
  0x6a: { v: "j" },
  0x6b: { v: "k" },
  0x6c: { v: "l" },
  0x6d: { v: "m" },
  0x6e: { v: "n" },
  0x6f: { v: "o" },

  0x70: { v: "p" },
  0x71: { v: "q" },
  0x72: { v: "r" },
  0x73: { v: "s" },
  0x74: { v: "t" },
  0x75: { v: "u" },
  0x76: { v: "v" },
  0x77: { v: "w" },
  0x78: { v: "x" },
  0x79: { v: "y" },
  0x7a: { v: "z" },
  0x7b: { v: "{" },
  0x7c: { v: "|" },
  0x7d: { v: "}" },
  0x7e: { v: "~" },
  0x7f: { v: ".", t:"(copyright)" },

  0x80: { c: "graph" },
  0x81: { c: "graph" },
  0x82: { c: "graph" },
  0x83: { c: "graph" },
  0x84: { c: "graph" },
  0x85: { c: "graph" },
  0x86: { c: "graph" },
  0x87: { c: "graph" },
  0x88: { c: "graph" },
  0x89: { c: "graph" },
  0x8a: { c: "graph" },
  0x8b: { c: "graph" },
  0x8c: { c: "graph" },
  0x8d: { c: "graph" },
  0x8e: { c: "graph" },
  0x8f: { c: "graph" },

  0x90: { v: "A", c: "udg", t: "(UDG A)" },
  0x91: { v: "B", c: "udg", t: "(UDG B)" },
  0x92: { v: "C", c: "udg", t: "(UDG C)" },
  0x93: { v: "D", c: "udg", t: "(UDG D)" },
  0x94: { v: "E", c: "udg", t: "(UDG E)" },
  0x95: { v: "F", c: "udg", t: "(UDG F)" },
  0x96: { v: "G", c: "udg", t: "(UDG G)" },
  0x97: { v: "H", c: "udg", t: "(UDG H)" },
  0x98: { v: "I", c: "udg", t: "(UDG I)" },
  0x99: { v: "J", c: "udg", t: "(UDG J)" },
  0x9a: { v: "K", c: "udg", t: "(UDG K)" },
  0x9b: { v: "L", c: "udg", t: "(UDG L)" },
  0x9c: { v: "M", c: "udg", t: "(UDG M)" },
  0x9d: { v: "N", c: "udg", t: "(UDG N)" },
  0x9e: { v: "O", c: "udg", t: "(UDG O)" },
  0x9f: { v: "P", c: "udg", t: "(UDG P)" },

  0xa0: { v: "Q", c: "udg", t: "(UDG Q)" },
  0xa1: { v: "R", c: "udg", t: "(UDG R)" },
  0xa2: { v: "S", c: "udg", t: "(UDG S)" },
  0xa3: { v: "T", c: "udg", t: "(UDG T)" },
  0xa4: { v: "U", c: "udg", t: "(UDG U)" },
  0xa5: { c: "token", t: "RND" },
  0xa6: { c: "token", t: "INKEY$" },
  0xa7: { c: "token", t: "PI" },
  0xa8: { c: "token", t: "FN" },
  0xa9: { c: "token", t: "POINT" },
  0xaa: { c: "token", t: "SCREEN$" },
  0xab: { c: "token", t: "ATTR" },
  0xac: { c: "token", t: "AT" },
  0xad: { c: "token", t: "TAB" },
  0xae: { c: "token", t: "VAL$" },
  0xaf: { c: "token", t: "CODE" },

  0xb0: { c: "token", t: "VAL" },
  0xb1: { c: "token", t: "LEN" },
  0xb2: { c: "token", t: "SIN" },
  0xb3: { c: "token", t: "COS" },
  0xb4: { c: "token", t: "TAN" },
  0xb5: { c: "token", t: "ASN" },
  0xb6: { c: "token", t: "ACS" },
  0xb7: { c: "token", t: "ATN" },
  0xb8: { c: "token", t: "LN" },
  0xb9: { c: "token", t: "EXP" },
  0xba: { c: "token", t: "INT" },
  0xbb: { c: "token", t: "SQR" },
  0xbc: { c: "token", t: "SGN" },
  0xbd: { c: "token", t: "ABS" },
  0xbe: { c: "token", t: "PEEK" },
  0xbf: { c: "token", t: "IN" },

  0xc0: { c: "token", t: "USR" },
  0xc1: { c: "token", t: "STR$" },
  0xc2: { c: "token", t: "CHR$" },
  0xc3: { c: "token", t: "NOT" },
  0xc4: { c: "token", t: "BIN" },
  0xc5: { c: "token", t: "OR" },
  0xc6: { c: "token", t: "AND" },
  0xc7: { c: "token", t: "<=" },
  0xc8: { c: "token", t: ">=" },
  0xc9: { c: "token", t: "<>" },
  0xca: { c: "token", t: "LINE" },
  0xcb: { c: "token", t: "THEN" },
  0xcc: { c: "token", t: "TO" },
  0xcd: { c: "token", t: "STEP" },
  0xce: { c: "token", t: "DEF FN" },
  0xcf: { c: "token", t: "CAT" },

  0xd0: { c: "token", t: "FORMAT" },
  0xd1: { c: "token", t: "MOVE" },
  0xd2: { c: "token", t: "ERASE" },
  0xd3: { c: "token", t: "OPEN #" },
  0xd4: { c: "token", t: "CLOSE #" },
  0xd5: { c: "token", t: "MERGE" },
  0xd6: { c: "token", t: "VERIFY" },
  0xd7: { c: "token", t: "BEEP" },
  0xd8: { c: "token", t: "CIRCLE" },
  0xd9: { c: "token", t: "INK" },
  0xda: { c: "token", t: "PAPER" },
  0xdb: { c: "token", t: "FLASH" },
  0xdc: { c: "token", t: "BRIGHT" },
  0xdd: { c: "token", t: "INVERSE" },
  0xde: { c: "token", t: "OVER" },
  0xdf: { c: "token", t: "OUT" },

  0xe0: { c: "token", t: "LPRINT" },
  0xe1: { c: "token", t: "LLIST" },
  0xe2: { c: "token", t: "STOP" },
  0xe3: { c: "token", t: "READ" },
  0xe4: { c: "token", t: "DATA" },
  0xe5: { c: "token", t: "RESTORE" },
  0xe6: { c: "token", t: "NEW" },
  0xe7: { c: "token", t: "BORDER" },
  0xe8: { c: "token", t: "CONTINUE" },
  0xe9: { c: "token", t: "DIM" },
  0xea: { c: "token", t: "REM" },
  0xeb: { c: "token", t: "FOR" },
  0xec: { c: "token", t: "GO TO" },
  0xed: { c: "token", t: "GO SUB" },
  0xee: { c: "token", t: "INPUT" },
  0xef: { c: "token", t: "LOAD" },

  0xf0: { c: "token", t: "LIST" },
  0xf1: { c: "token", t: "LET" },
  0xf2: { c: "token", t: "PAUSE" },
  0xf3: { c: "token", t: "NEXT" },
  0xf4: { c: "token", t: "POKE" },
  0xf5: { c: "token", t: "PRINT" },
  0xf6: { c: "token", t: "PLOT" },
  0xf7: { c: "token", t: "RUN" },
  0xf8: { c: "token", t: "SAVE" },
  0xf9: { c: "token", t: "RANDOMIZE" },
  0xfa: { c: "token", t: "IF" },
  0xfb: { c: "token", t: "CLS" },
  0xfc: { c: "token", t: "DRAW" },
  0xfd: { c: "token", t: "CLEAR" },
  0xfe: { c: "token", t: "RETURN" },
  0xff: { c: "token", t: "COPY" },
};
