/*
 * Static hardware facts of every registered machine model, for the Select Machine dialog's hardware
 * sheet (`.plans/MACHINE_SELECT_DIALOG_PLAN.md` §4.2, §5.1b).
 *
 * Why a table: most of these numbers live inside the machine hosts or the WASM C cores, and the
 * dialog must not instantiate a machine to read them. Three rules keep the table honest:
 *
 * 1. **Derive what the registry already says** - RAM from `MC_MEM_SIZE` / `MC_Z88_INTRAM`, banks from
 *    `MF_BANK`, the clock multiplier from `MF_ALLOW_CLOCK_MULTIPLIER`, PAL/NTSC from `MC_SCREEN_FREQ`,
 *    floppy drives from `MC_DISK_SUPPORT`, the Z88 ROM and keyboard from the model config. Those are
 *    resolved by `getHardwareSpec`, never written here.
 * 2. **Import a constant where a host exports one** (`ZX8081_*`, `Z88_*`).
 * 3. **Everything else is checked against the running cores** by `test/machines/hardware-specs*.test.ts`.
 *    A fact no source pins down (ZX81 lines per frame, the ZX80's line length) is left out and the
 *    sheet shows "—"; nothing here is written from memory.
 *
 * Must stay free of emulator and renderer imports: it is read by the dialog in both windows.
 */
import type { MachineInfo } from "./info-types";
import {
  MC_DISK_SUPPORT,
  MC_MEM_SIZE,
  MC_SCREEN_FREQ,
  MC_Z88_INTRAM,
  MC_Z88_KEYBOARD,
  MC_Z88_SLOT0,
  MC_ZX80_ROM8K,
  MF_ALLOW_CLOCK_MULTIPLIER,
  MF_BANK,
  MI_C64,
  MI_SPECTRUM_128,
  MI_SPECTRUM_3E,
  MI_SPECTRUM_48,
  MI_Z88,
  MI_ZX80,
  MI_ZX81,
  MI_ZXNEXT
} from "./constants";
import {
  ZX80_ROM,
  ZX81_ROM,
  ZX8081_BASE_CLOCK_FREQUENCY,
  ZX8081_TACTS_IN_FRAME_NTSC,
  ZX8081_TACTS_IN_FRAME_PAL
} from "@emu/machines/zx8081/zx8081MachineInfo";
import {
  Z88_BASE_CLOCK_FREQUENCY,
  Z88_TACTS_IN_FRAME,
  Z88_UI_FRAME_FREQUENCY
} from "@emu/machines/z88/z88MachineInfo";
import { getP3RomSet } from "@emu/machines/zxSpectrumP3e/p3RomSets";

/** One ROM image the machine loads */
export type RomImage = { id: string; kb: number; role?: string };

/** Frame timing, in the CPU's own clock unit */
export type FrameTiming = {
  unit: "T-states" | "cycles";
  perLine?: number;
  linesPerFrame?: number;
  perFrame?: number;
  /** Frames per second. Derived from the clock and `perFrame` when omitted. */
  frameHz?: number;
  /** A second refresh rate, e.g. the Z88 LCD's */
  displayHz?: number;
  note?: string;
};

/** The picture */
export type DisplaySpec = {
  kind: "crt" | "lcd";
  /** The bitmap/paper area */
  width: number;
  height: number;
  /** The visible raster, border included (equal to width/height for an LCD) */
  rasterWidth: number;
  rasterHeight: number;
  /** Says what the raster is when it is not "with border" */
  rasterLabel?: string;
  colours: string;
  attributes?: string;
  text?: string;
  layers?: string;
  videoChip?: string;
  otherSizes?: string;
};

/** What the table stores for a machine, optionally overridden per model */
export type HardwareSpecEntry = {
  cpu: string;
  clockHz: number;
  turbo?: string;
  rom: RomImage[];
  /** RAM when the model config does not say (`MC_MEM_SIZE`, `MC_Z88_INTRAM`) */
  ramKb: number;
  bankKb?: number;
  addressSpace?: string;
  display: DisplaySpec;
  timing: FrameTiming;
  sound: string[];
  media: string[];
  input: { label: string; value: string }[];
};

type Overrides = Partial<Omit<HardwareSpecEntry, "display" | "timing">> & {
  display?: Partial<DisplaySpec>;
  timing?: Partial<FrameTiming>;
};

type MachineSpecs = { base: HardwareSpecEntry; models?: Record<string, Overrides> };

const SPECTRUM_DISPLAY: DisplaySpec = {
  kind: "crt",
  width: 256,
  height: 192,
  rasterWidth: 352,
  rasterHeight: 288,
  colours: "15 (8 colours × BRIGHT)",
  attributes: "32 × 24 cells of 8 × 8 px, FLASH"
};
const SPECTRUM_KEYBOARD = [{ label: "Keyboard", value: "40-key Spectrum" }];
const SPECTRUM_TAPE = "Tape (TAP, TZX)";

const ZX8081_BASE: HardwareSpecEntry = {
  cpu: "Zilog Z80",
  clockHz: ZX8081_BASE_CLOCK_FREQUENCY,
  rom: [{ id: ZX81_ROM, kb: 8 }],
  ramKb: 16,
  display: {
    kind: "crt",
    width: 256,
    height: 192,
    rasterWidth: 352,
    rasterHeight: 288,
    colours: "Monochrome",
    text: "32 × 24 characters, generated by the CPU"
  },
  timing: { unit: "T-states", perFrame: ZX8081_TACTS_IN_FRAME_PAL },
  sound: [],
  media: ["Tape (.P)"],
  input: [{ label: "Keyboard", value: "40-key membrane" }]
};
const ZX8081_NTSC: Overrides = {
  display: { rasterHeight: 240 },
  timing: { perFrame: ZX8081_TACTS_IN_FRAME_NTSC }
};

/**
 * The table, keyed by machine ID. `""` is the key of a machine without models.
 */
export const HARDWARE_SPECS: Readonly<Record<string, MachineSpecs>> = {
  [MI_SPECTRUM_48]: {
    // --- ZxSpectrum48WasmHost.ts, sp48.c, CommonScreenDevice.ZxSpectrum48*ScreenConfiguration
    base: {
      cpu: "Zilog Z80",
      clockHz: 3_500_000,
      rom: [{ id: "sp48", kb: 16 }],
      ramKb: 48,
      display: SPECTRUM_DISPLAY,
      timing: { unit: "T-states", perLine: 224, linesPerFrame: 312, perFrame: 69_888 },
      sound: ["Beeper"],
      media: [SPECTRUM_TAPE],
      input: SPECTRUM_KEYBOARD
    },
    models: {
      ntsc: {
        clockHz: 3_527_500,
        display: { rasterHeight: 240 },
        timing: { linesPerFrame: 264, perFrame: 59_136 }
      }
    }
  },
  [MI_SPECTRUM_128]: {
    // --- ZxSpectrum128WasmHost.ts, sp128.c
    base: {
      cpu: "Zilog Z80",
      clockHz: 3_546_900,
      rom: [
        { id: "sp128-0", kb: 16, role: "128K editor" },
        { id: "sp128-1", kb: 16, role: "48K BASIC" }
      ],
      ramKb: 128,
      bankKb: 16,
      display: { ...SPECTRUM_DISPLAY, rasterHeight: 287 },
      timing: { unit: "T-states", perLine: 228, linesPerFrame: 311, perFrame: 70_908 },
      sound: ["Beeper", "AY-3-8912 PSG"],
      media: [SPECTRUM_TAPE],
      input: SPECTRUM_KEYBOARD
    }
  },
  [MI_SPECTRUM_3E]: {
    // --- ZxSpectrumP3eWasmHost.ts, spp3e.c
    base: {
      cpu: "Zilog Z80",
      clockHz: 3_546_900,
      rom: [0, 1, 2, 3].map((page) => ({ id: `spp3e-${page}`, kb: 16 })),
      ramKb: 128,
      bankKb: 16,
      display: { ...SPECTRUM_DISPLAY, rasterHeight: 287 },
      timing: { unit: "T-states", perLine: 228, linesPerFrame: 311, perFrame: 70_908 },
      sound: ["Beeper", "AY-3-8912 PSG"],
      media: [SPECTRUM_TAPE],
      input: SPECTRUM_KEYBOARD
    }
  },
  [MI_ZXNEXT]: {
    // --- ZxNextWasmHost.ts, ZxNextWasmV2Machine.ts (ROMs), zxnext.c (timing), nextMemoryLayout.ts
    base: {
      cpu: "Z80N",
      clockHz: 3_500_000,
      turbo: "3.5 / 7 / 14 / 28 MHz, set by NextReg $07",
      rom: [
        { id: "enNextZX", kb: 64, role: "Next ROMs" },
        { id: "enAltZX", kb: 32, role: "alternative ROM" },
        { id: "enNxtmmc", kb: 8, role: "DivMMC" },
        { id: "enNextMf", kb: 8, role: "Multiface" }
      ],
      ramKb: 1792,
      bankKb: 8,
      display: {
        kind: "crt",
        width: 256,
        height: 192,
        rasterWidth: 720,
        rasterHeight: 288,
        rasterLabel: "output buffer",
        colours: "256 on screen, from 512-colour palettes",
        layers: "ULA, Layer 2 (up to 320 × 256), tilemap, sprites, copper"
      },
      timing: {
        unit: "T-states",
        note: "Frame timing follows the video mode (48K, 128K/+3, Pentagon) and 50/60 Hz, set by NextRegs $03 and $05."
      },
      sound: ["Beeper", "TurboSound (3 × AY)", "4-channel DAC (SpecDrum)"],
      media: ["SD card (FAT32 image)"],
      input: [
        { label: "Keyboard", value: "Next, with extended keys" },
        { label: "Mouse", value: "Kempston" },
        { label: "Joysticks", value: "2 ports" }
      ]
    }
  },
  [MI_Z88]: {
    // --- z88MachineInfo.ts, z88-screen.c, z88-memory.c
    base: {
      cpu: "Zilog Z80",
      clockHz: Z88_BASE_CLOCK_FREQUENCY,
      rom: [],
      ramKb: 32,
      bankKb: 16,
      addressSpace: "4 MB",
      display: {
        kind: "lcd",
        width: 640,
        height: 64,
        rasterWidth: 640,
        rasterHeight: 64,
        colours: "Monochrome LCD",
        attributes: "grey, reverse, flash, underline",
        otherSizes: "640 × 256, 320 or 480 by configuration"
      },
      timing: {
        unit: "T-states",
        perFrame: Z88_TACTS_IN_FRAME,
        displayHz: Z88_BASE_CLOCK_FREQUENCY / Z88_TACTS_IN_FRAME / Z88_UI_FRAME_FREQUENCY
      },
      sound: ["Beeper"],
      media: ["Card slots 1–3 (RAM, EPROM, flash)"],
      input: []
    }
  },
  [MI_ZX81]: {
    base: ZX8081_BASE,
    models: { "zx81-16k-us": ZX8081_NTSC, "zx81-1k-us": ZX8081_NTSC }
  },
  [MI_ZX80]: {
    base: {
      ...ZX8081_BASE,
      rom: [{ id: ZX80_ROM, kb: 4 }],
      media: ["Tape (.O)"],
      display: { ...ZX8081_BASE.display, text: "32 × 24 characters; blank while the CPU computes" }
    }
  },
  [MI_C64]: {
    // --- C64Machine.ts, vic/vic-models.ts, C64VicDevice.ts
    base: {
      cpu: "MOS 6510",
      clockHz: 985_248,
      rom: [
        { id: "c64-basic", kb: 8, role: "BASIC" },
        { id: "c64-kernal-pal", kb: 8, role: "KERNAL" },
        { id: "c64-chargen", kb: 4, role: "character set" }
      ],
      ramKb: 64,
      display: {
        kind: "crt",
        width: 320,
        height: 200,
        rasterWidth: 384,
        rasterHeight: 272,
        colours: "16",
        videoChip: "VIC-II MOS 6569R3"
      },
      timing: { unit: "cycles", perLine: 63, linesPerFrame: 312, perFrame: 19_656 },
      sound: ["SID"],
      media: ["Tape"],
      input: [{ label: "Keyboard", value: "C64" }]
    },
    models: {
      ntsc: {
        clockHz: 1_022_727,
        rom: [
          { id: "c64-basic", kb: 8, role: "BASIC" },
          { id: "c64-kernal-ntsc", kb: 8, role: "KERNAL" },
          { id: "c64-chargen", kb: 4, role: "character set" }
        ],
        display: { rasterHeight: 247, videoChip: "VIC-II MOS 8562" },
        timing: { perLine: 65, linesPerFrame: 263, perFrame: 17_095 }
      }
    }
  }
};

const Z88_KEYBOARD_NAMES: Record<string, string> = {
  uk: "UK",
  de: "German",
  fr: "French",
  es: "Spanish",
  it: "Italian",
  dk: "Danish",
  se: "Swedish/Finnish"
};

/** A model's hardware facts, with everything the registry knows resolved in */
export type HardwareSpec = HardwareSpecEntry & {
  machineId: string;
  modelId?: string;
  standard: "PAL" | "NTSC" | "LCD" | "PAL/NTSC";
  clockMultiplier: boolean;
  bankCount?: number;
};

/**
 * The hardware facts of a model.
 * @param machine The registry entry of the machine
 * @param modelId The (canonical) model ID; omitted for a machine without models
 * @returns undefined when the table has no entry for the machine
 */
export function getHardwareSpec(machine: MachineInfo, modelId?: string): HardwareSpec | undefined {
  const entry = HARDWARE_SPECS[machine.machineId];
  if (!entry) return undefined;
  const model = modelId ? machine.models?.find((m) => m.modelId === modelId) : undefined;
  if (modelId && !model) return undefined;
  const config = { ...(machine.config ?? {}), ...(model?.config ?? {}) };
  const over = (modelId && entry.models?.[modelId]) || {};

  const spec: HardwareSpecEntry = {
    ...entry.base,
    ...over,
    display: { ...entry.base.display, ...over.display },
    timing: { ...entry.base.timing, ...over.timing },
    input: [...(over.input ?? entry.base.input)],
    media: [...(over.media ?? entry.base.media)],
    rom: [...(over.rom ?? entry.base.rom)]
  };

  // --- RAM from the model configuration
  if (typeof config[MC_MEM_SIZE] === "number") spec.ramKb = config[MC_MEM_SIZE];
  if (typeof config[MC_Z88_INTRAM] === "number") spec.ramKb = (config[MC_Z88_INTRAM] + 1) * 16;

  // --- The ZX80 with the ZX81's 8K ROM
  if (config[MC_ZX80_ROM8K]) spec.rom = [{ id: ZX81_ROM, kb: 8 }];

  // --- The +2A/+3/+2E/+3E boots the model's ROM set (the +3E ROMs when the config does not say)
  if (machine.machineId === MI_SPECTRUM_3E) {
    const romId = getP3RomSet(config).romId;
    spec.rom = [0, 1, 2, 3].map((page) => ({ id: `${romId}-${page}`, kb: 16 }));
  }

  // --- The Z88's internal ROM sits in slot 0
  const slot0 = config[MC_Z88_SLOT0];
  if (slot0 && typeof slot0.file === "string") {
    spec.rom = [{ id: slot0.file, kb: slot0.size, role: slot0.cardType === "ROM" ? "OZ" : `OZ, ${slot0.cardType} flash` }];
  }
  if (machine.machineId === MI_Z88) {
    const layout = Z88_KEYBOARD_NAMES[config[MC_Z88_KEYBOARD] ?? "uk"] ?? config[MC_Z88_KEYBOARD];
    spec.input = [{ label: "Keyboard", value: `64 keys, ${layout} layout` }];
  }

  // --- Floppy drives (+3E)
  if (typeof config[MC_DISK_SUPPORT] === "number") {
    const drives = config[MC_DISK_SUPPORT];
    spec.media.push(
      drives === 0 ? "No floppy drive" : drives === 1 ? "Floppy disk drive A (DSK)" : "Floppy disk drives A and B (DSK)"
    );
  }

  const standard: HardwareSpec["standard"] =
    spec.display.kind === "lcd"
      ? "LCD"
      : machine.machineId === MI_ZXNEXT
        ? "PAL/NTSC"
        : config[MC_SCREEN_FREQ] === "ntsc"
          ? "NTSC"
          : "PAL";

  // --- Frames per second follow from the clock; a machine whose timing depends on its video mode
  // --- (the Next) has none
  const frameHz =
    spec.timing.frameHz ?? (spec.timing.perFrame ? spec.clockHz / spec.timing.perFrame : undefined);

  const banks = machine.features?.[MF_BANK];
  return {
    ...spec,
    machineId: machine.machineId,
    modelId: model?.modelId,
    standard,
    clockMultiplier: machine.features?.[MF_ALLOW_CLOCK_MULTIPLIER] !== false,
    bankCount: typeof banks === "number" ? banks : undefined,
    timing: { ...spec.timing, frameHz }
  };
}
