/**
 * Available action types
 */
export interface ActionTypes {
  UNLOAD_WINDOWS: null;
  EMU_LOADED: null;
  EMU_STATE_SYNCHED: null,
  IDE_LOADED: null;
  IDE_STATE_SYNCHED: null,
  IS_WINDOWS: null;
  SET_THEME: null;
  IDE_FOCUSED: null,
  EMU_FOCUSED: null,
  DIM_MENU: null,
  INC_MENU_VERSION: null;

  EMU_SET_KEYBOARD_LAYOUT: null;
  SHOW_FRAME_INFO: null;

  SET_ACTIVITY: null;
  SET_SIDEBAR_PANEL_EXPANDED: null;
  SET_SIDEBAR_PANELS_STATE: null;
  SET_SIDEBAR_PANEL_SIZE: null;

  INC_DOC_HUB_SERVICE_VERSION: null;
  SET_VOLATILE_DOC_STATE: null;
  INC_EDITOR_VERSION: null;

  SET_TOOLS: null;

  SET_MACHINE_TYPE: null;
  SET_MODEL_TYPE: null;
  SET_MACHINE_CONFIG: null;
  SET_MACHINE_SPECIFIC: null;
  SET_MACHINE_STATE: null;
  SET_DEBUGGING: null;
  MUTE_SOUND: null;
  INC_EMU_VIEW_VERSION: null;
  SET_SOUND_LEVEL: null;
  SET_CLOCK_MULTIPLIER: null;
  SET_AUDIO_SAMPLE_RATE: null;
  SET_DISK_FILE: null;
  PROTECT_DISK: null;

  SET_IDE_STATUS_MESSAGE: null;
  INC_BPS_VERSION: null;
  INC_TOOL_CMD_SEQ: null;

  OPEN_FOLDER: null;
  CLOSE_FOLDER: null;
  SET_BUILD_ROOT: null;
  INC_PROJECT_FILE_VERSION: null;
  INC_PROJECT_VIEWSTATE_VERSION: null;
  ADD_EXCLUDED_PROJECT_ITEMS: null;
  SET_EXCLUDED_PROJECT_ITEMS: null;
  REFRESH_EXCLUDED_PROJECT_ITEMS: null;
  SET_PROJECT_BUILD_FILE: null;
  INC_BUILD_FILE_VERSION: null;

  DISPLAY_DIALOG: null;

  RESET_COMPILE: null;
  START_COMPILE: null;
  END_COMPILE: null;
  INC_INJECTION_VERSION: null;

  APPLY_PROJECT_SETTING: null;
  APPLY_USER_SETTING: null;
  SAVE_USER_SETTINGS: null;
  SAVE_PROJECT_SETTINGS: null;

  START_SCREEN_DISPLAYED: null;
  SET_KEY_MAPPINGS: null;
  SET_MEDIA: null;

  INC_EXPLORER_VIEW_VERSION: null;

  SET_SCRIPTS_STATUS: null;

  SET_IDE_DISABLE_AUTO_COMPLETE: null;
  SET_IDE_EXPORT_DIALOG: null;
  SET_WORKSPACE_SETTINGS: null;
  SET_SIDEBAR_WIDTH: null;
  SET_TOOL_PANEL_HEIGHT: null;

  // --- Globa setting now use this action type
  INIT_GLOBAL_SETTINGS: null;
  SET_GLOBAL_SETTING: null;
}