#include "zxnext-nmi.h"

static uint8_t nmiSignalActive;
static uint8_t nmiCause;
static uint8_t stacklessNmiEnabled;
static uint8_t stacklessNmiProcessed;
static uint16_t nmiReturnAddress;

/*
 * The NMI state machine (zxnext.vhd ~2046-2130), mirroring ZxNextMachine (updateNmiSources,
 * stepNmiStateMachine). Causes - the M1/DRIVE buttons, NextReg $02 bits 3/2 and the $D8 I/O trap -
 * become pending; at an opcode fetch in IDLE or FETCH one is taken as the source (Multiface first,
 * gated by NextReg $06 bits 3/4), the state machine raises NMI, pages the Multiface in when the CPU
 * fetches $0066, holds while the device serves it, and returns to IDLE.
 */
#define ZXNEXT_NMI_IDLE 0u
#define ZXNEXT_NMI_FETCH 1u
#define ZXNEXT_NMI_HOLD 2u
#define ZXNEXT_NMI_END 3u
static uint8_t nmiState;
static uint8_t nmiSourceMf;
static uint8_t nmiSourceDivMmc;
static uint8_t nmiPendingMf;
static uint8_t nmiPendingDivMmc;
/* NextReg $02 bits 3/2: set when $02 generates the NMI, cleared by writing the bit as 0 (~3820-3840) */
static uint8_t nmiNextReg02Mf;
static uint8_t nmiNextReg02DivMmc;

static void zxnextNmiReset(void) {
  nmiSignalActive = 0;
  nmiCause = 0;
  stacklessNmiEnabled = 0;
  stacklessNmiProcessed = 0;
  nmiReturnAddress = 0;
  nmiState = ZXNEXT_NMI_IDLE;
  nmiSourceMf = 0;
  nmiSourceDivMmc = 0;
  nmiPendingMf = 0;
  nmiPendingDivMmc = 0;
  nmiNextReg02Mf = 0;
  nmiNextReg02DivMmc = 0;
}

static uint32_t zxnextNmiAcceptCause(void) {
  return nmiState == ZXNEXT_NMI_IDLE || nmiState == ZXNEXT_NMI_FETCH;
}

/*
 * ~2046-2047, ~2063-2066: an NMI cause (a button, a $02 write, the I/O trap) is a one-cycle pulse,
 * asserted only while its $06 enable is set and latched only while no source is active. A pulse that
 * misses either is gone - it does not wait for the enable.
 */
static void zxnextNmiRequestMultiface(void) {
  if (zxnextNmiAcceptCause() && !nmiSourceMf && !nmiSourceDivMmc && zxnextDivMmcGetEnableMultifaceNmiByM1Button()) {
    nmiPendingMf = 1u;
  }
}

static void zxnextNmiRequestDivMmc(void) {
  if (zxnextNmiAcceptCause() && !nmiSourceMf && !nmiSourceDivMmc && zxnextDivMmcGetEnableNmiByDriveButton()) {
    nmiPendingDivMmc = 1u;
  }
}

static void zxnextNmiUpdateSources(void) {
  if (nmiSourceMf || nmiSourceDivMmc) return;
  uint32_t assertMf = nmiPendingMf && zxnextDivMmcGetEnableMultifaceNmiByM1Button();
  uint32_t assertDivMmc = nmiPendingDivMmc && zxnextDivMmcGetEnableNmiByDriveButton();
  uint32_t conmem = (zxnextDivMmcGetPortE3() & 0x80u) != 0u;
  if (assertMf && !conmem && !zxnextDivMmcGetNmiHold()) {
    nmiSourceMf = 1u;
  } else if (assertDivMmc && !zxnextMultifaceIsActive()) {
    nmiSourceDivMmc = 1u;
  }
  /* The causes are pulses: one that lost the arbitration is gone */
  nmiPendingMf = 0u;
  nmiPendingDivMmc = 0u;
}

static void zxnextNmiBeforeOpcodeFetch(uint32_t pc) {
  if (zxnextNmiAcceptCause()) zxnextNmiUpdateSources();
  switch (nmiState) {
    case ZXNEXT_NMI_IDLE:
      if (nmiSourceMf || nmiSourceDivMmc) {
        nmiState = ZXNEXT_NMI_FETCH;
        nmiSignalActive = 1u;
        if (nmiSourceMf) zxnextMultifacePressNmiButton();
        if (nmiSourceDivMmc) zxnextDivMmcArmNmiButton();
      }
      break;
    case ZXNEXT_NMI_FETCH:
      if ((pc & 0xffffu) == 0x0066u) {
        if (nmiSourceMf) zxnextMultifaceOnFetch0066();
        nmiState = ZXNEXT_NMI_HOLD;
        nmiSignalActive = 0u;
      }
      break;
    case ZXNEXT_NMI_HOLD: {
      uint32_t hold = nmiSourceMf ? zxnextMultifaceNmiHold() : nmiSourceDivMmc ? zxnextDivMmcGetNmiHold() : 0u;
      /* S_NMI_END lasts one CPU clock (no I/O write is in progress at an opcode fetch): pass through it
         at once, so a cause raised by the next instruction is accepted, as on the FPGA */
      if (!hold) {
        nmiSourceMf = 0u;
        nmiSourceDivMmc = 0u;
        nmiState = ZXNEXT_NMI_IDLE;
      }
      break;
    }
    default:
      nmiSourceMf = 0u;
      nmiSourceDivMmc = 0u;
      nmiState = ZXNEXT_NMI_IDLE;
      break;
  }
}

static void zxnextNmiNextReg02Write(uint32_t value) {
  uint32_t accept = zxnextNmiAcceptCause();
  if ((value & 0x08u) != 0u) {
    if (accept) nmiNextReg02Mf = 1u;
    zxnextNmiRequestMultiface();
  } else {
    nmiNextReg02Mf = 0u;
  }
  if ((value & 0x04u) != 0u) {
    if (accept) nmiNextReg02DivMmc = 1u;
    zxnextNmiRequestDivMmc();
  } else {
    nmiNextReg02DivMmc = 0u;
  }
  if ((value & 0x10u) == 0u) zxnextNextRegs[0xdau] = 0u; /* clears the I/O trap cause */
}

/* $02 bits 4-2: I/O trap (cause in $DA), Multiface and DivMMC NMI generated by $02 */
static uint32_t zxnextNmiNextReg02Flags(void) {
  return (zxnextNextRegs[0xdau] != 0u ? 0x10u : 0x00u) |
    (nmiNextReg02Mf ? 0x08u : 0x00u) | (nmiNextReg02DivMmc ? 0x04u : 0x00u);
}

/* +3 FDC I/O trap (~3815, ~3846-3875): cause 1 $2FFD read, 2 $3FFD read, 3 $3FFD write. */
static void zxnextNmiIoTrap(uint32_t cause, uint32_t value, uint32_t isWrite) {
  if (isWrite) zxnextNextRegs[0xd9u] = (uint8_t)value;
  if (zxnextNmiAcceptCause()) zxnextNextRegs[0xdau] = (uint8_t)(cause & 0x03u);
  zxnextNmiRequestMultiface();
}

static void zxnextNmiSetSignal(uint32_t active) {
  nmiSignalActive = active != 0;
  if (nmiSignalActive && nmiCause == 0) nmiCause = 1;
}

static uint32_t zxnextNmiGetSignal(void) {
  return nmiSignalActive;
}

static void zxnextNmiSetCause(uint32_t cause) {
  nmiCause = (uint8_t)cause;
  nmiSignalActive = cause != 0;
}

static uint32_t zxnextNmiGetCause(void) {
  return nmiCause;
}

static void zxnextNmiSetStacklessEnabled(uint32_t enabled) {
  stacklessNmiEnabled = enabled != 0;
  /* ~2031: clearing $C0 bit 3 cancels the pending stackless RETN */
  if (!stacklessNmiEnabled) stacklessNmiProcessed = 0;
}

static uint32_t zxnextNmiGetStacklessEnabled(void) {
  return stacklessNmiEnabled;
}

static void zxnextNmiSetReturnAddress(uint32_t address) {
  nmiReturnAddress = (uint16_t)address;
}

static uint32_t zxnextNmiGetReturnAddress(void) {
  return nmiReturnAddress;
}

static uint32_t zxnextNmiGetStacklessProcessed(void) {
  return stacklessNmiProcessed;
}

/* ~2031-2037: `z80_stackless_retn_en` - set by a stackless acknowledge whatever the NMI source (the
   Multiface ROM restores SP to its NMI-time value before its RETN, so it works either way). */
static void zxnextNmiMarkAccepted(void) {
  nmiSignalActive = 0;
  if (stacklessNmiEnabled) stacklessNmiProcessed = 1;
}

static void zxnextNmiAfterRetn(void) {
  nmiCause = 0;
  if (stacklessNmiProcessed) {
    stacklessNmiProcessed = 0;
    cpuPc = nmiReturnAddress;
  }
}
