// Generated by scripts/kbasic-help-data.cjs from .ai/zxbasic-syntax/zxbasic-syntax.json,
// .ai/kbasic/stdlib-api.json, src/main/kbasic/stdlib and scripts/kbasic-help-overrides.json.
// Do not edit: change the sources and run `npm run kbasic:help`.
// Paraphrased from the ZX BASIC documentation, CC BY 4.0, (c) Jose Rodriguez-Rosa (Boriel) and contributors.
import type {
  BasicHelpEntry,
  BasicLibraryHelp,
  BasicLibraryRoutineHelp,
  BasicPragmaHelp
} from "./help-types";

/** The attribution keyword and library help carries (hover footers show it). */
export const HELP_ATTRIBUTION = "Paraphrased from the ZX BASIC documentation, CC BY 4.0, (c) Jose Rodriguez-Rosa (Boriel) and contributors.";

/** Every keyword, with its syntax and a one-line summary. */
export const KEYWORD_HELP: readonly BasicHelpEntry[] = [
  {
    "name": "ABS",
    "kind": "function",
    "display": [
      "ABS(expr)"
    ],
    "summary": "Argument: numeric. Result: same type as the argument.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "ACS",
    "kind": "function",
    "display": [
      "ACS(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "AND",
    "kind": "operator",
    "display": [
      "AND"
    ],
    "summary": "Operands: numeric (0 is false, non-zero true). Result: boolean 0/1."
  },
  {
    "name": "AS",
    "kind": "modifier",
    "display": [
      "DIM name AS type",
      "FUNCTION name(...) AS type"
    ],
    "summary": "Gives the type of a variable, array, constant, parameter or FUNCTION result."
  },
  {
    "name": "ASM",
    "kind": "statement",
    "display": [
      "ASM … END ASM"
    ],
    "summary": "Passes the enclosed lines verbatim to the built-in Z80 assembler."
  },
  {
    "name": "ASN",
    "kind": "function",
    "display": [
      "ASN(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "AT",
    "kind": "modifier",
    "display": [
      "PRINT AT row, column; …",
      "DIM name AS type AT address"
    ],
    "summary": "PRINT AT row, column positions the cursor; DIM ... AT address maps a variable to memory."
  },
  {
    "name": "ATN",
    "kind": "function",
    "display": [
      "ATN(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "BAND",
    "kind": "operator",
    "display": [
      "BAND"
    ],
    "summary": "Operands: integral (decimals convert to Long). Result: common type."
  },
  {
    "name": "BEEP",
    "kind": "statement",
    "display": [
      "BEEP expr, expr"
    ],
    "summary": "Sounds the beeper: duration in seconds, then pitch in semitones relative to middle C."
  },
  {
    "name": "BIN",
    "kind": "misc",
    "display": [
      "BIN digits"
    ],
    "summary": "Reads the token after it as binary digits: BIN 101 is 5."
  },
  {
    "name": "BNOT",
    "kind": "operator",
    "display": [
      "BNOT"
    ],
    "summary": "Operands: integral (unary). Result: same type, all bits inverted."
  },
  {
    "name": "BOLD",
    "kind": "statement",
    "display": [
      "BOLD expr"
    ],
    "summary": "Permanent attribute statement (ZX BASIC extension): emphasised glyphs when the operand (converted to UByte) is non-zero."
  },
  {
    "name": "BOR",
    "kind": "operator",
    "display": [
      "BOR"
    ],
    "summary": "Operands: integral. Result: common type."
  },
  {
    "name": "BORDER",
    "kind": "statement",
    "display": [
      "BORDER expr"
    ],
    "summary": "Sets the border colour."
  },
  {
    "name": "BRIGHT",
    "kind": "statement",
    "display": [
      "BRIGHT expr"
    ],
    "summary": "Permanent attribute statement."
  },
  {
    "name": "BXOR",
    "kind": "operator",
    "display": [
      "BXOR"
    ],
    "summary": "Operands: integral. Result: common type."
  },
  {
    "name": "BYREF",
    "kind": "modifier",
    "display": [
      "BYREF name AS type"
    ],
    "summary": "The parameter receives the caller's variable, not a copy of its value."
  },
  {
    "name": "BYTE",
    "kind": "type",
    "display": [
      "BYTE"
    ],
    "summary": "1 byte, signed: -128..127."
  },
  {
    "name": "BYVAL",
    "kind": "modifier",
    "display": [
      "BYVAL name AS type"
    ],
    "summary": "The parameter receives a copy of the value (the default unless default_byref is on)."
  },
  {
    "name": "CAST",
    "kind": "function",
    "display": [
      "CAST(type, expr)"
    ],
    "summary": "Argument: numeric. Result: the named type.",
    "params": [
      "type",
      "expr"
    ]
  },
  {
    "name": "CHR",
    "kind": "function",
    "display": [
      "CHR(expr {, expr })"
    ],
    "summary": "Argument: each converted to UByte. Result: String with one character per argument; parentheses mandatory.",
    "params": [
      "expr",
      "…"
    ]
  },
  {
    "name": "CHR$",
    "kind": "function",
    "display": [
      "CHR$(expr {, expr })"
    ],
    "summary": "Argument: each converted to UByte. Result: String with one character per argument; parentheses mandatory.",
    "params": [
      "expr",
      "…"
    ]
  },
  {
    "name": "CIRCLE",
    "kind": "statement",
    "display": [
      "CIRCLE [ attr-list ] expr, expr, expr"
    ],
    "summary": "Draws a circle at x, y with radius r."
  },
  {
    "name": "CLS",
    "kind": "statement",
    "display": [
      "CLS"
    ],
    "summary": "Clears the screen with the current permanent attributes."
  },
  {
    "name": "CODE",
    "kind": "function",
    "display": [
      "CODE(string-expr)"
    ],
    "summary": "Argument: String. Result: UByte code of the first character; 0 for the empty string.",
    "params": [
      "string-expr"
    ]
  },
  {
    "name": "CONST",
    "kind": "declaration",
    "display": [
      "CONST identifier [ AS type ] = const-expr"
    ],
    "summary": "Declares a compile-time constant."
  },
  {
    "name": "CONTINUE",
    "kind": "statement",
    "display": [
      "CONTINUE ( DO | FOR | WHILE )"
    ],
    "summary": "Restarts the innermost enclosing loop of the named kind (goes to its next iteration)."
  },
  {
    "name": "COS",
    "kind": "function",
    "display": [
      "COS(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "DATA",
    "kind": "statement",
    "display": [
      "DATA expr {, expr }"
    ],
    "summary": "Provides items for READ."
  },
  {
    "name": "DECLARE",
    "kind": "declaration",
    "display": [
      "DECLARE ( sub-header | function-header )"
    ],
    "summary": "Forward-declares a SUB or FUNCTION header without a body, so it can be called before its definition with a known signature."
  },
  {
    "name": "DIM",
    "kind": "declaration",
    "display": [
      "DIM idlist [ AS type ]",
      "DIM identifier [ AS type ] = expr",
      "DIM identifier [ AS type ] AT const-address",
      "DIM identifier (bounds) [ AS type ]",
      "DIM identifier (bounds) [ AS type ] AT const-address",
      "DIM identifier (bounds) [ AS type ] => vector",
      "DIM identifier (bounds) [ AS type ] = vector"
    ],
    "summary": "Declares scalars or arrays."
  },
  {
    "name": "DO",
    "kind": "statement",
    "display": [
      "DO … LOOP",
      "DO … LOOP UNTIL expr",
      "DO … LOOP WHILE expr",
      "DO UNTIL expr … LOOP",
      "DO WHILE expr … LOOP"
    ],
    "summary": "DO ..."
  },
  {
    "name": "DRAW",
    "kind": "statement",
    "display": [
      "DRAW [ attr-list ] expr, expr [, expr ]"
    ],
    "summary": "Draws a line relative to the last plotted point: dx, dy convert to Integer."
  },
  {
    "name": "ELSE",
    "kind": "misc",
    "display": [
      "IF expr THEN … ELSE … END IF"
    ],
    "summary": "Starts the branch an IF runs when no condition holds."
  },
  {
    "name": "ELSEIF",
    "kind": "misc",
    "display": [
      "ELSEIF expr [THEN]"
    ],
    "summary": "Starts another tested branch of a block IF."
  },
  {
    "name": "END",
    "kind": "statement",
    "display": [
      "END [ expr ]"
    ],
    "summary": "Ends the program and returns to the caller (BASIC or the OS) with the optional value (default 0)."
  },
  {
    "name": "ENDIF",
    "kind": "misc",
    "display": [
      "ENDIF"
    ],
    "summary": "Closes an IF block; the same as END IF."
  },
  {
    "name": "ERROR",
    "kind": "statement",
    "display": [
      "ERROR expr"
    ],
    "summary": "Raises the ROM error report with the given number (operand converts to UByte)."
  },
  {
    "name": "EXIT",
    "kind": "statement",
    "display": [
      "EXIT ( DO | FOR | WHILE )"
    ],
    "summary": "Leaves the innermost enclosing loop of the named kind."
  },
  {
    "name": "EXP",
    "kind": "function",
    "display": [
      "EXP(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "FASTCALL",
    "kind": "modifier",
    "display": [
      "SUB FASTCALL name(...)",
      "FUNCTION FASTCALL name(...) AS type"
    ],
    "summary": "Calling convention: the first argument comes in registers (A, HL or DE:HL) and the routine has no stack frame."
  },
  {
    "name": "FIXED",
    "kind": "type",
    "display": [
      "FIXED"
    ],
    "summary": "4 bytes, signed: 16.16 fixed point, about -32767.99998..32767.99998, resolution 1/65536."
  },
  {
    "name": "FLASH",
    "kind": "statement",
    "display": [
      "FLASH expr"
    ],
    "summary": "Permanent attribute statement."
  },
  {
    "name": "FLOAT",
    "kind": "type",
    "display": [
      "FLOAT"
    ],
    "summary": "5 bytes, signed: Sinclair ROM 40-bit float: 1 exponent byte (excess 128) + 4 mantissa bytes."
  },
  {
    "name": "FOR",
    "kind": "statement",
    "display": [
      "FOR name = expr TO expr [STEP expr] … NEXT [name]"
    ],
    "summary": "Counted loop."
  },
  {
    "name": "FUNCTION",
    "kind": "declaration",
    "display": [
      "FUNCTION [FASTCALL | STDCALL] name[(params)] [AS type] … END FUNCTION"
    ],
    "summary": "Defines a value-returning routine."
  },
  {
    "name": "GO",
    "kind": "statement",
    "display": [
      "GO TO target",
      "GO SUB target"
    ],
    "summary": "Two-word spellings of GOTO and GOSUB."
  },
  {
    "name": "GOSUB",
    "kind": "statement",
    "display": [
      "GOSUB target"
    ],
    "summary": "Calls the code at a label or line number."
  },
  {
    "name": "GOTO",
    "kind": "statement",
    "display": [
      "GOTO target"
    ],
    "summary": "Jumps to a label or line number."
  },
  {
    "name": "IF",
    "kind": "statement",
    "display": [
      "IF expr [THEN] statements [ELSE statements]",
      "IF expr [THEN] … [ELSEIF expr [THEN] …] [ELSE …] END IF"
    ],
    "summary": "THEN is optional."
  },
  {
    "name": "IN",
    "kind": "function",
    "display": [
      "IN expr",
      "IN(expr)"
    ],
    "summary": "Argument: port converted to UInteger. Result: UByte read from the port.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "INK",
    "kind": "statement",
    "display": [
      "INK expr"
    ],
    "summary": "Permanent attribute statement."
  },
  {
    "name": "INKEY",
    "kind": "function",
    "display": [
      "INKEY",
      "INKEY$"
    ],
    "summary": "Result: String: the key currently pressed, or the empty string."
  },
  {
    "name": "INKEY$",
    "kind": "function",
    "display": [
      "INKEY",
      "INKEY$"
    ],
    "summary": "Result: String: the key currently pressed, or the empty string."
  },
  {
    "name": "INT",
    "kind": "function",
    "display": [
      "INT(expr)"
    ],
    "summary": "Argument: numeric. Result: Long, truncated toward minus infinity.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "INTEGER",
    "kind": "type",
    "display": [
      "INTEGER"
    ],
    "summary": "2 bytes, signed: -32768..32767. Sigil %."
  },
  {
    "name": "INVERSE",
    "kind": "statement",
    "display": [
      "INVERSE expr"
    ],
    "summary": "Permanent attribute statement."
  },
  {
    "name": "ITALIC",
    "kind": "statement",
    "display": [
      "ITALIC expr"
    ],
    "summary": "Permanent attribute statement (ZX BASIC extension): slanted glyphs when non-zero."
  },
  {
    "name": "LBOUND",
    "kind": "function",
    "display": [
      "LBOUND(array-identifier [, expr ])"
    ],
    "summary": "Argument: array and a 1-based dimension number. Result: UInteger lower bound; dimension omitted or 0 gives the number of dimensions; constant-folded for declared arrays.",
    "params": [
      "array-identifier",
      "[expr]"
    ]
  },
  {
    "name": "LEN",
    "kind": "function",
    "display": [
      "LEN(string-expr)"
    ],
    "summary": "Argument: String. Result: UInteger length; constant-folded for literals. LEN of an array gives its number of dimensions (edge case)..",
    "params": [
      "string-expr"
    ]
  },
  {
    "name": "LET",
    "kind": "statement",
    "display": [
      "[ LET ] identifier = expr",
      "[ LET ] identifier (args) = expr",
      "[ LET ] array-identifier = array-identifier",
      "[ LET ] str-designator ([ expr ] TO [ expr ]) = string-expr",
      "[ LET ] str-designator (expr) = string-expr",
      "[ LET ] string-array (args) ([ expr ] TO [ expr ]) = string-expr",
      "[ LET ] string-array (args, expr) = string-expr"
    ],
    "summary": "LET is optional everywhere."
  },
  {
    "name": "LN",
    "kind": "function",
    "display": [
      "LN(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "LOAD",
    "kind": "statement",
    "display": [
      "LOAD string-expr ( CODE [ expr [, expr ] ] | SCREEN$ | SCREEN | DATA [ identifier [ () ] ] )"
    ],
    "summary": "Loads from tape: CODE with optional address and length."
  },
  {
    "name": "LONG",
    "kind": "type",
    "display": [
      "LONG"
    ],
    "summary": "4 bytes, signed: -2^31..2^31-1."
  },
  {
    "name": "LOOP",
    "kind": "misc",
    "display": [
      "LOOP [UNTIL expr | WHILE expr]"
    ],
    "summary": "Closes a DO loop, optionally testing a condition at the bottom."
  },
  {
    "name": "MOD",
    "kind": "operator",
    "display": [
      "MOD"
    ],
    "summary": "Operands: numeric. Result: common type; remainder."
  },
  {
    "name": "NEXT",
    "kind": "misc",
    "display": [
      "NEXT [name]"
    ],
    "summary": "Closes a FOR loop; it may name the loop variable, which must then match."
  },
  {
    "name": "NOT",
    "kind": "operator",
    "display": [
      "NOT"
    ],
    "summary": "Operands: numeric (unary). Result: boolean 0/1."
  },
  {
    "name": "ON",
    "kind": "statement",
    "display": [
      "ON expr ( GOTO | GO TO | GOSUB | GO SUB ) target {, target }"
    ],
    "summary": "Computed jump through a jump table: the expression converts to UByte."
  },
  {
    "name": "OR",
    "kind": "operator",
    "display": [
      "OR"
    ],
    "summary": "Operands: numeric (0 is false, non-zero true). Result: boolean 0/1."
  },
  {
    "name": "OUT",
    "kind": "statement",
    "display": [
      "OUT expr, expr"
    ],
    "summary": "Writes a byte to an I/O port: port converts to UInteger, value to UByte."
  },
  {
    "name": "OVER",
    "kind": "statement",
    "display": [
      "OVER expr"
    ],
    "summary": "Permanent attribute statement."
  },
  {
    "name": "PAPER",
    "kind": "statement",
    "display": [
      "PAPER expr"
    ],
    "summary": "Permanent attribute statement."
  },
  {
    "name": "PAUSE",
    "kind": "statement",
    "display": [
      "PAUSE expr"
    ],
    "summary": "Waits the given number of frames (operand converts to UInteger)."
  },
  {
    "name": "PEEK",
    "kind": "function",
    "display": [
      "PEEK expr",
      "PEEK(expr)",
      "PEEK(type, expr)"
    ],
    "summary": "Argument: address converted to UInteger. Result: UByte, or the named type when one is given.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "PI",
    "kind": "function",
    "display": [
      "PI"
    ],
    "summary": "Result: Float constant."
  },
  {
    "name": "PLOT",
    "kind": "statement",
    "display": [
      "PLOT [ attr-list ] expr, expr"
    ],
    "summary": "Plots a pixel at x, y (both convert to UByte)."
  },
  {
    "name": "POKE",
    "kind": "statement",
    "display": [
      "POKE expr, expr",
      "POKE(expr, expr)",
      "POKE type expr, expr",
      "POKE(type expr, expr)",
      "POKE type, expr, expr",
      "POKE(type, expr, expr)"
    ],
    "summary": "Writes to memory."
  },
  {
    "name": "PRINT",
    "kind": "statement",
    "display": [
      "PRINT [ print-item { print-sep print-item } ] [ print-sep ]"
    ],
    "summary": "';' juxtaposes, ',' advances to the next 16-column field, a trailing separator suppresses the newline, a bare PRINT outputs a newline."
  },
  {
    "name": "RANDOMIZE",
    "kind": "statement",
    "display": [
      "RANDOMIZE [ expr ]"
    ],
    "summary": "Seeds the random generator with the operand (converted to ULong)."
  },
  {
    "name": "READ",
    "kind": "statement",
    "display": [
      "READ designator {, designator }"
    ],
    "summary": "Reads the next DATA items into scalars or array elements (a whole array is an error)."
  },
  {
    "name": "REM",
    "kind": "misc",
    "display": [
      "REM text"
    ],
    "summary": "A comment to the end of the line; ' is the short form."
  },
  {
    "name": "RESTORE",
    "kind": "statement",
    "display": [
      "RESTORE [ target ]"
    ],
    "summary": "Makes the next READ start at the first DATA item, or at the DATA line following the given label or line number."
  },
  {
    "name": "RETURN",
    "kind": "statement",
    "display": [
      "RETURN [ expr ]"
    ],
    "summary": "At global scope returns from GOSUB."
  },
  {
    "name": "RND",
    "kind": "function",
    "display": [
      "RND",
      "RND()"
    ],
    "summary": "Result: Float in [0, 1); 2^32 period."
  },
  {
    "name": "SAVE",
    "kind": "statement",
    "display": [
      "SAVE string-expr ( CODE expr, expr | SCREEN$ | SCREEN | DATA [ identifier [ () ] ] )"
    ],
    "summary": "Saves to tape: CODE address, length."
  },
  {
    "name": "SGN",
    "kind": "function",
    "display": [
      "SGN(expr)"
    ],
    "summary": "Argument: numeric. Result: Byte: -1, 0 or 1; warns on an unsigned argument.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "SHL",
    "kind": "operator",
    "display": [
      "SHL"
    ],
    "summary": "Operands: integral left (Fixed/Float left converts to ULong); right converted to UByte. Result: type of the left operand."
  },
  {
    "name": "SHR",
    "kind": "operator",
    "display": [
      "SHR"
    ],
    "summary": "Operands: as SHL. Result: type of the left operand."
  },
  {
    "name": "SIN",
    "kind": "function",
    "display": [
      "SIN(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "SIZEOF",
    "kind": "function",
    "display": [
      "SIZEOF(type)",
      "SIZEOF(name)"
    ],
    "summary": "Argument: type name or variable. Result: compile-time constant size in bytes.",
    "params": [
      "type or name"
    ]
  },
  {
    "name": "SQR",
    "kind": "function",
    "display": [
      "SQR(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "STDCALL",
    "kind": "modifier",
    "display": [
      "SUB STDCALL name(...)",
      "FUNCTION STDCALL name(...) AS type"
    ],
    "summary": "Calling convention (the default): arguments on the stack and a stack frame for locals."
  },
  {
    "name": "STEP",
    "kind": "modifier",
    "display": [
      "FOR name = expr TO expr STEP expr"
    ],
    "summary": "The amount a FOR loop's variable changes by on each NEXT (1 when omitted)."
  },
  {
    "name": "STOP",
    "kind": "statement",
    "display": [
      "STOP [ expr ]"
    ],
    "summary": "Raises a ROM report."
  },
  {
    "name": "STR",
    "kind": "function",
    "display": [
      "STR(expr)"
    ],
    "summary": "Argument: converted to Float. Result: String.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "STR$",
    "kind": "function",
    "display": [
      "STR$(expr)"
    ],
    "summary": "Argument: converted to Float. Result: String.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "STRING",
    "kind": "type",
    "display": [
      "STRING"
    ],
    "summary": "2 bytes, unsigned: pointer to a heap block: 2-byte length followed by the characters; max 65535 characters; null pointer means the empty string. Sigil $."
  },
  {
    "name": "SUB",
    "kind": "declaration",
    "display": [
      "SUB [FASTCALL | STDCALL] name[(params)] … END SUB"
    ],
    "summary": "Defines a routine without a return value."
  },
  {
    "name": "TAB",
    "kind": "modifier",
    "display": [
      "PRINT TAB column; …"
    ],
    "summary": "In PRINT, moves to a column (taken modulo 32)."
  },
  {
    "name": "TAN",
    "kind": "function",
    "display": [
      "TAN(expr)"
    ],
    "summary": "Argument: converted to Float. Result: Float.",
    "params": [
      "expr"
    ]
  },
  {
    "name": "THEN",
    "kind": "modifier",
    "display": [
      "IF expr THEN"
    ],
    "summary": "Ends an IF or ELSEIF condition; it is optional."
  },
  {
    "name": "TO",
    "kind": "modifier",
    "display": [
      "FOR name = expr TO expr",
      "DIM a(lower TO upper)",
      "s$(from TO to)"
    ],
    "summary": "Separates the limits of a FOR loop, an array bound or a string slice."
  },
  {
    "name": "UBOUND",
    "kind": "function",
    "display": [
      "UBOUND(array-identifier [, expr ])"
    ],
    "summary": "Argument: array and a 1-based dimension number. Result: UInteger upper bound; dimension omitted or 0 gives the number of dimensions; constant-folded for declared arrays.",
    "params": [
      "array-identifier",
      "[expr]"
    ]
  },
  {
    "name": "UBYTE",
    "kind": "type",
    "display": [
      "UBYTE"
    ],
    "summary": "1 byte, unsigned: 0..255."
  },
  {
    "name": "UINTEGER",
    "kind": "type",
    "display": [
      "UINTEGER"
    ],
    "summary": "2 bytes, unsigned: 0..65535."
  },
  {
    "name": "ULONG",
    "kind": "type",
    "display": [
      "ULONG"
    ],
    "summary": "4 bytes, unsigned: 0..2^32-1."
  },
  {
    "name": "UNTIL",
    "kind": "misc",
    "display": [
      "DO UNTIL expr",
      "LOOP UNTIL expr"
    ],
    "summary": "A DO loop's exit test: the loop ends when the condition holds."
  },
  {
    "name": "USR",
    "kind": "function",
    "display": [
      "USR expr",
      "USR string-expr"
    ],
    "summary": "Argument: address converted to UInteger, or a string. Result: UInteger: calls machine code at the address and returns BC; for a string, the UDG address of its first character (case-insensitive)."
  },
  {
    "name": "VAL",
    "kind": "function",
    "display": [
      "VAL(string-expr)"
    ],
    "summary": "Argument: String. Result: Float; constant strings fold at compile time (invalid gives 0 with a warning); at run time an invalid string sets the ROM error variable.",
    "params": [
      "string-expr"
    ]
  },
  {
    "name": "VERIFY",
    "kind": "statement",
    "display": [
      "VERIFY string-expr ( CODE [ expr [, expr ] ] | SCREEN$ | SCREEN | DATA [ identifier [ () ] ] )"
    ],
    "summary": "Same forms as LOAD."
  },
  {
    "name": "WEND",
    "kind": "misc",
    "display": [
      "WEND"
    ],
    "summary": "Closes a WHILE loop; the same as END WHILE."
  },
  {
    "name": "WHILE",
    "kind": "statement",
    "display": [
      "WHILE expr … WEND",
      "WHILE expr … END WHILE"
    ],
    "summary": "Top-tested loop."
  },
  {
    "name": "XOR",
    "kind": "operator",
    "display": [
      "XOR"
    ],
    "summary": "Operands: numeric (0 is false, non-zero true). Result: boolean 0/1."
  },
  {
    "name": "CODEBANK",
    "kind": "declaration",
    "display": [
      "CODEBANK bank … END CODEBANK"
    ],
    "summary": "Places the routines and data in the block in a memory bank (a Klive BASIC extension); bank 0 is resident."
  },
  {
    "name": "FARPTR",
    "kind": "operator",
    "display": [
      "FARPTR name"
    ],
    "summary": "A banked address as a ULong: the bank in bits 16-23, the address in bits 0-15."
  }
];

/** The preprocessor directives. */
export const DIRECTIVE_HELP: readonly BasicHelpEntry[] = [
  {
    "name": "#define",
    "kind": "directive",
    "display": [
      "#define NAME",
      "#define NAME body",
      "#define NAME(param, …) body"
    ],
    "summary": "Object-like or function-like macro."
  },
  {
    "name": "#else",
    "kind": "directive",
    "display": [
      "#else"
    ],
    "summary": "Alternative branch of #if, #ifdef or #ifndef."
  },
  {
    "name": "#endif",
    "kind": "directive",
    "display": [
      "#endif"
    ],
    "summary": "Closes a conditional block."
  },
  {
    "name": "#error",
    "kind": "directive",
    "display": [
      "#error text"
    ],
    "summary": "Emits a compile error with the text."
  },
  {
    "name": "#if",
    "kind": "directive",
    "display": [
      "#if pp-expr"
    ],
    "summary": "Conditional compilation."
  },
  {
    "name": "#ifdef",
    "kind": "directive",
    "display": [
      "#ifdef NAME"
    ],
    "summary": "True when NAME is defined."
  },
  {
    "name": "#ifndef",
    "kind": "directive",
    "display": [
      "#ifndef NAME"
    ],
    "summary": "True when NAME is not defined."
  },
  {
    "name": "#include",
    "kind": "directive",
    "display": [
      "#include <file>",
      "#include \"file\"",
      "#include MACRO",
      "#include once [ [ arch : arch ] ] ( <file> | \"file\" )"
    ],
    "summary": "<file> searches the include path: the architecture's stdlib/, runtime/, then -I directories (zx81sd falls back to zx48k)."
  },
  {
    "name": "#init",
    "kind": "directive",
    "display": [
      "#init name",
      "#init \"name\""
    ],
    "summary": "Registers an assembler routine (dotted names allowed) to be called in the program prologue."
  },
  {
    "name": "#line",
    "kind": "directive",
    "display": [
      "#line N [ \"file\" ]"
    ],
    "summary": "Resets line and file bookkeeping for diagnostics."
  },
  {
    "name": "#pragma",
    "kind": "directive",
    "display": [
      "#pragma option = value",
      "#pragma option value",
      "#pragma push(option)",
      "#pragma pop(option)",
      "#pragma once"
    ],
    "summary": "Sets, saves or restores a compiler option (see pragmas)."
  },
  {
    "name": "#require",
    "kind": "directive",
    "display": [
      "#require \"file.asm\""
    ],
    "summary": "Requests a runtime assembler module to be appended to the output (an include-once of that file)."
  },
  {
    "name": "#undef",
    "kind": "directive",
    "display": [
      "#undef NAME"
    ],
    "summary": "Removes a macro definition."
  },
  {
    "name": "#warning",
    "kind": "directive",
    "display": [
      "#warning text"
    ],
    "summary": "Emits a compile warning with the text."
  }
];

/** The `#pragma` options. */
export const PRAGMA_HELP: readonly BasicPragmaHelp[] = [
  {
    "name": "array_base",
    "type": "int",
    "default": "0",
    "effect": "default lower array bound"
  },
  {
    "name": "array_check",
    "type": "bool",
    "default": "false",
    "effect": "subscript range checks (same as --debug-array)"
  },
  {
    "name": "autorun",
    "type": "bool",
    "default": "false",
    "effect": "auto-start entry in the output"
  },
  {
    "name": "case_insensitive",
    "type": "bool",
    "default": "false",
    "effect": "identifiers become case-insensitive"
  },
  {
    "name": "default_byref",
    "type": "bool",
    "default": "false",
    "effect": "scalar parameters default to BYREF"
  },
  {
    "name": "enable_break",
    "type": "bool",
    "default": "false",
    "effect": "BREAK key checks per line"
  },
  {
    "name": "expected_warnings",
    "type": "int",
    "default": "0",
    "effect": "as --expect-warnings"
  },
  {
    "name": "explicit",
    "type": "bool",
    "default": "false",
    "effect": "variables must be declared before use"
  },
  {
    "name": "force_asm_brackets",
    "type": "bool",
    "default": "false",
    "effect": "as the CLI flag of the same name (assembler bracket style)"
  },
  {
    "name": "headerless",
    "type": "bool",
    "default": "false",
    "effect": "omit prologue and epilogue"
  },
  {
    "name": "heap_address",
    "type": "int",
    "default": "",
    "effect": "fixed heap address instead of after the program"
  },
  {
    "name": "heap_size",
    "type": "int",
    "default": "4768",
    "effect": "heap size in bytes"
  },
  {
    "name": "hide_warning_codes",
    "type": "bool",
    "default": "false",
    "effect": "omit [Wnnn] prefixes"
  },
  {
    "name": "include_path",
    "type": "string",
    "default": "",
    "effect": "extra include directories"
  },
  {
    "name": "memory_check",
    "type": "bool",
    "default": "false",
    "effect": "out-of-memory detection (same as --debug-memory)"
  },
  {
    "name": "memory_map",
    "type": "string",
    "default": "",
    "effect": "label map output file (as --mmap)"
  },
  {
    "name": "once",
    "type": "flag",
    "default": "",
    "effect": "marks the current file as include-once"
  },
  {
    "name": "opt_strategy",
    "type": "size | speed | auto",
    "default": "auto",
    "effect": "optimiser strategy"
  },
  {
    "name": "optimization_level",
    "type": "int",
    "default": "2",
    "effect": "optimisation level"
  },
  {
    "name": "org",
    "type": "int",
    "default": "32768",
    "effect": "code origin"
  },
  {
    "name": "sinclair",
    "type": "bool",
    "default": "false",
    "effect": "Sinclair compatibility mode (as --sinclair)"
  },
  {
    "name": "strict",
    "type": "bool",
    "default": "false",
    "effect": "explicit types required"
  },
  {
    "name": "strict_bool",
    "type": "bool",
    "default": "false",
    "effect": "deprecated and ignored since 1.18.0"
  },
  {
    "name": "string_base",
    "type": "int",
    "default": "0",
    "effect": "index of the first character of a string"
  },
  {
    "name": "zxnext",
    "type": "bool",
    "default": "false",
    "effect": "ZX Next opcodes allowed in ASM blocks"
  }
];

/** The documented libraries; `available` ones are in Klive BASIC's standard library. */
export const LIBRARY_HELP: readonly BasicLibraryHelp[] = [
  {
    "name": "asc.bas",
    "include": "#include <asc.bas>",
    "provides": [
      "asc"
    ],
    "summary": "ASCII code of the n-th character of a string; FreeBASIC compatible; 0 beyond end.",
    "available": true
  },
  {
    "name": "attr.bas",
    "include": "#include <attr.bas>",
    "provides": [
      "ATTR"
    ],
    "summary": "Attribute byte at (row, col); rows 22/23 allowed; auto with --sinclair.",
    "available": true
  },
  {
    "name": "attrAddress.bas",
    "include": "#include <attrAddress.bas>",
    "provides": [
      "attrAddress"
    ],
    "summary": "Attribute memory address for a character position (copy listing).",
    "available": false
  },
  {
    "name": "clearBox.bas",
    "include": "#include <clearBox.bas>",
    "provides": [
      "clearBox"
    ],
    "summary": "Blank the pixels of a character-square rectangle (copy listing).",
    "available": true
  },
  {
    "name": "csrlin.bas",
    "include": "#include <csrlin.bas>",
    "provides": [
      "CSRLIN"
    ],
    "summary": "Row of the text cursor.",
    "available": true
  },
  {
    "name": "distance.bas",
    "include": "#include <distance.bas>",
    "provides": [
      "distance"
    ],
    "summary": "Fast approximate SQR(x^2+y^2) for bytes (copy listing).",
    "available": false
  },
  {
    "name": "doubleSizePrint.bas",
    "include": "#include <doubleSizePrint.bas>",
    "provides": [
      "doubleSizePrintChar",
      "doubleSizePrint"
    ],
    "summary": "Double-size character/string printing (copy listing).",
    "available": false
  },
  {
    "name": "fastPlot.bas",
    "include": "#include <fastPlot.bas>",
    "provides": [
      "fastPlot"
    ],
    "summary": "Fast OVER 0 pixel plot without attributes; optional screen-tables variant (copy listing).",
    "available": false
  },
  {
    "name": "fsin.bas / fmath.bas",
    "include": "#include <fmath.bas>",
    "provides": [
      "fSin",
      "fCos",
      "fTan"
    ],
    "summary": "Fast Fixed-point trig in degrees, ~0.25% accuracy; page says bundled as fmath.bas.",
    "available": false
  },
  {
    "name": "fSqrt.bas",
    "include": "#include <fSqrt.bas>",
    "provides": [
      "fSqrt"
    ],
    "summary": "Newton-Raphson Float square root, ~6x faster than ROM SQR, same accuracy.",
    "available": false
  },
  {
    "name": "hex.bas",
    "include": "#include <hex.bas>",
    "provides": [
      "hex",
      "hex16",
      "hex8"
    ],
    "summary": "Hexadecimal string conversion for 32/16/8-bit unsigned values.",
    "available": true
  },
  {
    "name": "hMirror.bas",
    "include": "#include <hMirror.bas>",
    "provides": [
      "hMirror"
    ],
    "summary": "Reverse bit order of a byte (copy listing; use the second, faster version).",
    "available": true
  },
  {
    "name": "HRPrint.bas",
    "include": "#include \"hrprint.bas\" (local copy)",
    "provides": [
      "HRPrint"
    ],
    "summary": "Print a character at any pixel position with attributes and OVER modes.",
    "available": false
  },
  {
    "name": "HRPrintFast.bas",
    "include": "#include <HRPrintFast.bas>",
    "provides": [
      "HRPrintFast"
    ],
    "summary": "Table-driven HRPrint, ~20% faster; needs Screentables.asm/RotateTables.asm from forum.",
    "available": false
  },
  {
    "name": "input42.bas",
    "include": "#include <input42.bas>",
    "provides": [
      "INPUT42"
    ],
    "summary": "Line input echoed through print42; always returns a string.",
    "available": true
  },
  {
    "name": "iSqrt.bas",
    "include": "#include <iSqrt.bas>",
    "provides": [
      "iSqrt"
    ],
    "summary": "Integer square root of a uLong, 50-100x faster than ROM (copy listing).",
    "available": false
  },
  {
    "name": "keys.bas",
    "include": "#include <keys.bas>",
    "provides": [
      "GetKey",
      "GetKeyScanCode",
      "MultiKeys",
      "KEY* scan code constants"
    ],
    "summary": "Standard library: fast keyboard scanning without the ROM; scan-code constants per row half.",
    "available": true
  },
  {
    "name": "keys.bas (GetKey)",
    "include": "#include <keys.bas>",
    "provides": [
      "GetKey"
    ],
    "summary": "Wait for a key and return its ASCII code (UByte).",
    "available": false
  },
  {
    "name": "keys.bas (GetKeyScanCode)",
    "include": "#include <keys.bas>",
    "provides": [
      "GetKeyScanCode"
    ],
    "summary": "Scan code of pressed key(s) ORed, 0 if none; no wait.",
    "available": false
  },
  {
    "name": "keys.bas (MultiKeys)",
    "include": "#include <keys.bas>",
    "provides": [
      "MultiKeys"
    ],
    "summary": "Test several keys at once (same row half).",
    "available": false
  },
  {
    "name": "megalz.bas",
    "include": "#include <megalz.bas>",
    "provides": [
      "megaLZDepack"
    ],
    "summary": "MegaLZ v4 decompressor wrapper (110-byte relocatable depacker).",
    "available": true
  },
  {
    "name": "memorybank.bas",
    "include": "#include <memorybank.bas>",
    "provides": [
      "SetBank",
      "GetBank",
      "SetCodeBank"
    ],
    "summary": "Paged RAM management at $c000 (and copy-to-$8000) for 128K models.",
    "available": true
  },
  {
    "name": "memorybank.bas (GetBank)",
    "include": "#include <memorybank.bas>",
    "provides": [
      "GetBank"
    ],
    "summary": "Bank currently at $c000 (from BANKM).",
    "available": false
  },
  {
    "name": "memorybank.bas (SetBank)",
    "include": "#include <memorybank.bas>",
    "provides": [
      "SetBank"
    ],
    "summary": "Page a bank into $c000-$ffff and update BANKM.",
    "available": false
  },
  {
    "name": "memorybank.bas (SetCodeBank)",
    "include": "#include <memorybank.bas>",
    "provides": [
      "SetCodeBank"
    ],
    "summary": "Copy a bank to $8000 (per memorybank.md); destroys bank 2; book chapter 14 architecture.",
    "available": false
  },
  {
    "name": "pixelScroll.bas",
    "include": "#include <pixelScroll.bas>",
    "provides": [
      "PixelScrollUp"
    ],
    "summary": "Scroll the pixel screen up N rows (attributes untouched); needs ScreenTables.bas.",
    "available": false
  },
  {
    "name": "point.bas",
    "include": "#include <point.bas>",
    "provides": [
      "POINT"
    ],
    "summary": "Pixel test at (x, y); auto with --sinclair.",
    "available": true
  },
  {
    "name": "pos.bas",
    "include": "#include <pos.bas>",
    "provides": [
      "POS"
    ],
    "summary": "Column of the text cursor.",
    "available": true
  },
  {
    "name": "print42.bas",
    "include": "#include <print42.bas>",
    "provides": [
      "print42",
      "printat42"
    ],
    "summary": "42-column (6 px) fixed-width text printing.",
    "available": true
  },
  {
    "name": "print64.bas",
    "include": "#include <print64.bas>",
    "provides": [
      "print64",
      "printat64"
    ],
    "summary": "64-column (4 px) fixed-width text printing with its own cursor.",
    "available": true
  },
  {
    "name": "Print64x32.bas",
    "include": "#include <Print64x32.bas>",
    "provides": [
      "Print64x32",
      "Print64x32At",
      "Print64x32StringAt"
    ],
    "summary": "64x32 grid text (2048 positions), no attributes; needs ScreenTables.asm from forum.",
    "available": false
  },
  {
    "name": "propPrint.bas",
    "include": "#include <propPrint.bas>",
    "provides": [
      "propPrint"
    ],
    "summary": "Proportional text printing at pixel positions (copy listing).",
    "available": false
  },
  {
    "name": "putchars.bas",
    "include": "#include <putchars.bas>",
    "provides": [
      "putChars",
      "paint",
      "paintData"
    ],
    "summary": "Block graphics and attribute painting at character coordinates; no bounds checks (copy listing).",
    "available": true
  },
  {
    "name": "putTile.bas",
    "include": "#include <putTile.bas>",
    "provides": [
      "putTile"
    ],
    "summary": "PUSH/POP-based 2x2 character tile blit with attributes; disables interrupts (copy listing).",
    "available": true
  },
  {
    "name": "randomStream.bas",
    "include": "#include <randomStream.bas>",
    "provides": [
      "randomBase",
      "updateSeed",
      "time",
      "randomLimit",
      "randomFixed"
    ],
    "summary": "Integer/Fixed random numbers from Patrik Rak's stream generator (copy listing).",
    "available": false
  },
  {
    "name": "scrAddress.bas",
    "include": "#include <scrAddress.bas>",
    "provides": [
      "scrAddress",
      "attrAddress"
    ],
    "summary": "Screen and attribute addresses for a character cell (copy listing).",
    "available": false
  },
  {
    "name": "screen.bas",
    "include": "#include <screen.bas>",
    "provides": [
      "SCREEN$"
    ],
    "summary": "Character at (row, col); auto with --sinclair.",
    "available": true
  },
  {
    "name": "stdlib (index)",
    "include": "#include <stdlib (index)>",
    "provides": [],
    "summary": "Index of bundled standard libraries: keys.bas and string.bas; some libraries may be architecture-specific (none flagged).",
    "available": false
  },
  {
    "name": "string.bas",
    "include": "#include <string.bas>",
    "provides": [
      "left",
      "mid",
      "right"
    ],
    "summary": "Standard library string slicing; strings are 0-based unless --string-base=1.",
    "available": true
  },
  {
    "name": "string.bas (left)",
    "include": "#include <string.bas>",
    "provides": [
      "left"
    ],
    "summary": "First N chars.",
    "available": false
  },
  {
    "name": "string.bas (mid)",
    "include": "#include <string.bas>",
    "provides": [
      "mid"
    ],
    "summary": "N chars from a 0-based start.",
    "available": false
  },
  {
    "name": "string.bas (right)",
    "include": "#include <string.bas>",
    "provides": [
      "right"
    ],
    "summary": "Last N chars.",
    "available": false
  },
  {
    "name": "windowAttrScrollUP.bas",
    "include": "#include <windowAttrScrollUP.bas>",
    "provides": [
      "BLAttrWindowScrollUp"
    ],
    "summary": "Scroll a window's attributes up one row (copy listing).",
    "available": false
  },
  {
    "name": "windowPaint.bas",
    "include": "#include <windowPaint.bas>",
    "provides": [
      "windowPaint",
      "paint"
    ],
    "summary": "Set attributes of a rectangle without touching pixels (copy listing).",
    "available": false
  },
  {
    "name": "windowScrollUP.bas",
    "include": "#include <windowScrollUP.bas>",
    "provides": [
      "BLWindowScrollUp"
    ],
    "summary": "Scroll a window's pixels up one character row (copy listing).",
    "available": false
  },
  {
    "name": "zx0.bas",
    "include": "#include <zx0.bas>",
    "provides": [
      "dzx0Standard",
      "dzx0StandardBack",
      "dzx0Turbo",
      "dzx0TurboBack",
      "dzx0Mega",
      "dzx0MegaBack",
      "dzx0SmartRCS",
      "dzx0SmartRCSBack",
      "dzx0AgileRCS"
    ],
    "summary": "Einar Saukas' ZX0 decompressors (src, dst); free to use, credit requested.",
    "available": true
  },
  {
    "name": "farmem.bas",
    "include": "#include <farmem.bas>",
    "provides": [
      "FarPeek",
      "FarPeekW",
      "FarPoke",
      "FarPokeW",
      "FarCopy",
      "FarCopyTo",
      "FarStr"
    ],
    "summary": "Reads and writes CODEBANK bank-local data through FARPTR values, from anywhere, without changing the current bank.",
    "available": true
  }
];

/** The documented library routines; `available` ones are in Klive BASIC's standard library. */
export const LIBRARY_ROUTINE_HELP: readonly BasicLibraryRoutineHelp[] = [
  {
    "name": "ASC",
    "kind": "function",
    "library": "asc.bas",
    "include": "#include <asc.bas>",
    "syntax": [
      "asc(A$, n)"
    ],
    "returns": "UByte (implied; same as CODE(A$(n)))",
    "params": [
      {
        "name": "A$",
        "type": "String"
      },
      {
        "name": "n",
        "type": "numeric",
        "notes": "character index"
      }
    ],
    "summary": "ASCII code of the n-th character of a string (FreeBASIC compatibility).",
    "available": true
  },
  {
    "name": "ATTR",
    "kind": "function",
    "library": "attr.bas",
    "include": "#include <attr.bas>",
    "syntax": [
      "ATTR(row, col)"
    ],
    "returns": "attribute byte (type not stated)",
    "params": [
      {
        "name": "row",
        "type": "numeric"
      },
      {
        "name": "col",
        "type": "numeric"
      }
    ],
    "summary": "Returns the colour attribute byte of the screen cell at (row, col).",
    "available": true
  },
  {
    "name": "attrAddress",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "attrAddress(x as uByte, y as uByte) as uInteger"
    ],
    "returns": "uInteger",
    "params": [
      {
        "name": "x",
        "type": "uByte",
        "notes": "column"
      },
      {
        "name": "y",
        "type": "uByte",
        "notes": "row"
      }
    ],
    "summary": "Returns the address of the attribute byte for character position (x, y).",
    "available": false
  },
  {
    "name": "BLAttrWindowScrollUp",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "BLAttrWindowScrollUp(X AS UBYTE, Y AS UBYTE, Width AS UBYTE, Height AS UBYTE)"
    ],
    "params": [
      {
        "name": "X",
        "type": "UBYTE",
        "notes": "top-left column"
      },
      {
        "name": "Y",
        "type": "UBYTE",
        "notes": "top-left row"
      },
      {
        "name": "Width",
        "type": "UBYTE",
        "notes": "chars"
      },
      {
        "name": "Height",
        "type": "UBYTE",
        "notes": "chars"
      }
    ],
    "summary": "Scrolls the colour attributes of a character window up by one row.",
    "available": false
  },
  {
    "name": "BLWindowScrollUp",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "BLWindowScrollUp(X as uByte, Y as uByte, Width as uByte, Height as uByte)"
    ],
    "params": [
      {
        "name": "X",
        "type": "uByte"
      },
      {
        "name": "Y",
        "type": "uByte"
      },
      {
        "name": "Width",
        "type": "uByte"
      },
      {
        "name": "Height",
        "type": "uByte"
      }
    ],
    "summary": "Scrolls a rectangular character window of the pixel screen up by one character row and blanks the last row.",
    "available": false
  },
  {
    "name": "clearBox",
    "kind": "sub",
    "library": "clearbox.bas",
    "include": "#include <clearbox.bas>",
    "syntax": [
      "clearBox(x as uByte, y as uByte, width as uByte, height as uByte)"
    ],
    "params": [
      {
        "name": "x",
        "type": "uByte",
        "notes": "0<x<32"
      },
      {
        "name": "y",
        "type": "uByte",
        "notes": "0<y<23"
      },
      {
        "name": "width",
        "type": "uByte",
        "notes": "x+width<32"
      },
      {
        "name": "height",
        "type": "uByte",
        "notes": "y+height<23"
      }
    ],
    "summary": "Blanks the pixels of a rectangle measured in character squares.",
    "available": true
  },
  {
    "name": "CSRLIN",
    "kind": "function",
    "library": "csrlin.bas",
    "include": "#include <csrlin.bas>",
    "syntax": [
      "CSRLIN()"
    ],
    "returns": "row number (type not stated)",
    "params": [],
    "summary": "Row (line) of the text cursor, 0 = top.",
    "available": true
  },
  {
    "name": "distance",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "FUNCTION fastcall distance(a as ubyte, b as ubyte) as uInteger"
    ],
    "returns": "uInteger",
    "params": [
      {
        "name": "a",
        "type": "ubyte"
      },
      {
        "name": "b",
        "type": "ubyte"
      }
    ],
    "summary": "Very fast integer approximation of SQR(a^2 + b^2).",
    "available": false
  },
  {
    "name": "doubleSizePrint",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "doubleSizePrint(y as uByte, x as uByte, thingToPrint$ as String)"
    ],
    "params": [
      {
        "name": "y",
        "type": "uByte"
      },
      {
        "name": "x",
        "type": "uByte"
      },
      {
        "name": "thingToPrint$",
        "type": "String"
      }
    ],
    "summary": "Prints a string in double-size characters starting at (y, x).",
    "available": false
  },
  {
    "name": "doubleSizePrintChar",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "doubleSizePrintChar(y as uByte, x as uByte, thingToPrint as uByte)"
    ],
    "params": [
      {
        "name": "y",
        "type": "uByte",
        "notes": "<22"
      },
      {
        "name": "x",
        "type": "uByte",
        "notes": "<30"
      },
      {
        "name": "thingToPrint",
        "type": "uByte",
        "notes": "code 32..164"
      }
    ],
    "summary": "Prints one character (ASCII code, incl. UDGs 144-164) at double size.",
    "available": false
  },
  {
    "name": "dzx0AgileRCS",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0AgileRCS(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address",
        "notes": "compressed data"
      },
      {
        "name": "dst",
        "type": "address",
        "notes": "destination"
      }
    ],
    "summary": "ZX0 decompressor variant (agile, RCS screen layout).",
    "available": true
  },
  {
    "name": "dzx0Mega",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0Mega(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address"
      },
      {
        "name": "dst",
        "type": "address"
      }
    ],
    "summary": "ZX0 decompressor, mega (fastest/largest) variant.",
    "available": true
  },
  {
    "name": "dzx0MegaBack",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0MegaBack(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address"
      },
      {
        "name": "dst",
        "type": "address"
      }
    ],
    "summary": "Backwards variant of dzx0Mega.",
    "available": true
  },
  {
    "name": "dzx0SmartRCS",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0SmartRCS(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address"
      },
      {
        "name": "dst",
        "type": "address"
      }
    ],
    "summary": "ZX0 decompressor for RCS-encoded screens (smart variant).",
    "available": true
  },
  {
    "name": "dzx0SmartRCSBack",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0SmartRCSBack(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address"
      },
      {
        "name": "dst",
        "type": "address"
      }
    ],
    "summary": "Backwards variant of dzx0SmartRCS.",
    "available": true
  },
  {
    "name": "dzx0Standard",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0Standard(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address"
      },
      {
        "name": "dst",
        "type": "address"
      }
    ],
    "summary": "ZX0 decompressor, standard (smallest) variant.",
    "available": true
  },
  {
    "name": "dzx0StandardBack",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0StandardBack(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address"
      },
      {
        "name": "dst",
        "type": "address"
      }
    ],
    "summary": "Backwards variant of dzx0Standard.",
    "available": true
  },
  {
    "name": "dzx0Turbo",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0Turbo(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address"
      },
      {
        "name": "dst",
        "type": "address"
      }
    ],
    "summary": "ZX0 decompressor, turbo variant.",
    "available": true
  },
  {
    "name": "dzx0TurboBack",
    "kind": "sub",
    "library": "zx0.bas",
    "include": "#include <zx0.bas>",
    "syntax": [
      "dzx0TurboBack(src, dst)"
    ],
    "params": [
      {
        "name": "src",
        "type": "address"
      },
      {
        "name": "dst",
        "type": "address"
      }
    ],
    "summary": "Backwards variant of dzx0Turbo.",
    "available": true
  },
  {
    "name": "fastPlot",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "fastPlot(x as uByte, y as uByte)"
    ],
    "params": [
      {
        "name": "x",
        "type": "uByte"
      },
      {
        "name": "y",
        "type": "uByte",
        "notes": "y>191 ignored"
      }
    ],
    "summary": "Plots one pixel in OVER 0 mode at high speed, ignoring attributes.",
    "available": false
  },
  {
    "name": "fCos",
    "kind": "function",
    "library": "fmath.bas",
    "include": "#include <fmath.bas>",
    "syntax": [
      "fCos(num as FIXED) as FIXED"
    ],
    "returns": "FIXED",
    "params": [
      {
        "name": "num",
        "type": "FIXED",
        "notes": "degrees"
      }
    ],
    "summary": "Fast Fixed-point cosine in DEGREES, implemented as fSin(90 - num).",
    "available": true
  },
  {
    "name": "fSin",
    "kind": "function",
    "library": "fmath.bas",
    "include": "#include <fmath.bas>",
    "syntax": [
      "fSin(num as FIXED) as FIXED"
    ],
    "returns": "FIXED",
    "params": [
      {
        "name": "num",
        "type": "FIXED",
        "notes": "degrees; any range (reduced with MOD 360)"
      }
    ],
    "summary": "Fast Fixed-point sine in DEGREES using a 46-entry lookup table with interpolation.",
    "available": true
  },
  {
    "name": "fSqrt",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "FUNCTION FASTCALL fSqrt(radicand as FLOAT) as FLOAT"
    ],
    "returns": "FLOAT",
    "params": [
      {
        "name": "radicand",
        "type": "FLOAT",
        "notes": "sign bit cleared, so negatives are treated as positive"
      }
    ],
    "summary": "Float square root by Newton-Raphson, same result as ROM SQR but about 6x faster.",
    "available": false
  },
  {
    "name": "fTan",
    "kind": "function",
    "library": "fmath.bas",
    "include": "#include <fmath.bas>",
    "syntax": [
      "fTan(num as FIXED) as FIXED"
    ],
    "returns": "FIXED",
    "params": [
      {
        "name": "num",
        "type": "FIXED",
        "notes": "degrees"
      }
    ],
    "summary": "Fast Fixed-point tangent in DEGREES: fSin(num) / fSin(90 - num).",
    "available": true
  },
  {
    "name": "GetBank",
    "kind": "function",
    "library": "memorybank.bas",
    "include": "#include <memorybank.bas>",
    "syntax": [
      "GetBank()"
    ],
    "returns": "bank number 0-7 (type not stated)",
    "params": [],
    "summary": "Returns the RAM bank currently paged at $c000, read from system variable BANKM.",
    "available": true
  },
  {
    "name": "GetKey",
    "kind": "function",
    "library": "keys.bas",
    "include": "#include <keys.bas>",
    "syntax": [
      "GetKey()"
    ],
    "returns": "UByte",
    "params": [],
    "summary": "Waits for a key press and returns its ASCII code.",
    "available": true
  },
  {
    "name": "GetKeyScanCode",
    "kind": "function",
    "library": "keys.bas",
    "include": "#include <keys.bas>",
    "syntax": [
      "GetKeyScanCode()"
    ],
    "returns": "UInteger scan code (0 if none)",
    "params": [],
    "summary": "Returns the scan code(s) of the currently pressed key(s) bitwise-ORed, or 0; does not wait.",
    "available": true
  },
  {
    "name": "HEX",
    "kind": "function",
    "library": "hex.bas",
    "include": "#include <hex.bas>",
    "syntax": [
      "A$ = hex(n32)"
    ],
    "returns": "String (8 chars)",
    "params": [
      {
        "name": "n32",
        "type": "ULong"
      }
    ],
    "summary": "8-character hexadecimal string of a 32-bit unsigned value.",
    "available": true
  },
  {
    "name": "HEX16",
    "kind": "function",
    "library": "hex.bas",
    "include": "#include <hex.bas>",
    "syntax": [
      "B$ = hex16(n16)"
    ],
    "returns": "String (4 chars)",
    "params": [
      {
        "name": "n16",
        "type": "UInteger"
      }
    ],
    "summary": "4-character hex string of a 16-bit unsigned value (calls HEX).",
    "available": true
  },
  {
    "name": "HEX8",
    "kind": "function",
    "library": "hex.bas",
    "include": "#include <hex.bas>",
    "syntax": [
      "C$ = hex8(n8)"
    ],
    "returns": "String (2 chars)",
    "params": [
      {
        "name": "n8",
        "type": "UByte"
      }
    ],
    "summary": "2-character hex string of an 8-bit unsigned value (calls HEX).",
    "available": true
  },
  {
    "name": "hMirror",
    "kind": "function",
    "library": "hmirror.bas",
    "include": "#include <hmirror.bas>",
    "syntax": [
      "Function fastcall hMirror(number as uByte) as uByte"
    ],
    "returns": "uByte",
    "params": [
      {
        "name": "number",
        "type": "uByte"
      }
    ],
    "summary": "Reverses the bit order of a byte (bit 7 to bit 0), e.g. to mirror sprite graphics.",
    "available": true
  },
  {
    "name": "HRPrint",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "HRPrint(x as uByte, y as uByte, char as uInteger, attribute as uByte, overprint as uByte)"
    ],
    "params": [
      {
        "name": "x",
        "type": "uByte",
        "notes": "pixel column"
      },
      {
        "name": "y",
        "type": "uByte",
        "notes": "pixel row (>191 skipped)"
      },
      {
        "name": "char",
        "type": "uInteger",
        "notes": "address of 8 UDG-style bytes; values <256 are taken as ROM charset codes"
      },
      {
        "name": "attribute",
        "type": "uByte",
        "notes": "attribute byte; 0 = do not touch attributes"
      },
      {
        "name": "overprint",
        "type": "uByte",
        "notes": "doc says 0/1; code comments: 0 direct, 0xB6 OR, 0xAE XOR"
      }
    ],
    "summary": "Prints an 8x8 character at any pixel position, optionally setting attributes.",
    "available": false
  },
  {
    "name": "HRPrintFast",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "HRPrintFast(x AS UBYTE, y AS UBYTE, char AS UInteger, attribute AS UBYTE, overprint AS UBYTE)"
    ],
    "params": [
      {
        "name": "x",
        "type": "UBYTE"
      },
      {
        "name": "y",
        "type": "UBYTE"
      },
      {
        "name": "char",
        "type": "UInteger",
        "notes": "data address or charset code"
      },
      {
        "name": "attribute",
        "type": "UBYTE",
        "notes": "0 = none"
      },
      {
        "name": "overprint",
        "type": "UBYTE",
        "notes": "0 or non-zero (OR)"
      }
    ],
    "summary": "Table-driven variant of HRPrint, ~20% faster per character but much larger.",
    "available": false
  },
  {
    "name": "INPUT",
    "kind": "function",
    "library": "input.bas",
    "include": "#include <input.bas>",
    "syntax": [
      "variable = INPUT(max_length)"
    ],
    "returns": "String (always)",
    "params": [
      {
        "name": "max_length",
        "type": "numeric",
        "notes": "maximum characters accepted"
      }
    ],
    "summary": "Library function: shows a cursor, reads a line and returns it as a String when ENTER is pressed.",
    "available": true
  },
  {
    "name": "INPUT42",
    "kind": "function",
    "library": "input42.bas",
    "include": "#include <input42.bas>",
    "syntax": [
      "A$ = INPUT42(MaxChars)"
    ],
    "returns": "String",
    "params": [
      {
        "name": "MaxChars",
        "type": "UINTEGER",
        "notes": "max 65535"
      }
    ],
    "summary": "Simple INPUT that echoes through the 42-column PRINT42 routine.",
    "available": true
  },
  {
    "name": "iSqrt",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "FUNCTION FASTCALL iSqrt(num as uLong) as uInteger"
    ],
    "returns": "uInteger (in HL)",
    "params": [
      {
        "name": "num",
        "type": "uLong",
        "notes": "arrives in DEHL"
      }
    ],
    "summary": "Integer square root (floor), 50-100x faster than ROM SQR.",
    "available": false
  },
  {
    "name": "LEFT",
    "kind": "function",
    "library": "string.bas",
    "include": "#include <string.bas>",
    "syntax": [
      "left(s$, N)"
    ],
    "returns": "String",
    "params": [
      {
        "name": "s$",
        "type": "String"
      },
      {
        "name": "N",
        "type": "numeric"
      }
    ],
    "summary": "First N characters of a string (whole string if shorter).",
    "available": true
  },
  {
    "name": "megaLZDepack",
    "kind": "sub",
    "library": "megalz.bas",
    "include": "#include <megalz.bas>",
    "syntax": [
      "megaLZDepack(source as uInteger, dest as uInteger)"
    ],
    "params": [
      {
        "name": "source",
        "type": "uInteger",
        "notes": "packed data address"
      },
      {
        "name": "dest",
        "type": "uInteger",
        "notes": "destination"
      }
    ],
    "summary": "Decompresses a MegaLZ (v4) packed block from source to dest.",
    "available": true
  },
  {
    "name": "MID",
    "kind": "function",
    "library": "string.bas",
    "include": "#include <string.bas>",
    "syntax": [
      "mid(s$, start, N)"
    ],
    "returns": "String",
    "params": [
      {
        "name": "s$",
        "type": "String"
      },
      {
        "name": "start",
        "type": "numeric",
        "notes": "0-based"
      },
      {
        "name": "N",
        "type": "numeric"
      }
    ],
    "summary": "Up to N characters of a string starting at position start (0-based).",
    "available": true
  },
  {
    "name": "MultiKeys",
    "kind": "function",
    "library": "keys.bas",
    "include": "#include <keys.bas>",
    "syntax": [
      "MultiKeys(KeyCode1 bOR KeyCode2 bOR ...)"
    ],
    "returns": "0 if none, else pressed keys' bits",
    "params": [
      {
        "name": "keycodes",
        "type": "UInteger",
        "notes": "scan codes ORed together, same row half"
      }
    ],
    "summary": "Tests whether any of the given keys is pressed; result can be decoded with bAND to see which.",
    "available": true
  },
  {
    "name": "paint",
    "kind": "sub",
    "library": "putchars.bas",
    "include": "#include <putchars.bas>",
    "syntax": [
      "paint(x as uByte, y as uByte, width as uByte, height as uByte, attribute as ubyte)"
    ],
    "params": [
      {
        "name": "x",
        "type": "uByte"
      },
      {
        "name": "y",
        "type": "uByte"
      },
      {
        "name": "width",
        "type": "uByte"
      },
      {
        "name": "height",
        "type": "uByte"
      },
      {
        "name": "attribute",
        "type": "uByte",
        "notes": "as from ATTR"
      }
    ],
    "summary": "Fills a character rectangle of the attribute area with one attribute byte.",
    "available": true
  },
  {
    "name": "paintData",
    "kind": "sub",
    "library": "putchars.bas",
    "include": "#include <putchars.bas>",
    "syntax": [
      "paintData(x as uByte, y as uByte, width as uByte, height as uByte, address as uInteger)"
    ],
    "params": [
      {
        "name": "x",
        "type": "uByte"
      },
      {
        "name": "y",
        "type": "uByte"
      },
      {
        "name": "width",
        "type": "uByte"
      },
      {
        "name": "height",
        "type": "uByte"
      },
      {
        "name": "address",
        "type": "uInteger",
        "notes": "source attribute data, rows then columns"
      }
    ],
    "summary": "Copies a block of attribute bytes (row-major) to a character rectangle.",
    "available": true
  },
  {
    "name": "PixelScrollUp",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "PixelScrollUp(numOfLines as uByte)"
    ],
    "params": [
      {
        "name": "numOfLines",
        "type": "uByte",
        "notes": "1..191; 0 or >=192 does nothing"
      }
    ],
    "summary": "Scrolls the whole pixel screen up by N pixel rows, blanking the rows uncovered; attributes untouched.",
    "available": false
  },
  {
    "name": "POINT",
    "kind": "function",
    "library": "point.bas",
    "include": "#include <point.bas>",
    "syntax": [
      "POINT(x, y)"
    ],
    "returns": "0 or 1",
    "params": [
      {
        "name": "x",
        "type": "numeric"
      },
      {
        "name": "y",
        "type": "numeric"
      }
    ],
    "summary": "1 if the pixel at (x, y) is set, else 0.",
    "available": true
  },
  {
    "name": "POS",
    "kind": "function",
    "library": "pos.bas",
    "include": "#include <pos.bas>",
    "syntax": [
      "POS()"
    ],
    "returns": "column (type not stated)",
    "params": [],
    "summary": "Horizontal (column) position of the text cursor, 0 = leftmost.",
    "available": true
  },
  {
    "name": "print42",
    "kind": "sub",
    "library": "print42.bas",
    "include": "#include <print42.bas>",
    "syntax": [
      "print42(STRING)"
    ],
    "params": [
      {
        "name": "STRING",
        "type": "String"
      }
    ],
    "summary": "Prints a string in 6-pixel-wide (42 column) characters at the print42 cursor using permanent colours.",
    "available": true
  },
  {
    "name": "print64",
    "kind": "sub",
    "library": "print64.bas",
    "include": "#include <print64.bas>",
    "syntax": [
      "print64(characters$ as String)"
    ],
    "params": [
      {
        "name": "characters$",
        "type": "String",
        "notes": "codes >127 skipped, 13 = newline"
      }
    ],
    "summary": "Prints a string in 4-pixel-wide (64 column) characters at the print64 cursor.",
    "available": true
  },
  {
    "name": "Print64x32",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "Print64x32(info as String)"
    ],
    "params": [
      {
        "name": "info",
        "type": "String"
      }
    ],
    "summary": "Prints a string on a 64x32 grid (4x6 pixel cells, 2048 positions).",
    "available": false
  },
  {
    "name": "Print64x32At",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "Print64x32At(y as uByte, x as uByte)"
    ],
    "params": [
      {
        "name": "y",
        "type": "uByte",
        "notes": "0-31"
      },
      {
        "name": "x",
        "type": "uByte",
        "notes": "0-63"
      }
    ],
    "summary": "Sets the 64x32 print cursor (y 0-31, x 0-63).",
    "available": false
  },
  {
    "name": "Print64x32StringAt",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "Print64x32StringAt(y as ubyte, x as ubyte, text$ as string)"
    ],
    "params": [
      {
        "name": "y",
        "type": "ubyte"
      },
      {
        "name": "x",
        "type": "ubyte"
      },
      {
        "name": "text$",
        "type": "string"
      }
    ],
    "summary": "Combines Print64x32At and Print64x32.",
    "available": false
  },
  {
    "name": "printat42",
    "kind": "sub",
    "library": "print42.bas",
    "include": "#include <print42.bas>",
    "syntax": [
      "printat42(y, x)"
    ],
    "params": [
      {
        "name": "y",
        "type": "numeric",
        "notes": "0-23"
      },
      {
        "name": "x",
        "type": "numeric",
        "notes": "0-41"
      }
    ],
    "summary": "Moves the print42 cursor to row y (0-23), column x (0-41).",
    "available": true
  },
  {
    "name": "printat64",
    "kind": "sub",
    "library": "print64.bas",
    "include": "#include <print64.bas>",
    "syntax": [
      "printat64(y as uByte, x as uByte)"
    ],
    "params": [
      {
        "name": "y",
        "type": "uByte",
        "notes": "0-23"
      },
      {
        "name": "x",
        "type": "uByte",
        "notes": "0-63"
      }
    ],
    "summary": "Moves the print64 cursor to row y (0-23), column x (0-63).",
    "available": true
  },
  {
    "name": "propPrint",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "propPrint(x as ubyte, y as ubyte, spacesize as ubyte, xgap as ubyte, txt$ as string)"
    ],
    "params": [
      {
        "name": "x",
        "type": "ubyte",
        "notes": "pixel X (note x,y order, unlike PRINT)"
      },
      {
        "name": "y",
        "type": "ubyte",
        "notes": "pixel Y (clamped to 184)"
      },
      {
        "name": "spacesize",
        "type": "ubyte",
        "notes": "width of a space"
      },
      {
        "name": "xgap",
        "type": "ubyte",
        "notes": "pixels between letters; 1 typical"
      },
      {
        "name": "txt$",
        "type": "string"
      }
    ],
    "summary": "Proportional-width text printing at any pixel position.",
    "available": false
  },
  {
    "name": "putChars",
    "kind": "sub",
    "library": "putchars.bas",
    "include": "#include <putchars.bas>",
    "syntax": [
      "putChars(x as uByte, y as uByte, width as uByte, height as uByte, dataAddress as uInteger)"
    ],
    "params": [
      {
        "name": "x",
        "type": "uByte",
        "notes": "char column"
      },
      {
        "name": "y",
        "type": "uByte",
        "notes": "char row"
      },
      {
        "name": "width",
        "type": "uByte",
        "notes": "chars"
      },
      {
        "name": "height",
        "type": "uByte",
        "notes": "chars"
      },
      {
        "name": "dataAddress",
        "type": "uInteger",
        "notes": "8 bytes per char, top-left to bottom-right, first column then next"
      }
    ],
    "summary": "Copies a block of 8-byte character bitmaps to the screen at character coordinates (column-major data).",
    "available": true
  },
  {
    "name": "putTile",
    "kind": "sub",
    "library": "puttile.bas",
    "include": "#include <puttile.bas>",
    "syntax": [
      "putTile(x as uByte, y as uByte, graphicsAddr as uInteger)"
    ],
    "params": [
      {
        "name": "x",
        "type": "uByte",
        "notes": "0-31"
      },
      {
        "name": "y",
        "type": "uByte",
        "notes": "0-23"
      },
      {
        "name": "graphicsAddr",
        "type": "uInteger",
        "notes": "36 bytes: 16 rows x 2 bytes, then 2+2 attribute bytes"
      }
    ],
    "summary": "Copies a 16x16 pixel (2x2 char) tile plus its 4 attributes to character position (x, y) using PUSH/POP.",
    "available": true
  },
  {
    "name": "randomBase",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "FUNCTION FASTCALL randomBase() AS UBYTE"
    ],
    "returns": "UBYTE",
    "params": [],
    "summary": "Patrik Rak's stream generator core: pseudo-random byte 0-255 (same generator ZX BASIC uses internally).",
    "available": false
  },
  {
    "name": "randomFixed",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "FUNCTION FASTCALL randomFixed() as FIXED"
    ],
    "returns": "FIXED",
    "params": [],
    "summary": "Random Fixed value between 0 and 1, faster than Float RND.",
    "available": false
  },
  {
    "name": "randomLimit",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "FUNCTION fastcall randomLimit(limit as uByte) as uByte"
    ],
    "returns": "uByte",
    "params": [
      {
        "name": "limit",
        "type": "uByte",
        "notes": "0 returns 0"
      }
    ],
    "summary": "Random integer from 0 to limit inclusive (e.g. randomLimit(5)+1 for a die).",
    "available": false
  },
  {
    "name": "RIGHT",
    "kind": "function",
    "library": "string.bas",
    "include": "#include <string.bas>",
    "syntax": [
      "right(s$, N)"
    ],
    "returns": "String",
    "params": [
      {
        "name": "s$",
        "type": "String"
      },
      {
        "name": "N",
        "type": "numeric"
      }
    ],
    "summary": "Last N characters of a string (whole string if shorter).",
    "available": true
  },
  {
    "name": "scrAddress",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "scrAddress(x as uByte, y as uByte) as UInteger"
    ],
    "returns": "UInteger",
    "params": [
      {
        "name": "x",
        "type": "uByte",
        "notes": "masked to 0-31"
      },
      {
        "name": "y",
        "type": "uByte"
      }
    ],
    "summary": "Address of the top pixel line of character cell (x, y); following lines are +256 each.",
    "available": false
  },
  {
    "name": "SCREEN$",
    "kind": "function",
    "library": "screen.bas",
    "include": "#include <screen.bas>",
    "syntax": [
      "SCREEN$(row, col)"
    ],
    "returns": "String",
    "params": [
      {
        "name": "row",
        "type": "numeric"
      },
      {
        "name": "col",
        "type": "numeric"
      }
    ],
    "summary": "Returns the character displayed at (row, col) if it matches the current font.",
    "available": true
  },
  {
    "name": "SetBank",
    "kind": "sub",
    "library": "memorybank.bas",
    "include": "#include <memorybank.bas>",
    "syntax": [
      "SetBank(bankNumber)"
    ],
    "params": [
      {
        "name": "bankNumber",
        "type": "0..7"
      }
    ],
    "summary": "Pages RAM bank 0-7 into $c000-$ffff and updates BANKM.",
    "available": true
  },
  {
    "name": "SetCodeBank",
    "kind": "sub",
    "library": "memorybank.bas",
    "include": "#include <memorybank.bas>",
    "syntax": [
      "SetCodeBank(bankNumber)"
    ],
    "params": [
      {
        "name": "bankNumber",
        "type": "0..7",
        "notes": "bank 2 is destroyed/skipped"
      }
    ],
    "summary": "Copies the given bank into the $8000 slot (memorybank.md), for the architecture in chapter 14 of the Boriel BASIC book.",
    "available": true
  },
  {
    "name": "time",
    "kind": "function",
    "library": "",
    "include": "",
    "syntax": [
      "FUNCTION FASTCALL time() as uLong"
    ],
    "returns": "uLong (in DEHL)",
    "params": [],
    "summary": "Returns the ROM FRAMES counter (23672-23674) as a uLong.",
    "available": false
  },
  {
    "name": "updateSeed",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "SUB FASTCALL updateSeed()"
    ],
    "params": [],
    "summary": "Re-seeds randomBase from the FRAMES counter.",
    "available": false
  },
  {
    "name": "windowPaint",
    "kind": "sub",
    "library": "",
    "include": "",
    "syntax": [
      "windowPaint(x as uByte, y as uByte, width as uByte, height as uByte, inkCol as ubyte, paperCol as uByte, isBright as uByte, isFlash as uByte)"
    ],
    "params": [
      {
        "name": "x",
        "type": "uByte"
      },
      {
        "name": "y",
        "type": "uByte"
      },
      {
        "name": "width",
        "type": "uByte"
      },
      {
        "name": "height",
        "type": "uByte"
      },
      {
        "name": "inkCol",
        "type": "uByte"
      },
      {
        "name": "paperCol",
        "type": "uByte"
      },
      {
        "name": "isBright",
        "type": "uByte",
        "notes": "0/1"
      },
      {
        "name": "isFlash",
        "type": "uByte",
        "notes": "0/1"
      }
    ],
    "summary": "Sets attributes for a character rectangle from separate ink/paper/bright/flash values (wraps paint).",
    "available": false
  },
  {
    "name": "FarPeek",
    "kind": "function",
    "library": "farmem.bas",
    "include": "#include <farmem.bas>",
    "syntax": [
      "FarPeek(fp)"
    ],
    "returns": "UByte",
    "params": [
      {
        "name": "fp",
        "type": "ULong",
        "notes": "a FARPTR value: logical bank in bits 16-23, address in bits 0-15 (bank 0: resident)"
      }
    ],
    "summary": "The byte at a FARPTR.",
    "available": true
  },
  {
    "name": "FarPeekW",
    "kind": "function",
    "library": "farmem.bas",
    "include": "#include <farmem.bas>",
    "syntax": [
      "FarPeekW(fp)"
    ],
    "returns": "UInteger",
    "params": [
      {
        "name": "fp",
        "type": "ULong",
        "notes": "a FARPTR value: logical bank in bits 16-23, address in bits 0-15 (bank 0: resident)"
      }
    ],
    "summary": "The word at a FARPTR.",
    "available": true
  },
  {
    "name": "FarPoke",
    "kind": "sub",
    "library": "farmem.bas",
    "include": "#include <farmem.bas>",
    "syntax": [
      "FarPoke(fp, v)"
    ],
    "params": [
      {
        "name": "fp",
        "type": "ULong",
        "notes": "a FARPTR value: logical bank in bits 16-23, address in bits 0-15 (bank 0: resident)"
      },
      {
        "name": "v",
        "type": "UByte"
      }
    ],
    "summary": "Writes a byte at a FARPTR.",
    "available": true
  },
  {
    "name": "FarPokeW",
    "kind": "sub",
    "library": "farmem.bas",
    "include": "#include <farmem.bas>",
    "syntax": [
      "FarPokeW(fp, v)"
    ],
    "params": [
      {
        "name": "fp",
        "type": "ULong",
        "notes": "a FARPTR value: logical bank in bits 16-23, address in bits 0-15 (bank 0: resident)"
      },
      {
        "name": "v",
        "type": "UInteger"
      }
    ],
    "summary": "Writes a word at a FARPTR.",
    "available": true
  },
  {
    "name": "FarCopy",
    "kind": "sub",
    "library": "farmem.bas",
    "include": "#include <farmem.bas>",
    "syntax": [
      "FarCopy(fp, dest, count)"
    ],
    "params": [
      {
        "name": "fp",
        "type": "ULong",
        "notes": "a FARPTR value: logical bank in bits 16-23, address in bits 0-15 (bank 0: resident)"
      },
      {
        "name": "dest",
        "type": "UInteger",
        "notes": "resident address; must not be in the window"
      },
      {
        "name": "count",
        "type": "UInteger",
        "notes": "0 copies nothing"
      }
    ],
    "summary": "Copies count bytes from a bank (at fp) to resident memory.",
    "available": true
  },
  {
    "name": "FarCopyTo",
    "kind": "sub",
    "library": "farmem.bas",
    "include": "#include <farmem.bas>",
    "syntax": [
      "FarCopyTo(fp, src, count)"
    ],
    "params": [
      {
        "name": "fp",
        "type": "ULong",
        "notes": "a FARPTR value: logical bank in bits 16-23, address in bits 0-15 (bank 0: resident)"
      },
      {
        "name": "src",
        "type": "UInteger",
        "notes": "resident address; must not be in the window"
      },
      {
        "name": "count",
        "type": "UInteger",
        "notes": "0 copies nothing"
      }
    ],
    "summary": "Copies count bytes from resident memory into a bank (at fp).",
    "available": true
  },
  {
    "name": "FarStr",
    "kind": "function",
    "library": "farmem.bas",
    "include": "#include <farmem.bas>",
    "syntax": [
      "FarStr(fp)"
    ],
    "returns": "String",
    "params": [
      {
        "name": "fp",
        "type": "ULong",
        "notes": "a FARPTR value: logical bank in bits 16-23, address in bits 0-15 (bank 0: resident)"
      }
    ],
    "summary": "A String read from a bank: the image at fp is [length:2][characters].",
    "available": true
  }
];
