// Generated by scripts/build-sp48-wasm.cjs. Do not edit by hand.

export const SP48_WASM_ARTIFACT_NAME = "zx-spectrum48.wasm";
export const SP48_WASM_ABI_VERSION = 1 as const;
export const SP48_WASM_LAYOUT = {
  "abiVersion": 1,
  "layoutVersion": 1,
  "machineStateBlockSize": 64,
  "inputBlockSize": 64,
  "resultBlockSize": 64,
  "eventBufferSize": 4096,
  "memorySize": 65536,
  "dirtyRangeCapacity": 32,
  "dirtyRangeRecordSize": 4,
  "machineStateCpuStateOffset": 0,
  "machineStateFrameTactsOffset": 32,
  "machineStateUlaPortOffset": 36,
  "machineStateIs16KModelOffset": 37,
  "inputKeyboardRowsOffset": 0,
  "inputRunModeOffset": 16,
  "resultTerminationOffset": 0,
  "resultEventCountOffset": 4,
  "resultDirtyRangeCountOffset": 8
} as const;
export const SP48_WASM_LAYOUT_VALUE_ID = {
  "layoutVersion": 0,
  "machineStateBlockSize": 1,
  "inputBlockSize": 2,
  "resultBlockSize": 3,
  "eventBufferSize": 4,
  "memorySize": 5,
  "dirtyRangeCapacity": 6,
  "dirtyRangeRecordSize": 7,
  "machineStateCpuStateOffset": 8,
  "machineStateFrameTactsOffset": 9,
  "machineStateUlaPortOffset": 10,
  "machineStateIs16KModelOffset": 11,
  "inputKeyboardRowsOffset": 12,
  "inputRunModeOffset": 13,
  "resultTerminationOffset": 14,
  "resultEventCountOffset": 15,
  "resultDirtyRangeCountOffset": 16
} as const;

export type Sp48WasmLayoutValueKey = keyof typeof SP48_WASM_LAYOUT_VALUE_ID;
