// Generated by scripts/build-sp48-wasm.cjs. Do not edit by hand.

export const SP48_WASM_ARTIFACT_NAME = "zx-spectrum48.wasm";
export const SP48_WASM_ABI_VERSION = 1 as const;
export const SP48_WASM_LAYOUT = {
  "abiVersion": 1,
  "layoutVersion": 1,
  "machineStateBlockSize": 64,
  "inputBlockSize": 64,
  "resultBlockSize": 64,
  "eventBufferSize": 4096,
  "machineStateCpuStateOffset": 0,
  "machineStateFrameTactsOffset": 32,
  "machineStateUlaPortOffset": 36,
  "inputKeyboardRowsOffset": 0,
  "inputRunModeOffset": 16,
  "resultTerminationOffset": 0,
  "resultEventCountOffset": 4
} as const;
export const SP48_WASM_LAYOUT_VALUE_ID = {
  "layoutVersion": 0,
  "machineStateBlockSize": 1,
  "inputBlockSize": 2,
  "resultBlockSize": 3,
  "eventBufferSize": 4,
  "machineStateCpuStateOffset": 5,
  "machineStateFrameTactsOffset": 6,
  "machineStateUlaPortOffset": 7,
  "inputKeyboardRowsOffset": 8,
  "inputRunModeOffset": 9,
  "resultTerminationOffset": 10,
  "resultEventCountOffset": 11
} as const;

export type Sp48WasmLayoutValueKey = keyof typeof SP48_WASM_LAYOUT_VALUE_ID;
