import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, statSync } from "fs";
import { join, relative } from "path";
import { fileURLToPath } from "url";

import { semanticTokens } from "@renderer/theming/tokens/semantic";
import { dimensionTokens } from "@renderer/theming/tokens/dimensions";
import { rowSizeTokens } from "@renderer/theming/tokens/rowSizes";
import { componentAliases } from "@renderer/theming/tokens/componentAliases";
import { staticTokens, toneTokens } from "@renderer/theming/tokens/staticTokens";
import { ACCENT_IDS, DEFAULT_ACCENT } from "@common/theming/accents";

/**
 * Build the full token set a tone actually emits, in the same order ThemeProvider composes it.
 * There is no longer a `darkTheme` / `lightTheme` object to inspect: a theme is a tone plus the
 * ramps it selects.
 */
function tokensFor(tone: "dark" | "light", accent = DEFAULT_ACCENT) {
  return {
    ...staticTokens,
    ...toneTokens(tone),
    ...semanticTokens(tone, accent),
    ...dimensionTokens(tone),
    ...rowSizeTokens(),
    ...componentAliases
  };
}

const darkTheme = tokensFor("dark");
const lightTheme = tokensFor("light");

/**
 * The theme-token contract.
 *
 * Colours are the one part of this app that is already tokenized, but nothing has ever checked
 * that the tokens a stylesheet *asks* for are tokens a theme actually *defines*. The result is a
 * set of silent failures: `var(--undefined-name)` is not an error in CSS, it simply drops the
 * declaration, so a missing token looks like a design decision rather than a bug.
 *
 * This test closes that gap. It was written before the token layer landed (Phase 0.1 of
 * .plans/UI_MODERNIZATION_PLAN.md) so that its initial failures documented the existing breakage,
 * and now guards the layer that replaced it.
 */

const RENDERER = fileURLToPath(new URL("../../src/renderer", import.meta.url));
const REPO = fileURLToPath(new URL("../..", import.meta.url));

/**
 * Custom properties supplied at runtime rather than by the token layer, so they can never appear in
 * `tokensFor()`. Keep this list short and justified: every entry is a hole in the contract.
 */
const RUNTIME_PROVIDED = new Set([
  // Synthesized by ThemeProvider from the platform-specific font tokens.
  "--main-font-family",
  // ThemeProvider resolves these two from user settings rather than from a theme: the monospace
  // family from View | Panel Options | Font Family, the size from | Font Size.
  "--monospace-font",
  "--panel-font-size",
  // Emitted by `rowSizeTokens()` alongside the --row-size-* family.
  "--panel-line-height",
  // Supplied by Radix on the select trigger element itself.
  "--radix-select-trigger-width"
]);

/** Generated by `generateBaseSpacings()` in ThemeProvider from `--space-base`. */
const isGeneratedSpacing = (name: string) => /^--space-\d/.test(name);

// ---------------------------------------------------------------------------------------------
// File collection
// ---------------------------------------------------------------------------------------------

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const allFiles = walk(RENDERER);
const styleFiles = allFiles.filter((f) => f.endsWith(".scss") || f.endsWith(".css"));
const codeFiles = allFiles.filter(
  (f) => (f.endsWith(".tsx") || f.endsWith(".ts")) && !f.includes(join("theming", ""))
);

type Ref = { name: string; where: string };

/**
 * Blank out SCSS/CSS comments so that prose mentioning a token — or describing a bug in terms of
 * the very syntax being scanned for — is not mistaken for code. Comment bodies are replaced with
 * spaces rather than removed so that line and column numbers stay accurate for error reporting.
 */
function stripStyleComments(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "))
    .replace(/\/\/[^\n]*/g, (m) => " ".repeat(m.length));
}

const isStyle = (file: string) => file.endsWith(".scss") || file.endsWith(".css");

/**
 * Comment stripping is applied to stylesheets only. In TSX a `//` also appears inside string
 * literals (`"https://…"`), where blanking to end of line could hide a real token reference.
 */
function readLines(file: string): string[] {
  const source = readFileSync(file, "utf-8");
  return (isStyle(file) ? stripStyleComments(source) : source).split("\n");
}

function locate(file: string, line: number): string {
  return `${relative(REPO, file)}:${line}`;
}

// ---------------------------------------------------------------------------------------------
// Scanners
// ---------------------------------------------------------------------------------------------

/** `var(--name)` / `var(--name, fallback)` references in stylesheets. */
function collectVarRefs(): Ref[] {
  const re = /var\(\s*(--[A-Za-z0-9_-]*)/g;
  const refs: Ref[] = [];
  for (const file of styleFiles) {
    readLines(file).forEach((text, i) => {
      for (const m of text.matchAll(re)) {
        refs.push({ name: m[1], where: locate(file, i + 1) });
      }
    });
  }
  return refs;
}

/** `--name:` declarations in stylesheets — a variable defined by the app's own CSS. */
function collectVarDeclarations(): Set<string> {
  const re = /(--[A-Za-z0-9_-]+)\s*:/g;
  const declared = new Set<string>();
  for (const file of styleFiles) {
    const source = stripStyleComments(readFileSync(file, "utf-8"));
    for (const m of source.matchAll(re)) declared.add(m[1]);
  }
  return declared;
}

/**
 * Token names passed to the theme from TSX as bare strings — `fill="--color-x"`,
 * `getThemeProperty("--color-x")`, `color="--color-x"`. These bypass CSS entirely
 * (see §2.4g of the plan), so `var()` scanning alone would miss them.
 */
function collectCodeTokenRefs(): Ref[] {
  // Require at least one letter after `--` so display placeholders like "--" and "----"
  // (Values.tsx renders those for undefined values) are not mistaken for token names.
  const re = /["'](--[A-Za-z][A-Za-z0-9_-]*)["']/g;
  const refs: Ref[] = [];
  for (const file of codeFiles) {
    readLines(file).forEach((text, i) => {
      for (const m of text.matchAll(re)) {
        refs.push({ name: m[1], where: locate(file, i + 1) });
      }
    });
  }
  return refs;
}

const darkKeys = new Set(Object.keys(darkTheme));
const lightKeys = new Set(Object.keys(lightTheme));
const declaredInCss = collectVarDeclarations();

/**
 * A reference resolves if a theme defines it, the app's own CSS declares it (OverlayScrollbars'
 * `--os-*` internals, for instance), it is generated at runtime, or it is a documented hole.
 *
 * A name ending in `-` is a prefix built by string concatenation — e.g.
 * `"--color-tabbutton-fill-" + (isActive ? "active" : "inactive")`. Those cannot be resolved
 * statically, so the weaker assertion is that *some* token starts with the prefix.
 */
function resolves(name: string): boolean {
  if (name.endsWith("-")) {
    return [...darkKeys].some((k) => k.startsWith(name));
  }
  return (
    (darkKeys.has(name) && lightKeys.has(name)) ||
    declaredInCss.has(name) ||
    RUNTIME_PROVIDED.has(name) ||
    isGeneratedSpacing(name)
  );
}

function report(refs: Ref[]): string {
  const grouped = new Map<string, string[]>();
  for (const r of refs) {
    if (!grouped.has(r.name)) grouped.set(r.name, []);
    grouped.get(r.name)!.push(r.where);
  }
  return [...grouped.entries()]
    .sort()
    .map(([name, wheres]) => `  ${name}\n${wheres.map((w) => `      ${w}`).join("\n")}`)
    .join("\n");
}

// ---------------------------------------------------------------------------------------------
// The contract
// ---------------------------------------------------------------------------------------------

describe("theme token contract", () => {
  it("finds the files it is supposed to scan", () => {
    // Guards against a silent pass caused by a bad path or a moved directory.
    expect(styleFiles.length).toBeGreaterThan(100);
    expect(codeFiles.length).toBeGreaterThan(100);
    expect(darkKeys.size).toBeGreaterThan(150);
  });

  it("emits the same token set for every accent", () => {
    // The accent axis must not add or remove tokens, only change their values — otherwise a
    // stylesheet would resolve under one accent and not another.
    const base = Object.keys(tokensFor("dark", DEFAULT_ACCENT)).sort();
    for (const accent of ACCENT_IDS) {
      expect(Object.keys(tokensFor("dark", accent)).sort(), `accent ${accent}`).toEqual(base);
      expect(Object.keys(tokensFor("light", accent)).sort(), `accent ${accent}`).toEqual(base);
    }
  });

  it("defines the same token set in both themes", () => {
    const onlyDark = [...darkKeys].filter((k) => !lightKeys.has(k)).sort();
    const onlyLight = [...lightKeys].filter((k) => !darkKeys.has(k)).sort();
    expect(
      { onlyDark, onlyLight },
      "Both themes must define exactly the same tokens: a token present in only one theme " +
        "resolves to nothing in the other, and the failure is invisible."
    ).toEqual({ onlyDark: [], onlyLight: [] });
  });

  it("has no empty var() calls", () => {
    const empties: string[] = [];
    for (const file of styleFiles) {
      readLines(file).forEach((text, i) => {
        if (/var\(\s*\)/.test(text)) empties.push(locate(file, i + 1));
      });
    }
    expect(empties, "`var()` with no argument is invalid CSS; the declaration is dropped.").toEqual(
      []
    );
  });

  it("resolves every var(--…) used in a stylesheet", () => {
    const unresolved = collectVarRefs().filter((r) => !resolves(r.name));
    expect(
      unresolved.length === 0 ? "" : `\n${report(unresolved)}\n`,
      "These custom properties are referenced but defined by no theme, no stylesheet and no " +
        "documented runtime source. Each one silently drops its declaration."
    ).toBe("");
  });

  it("resolves every token name passed to the theme from component code", () => {
    const unresolved = collectCodeTokenRefs().filter((r) => !resolves(r.name));
    expect(
      unresolved.length === 0 ? "" : `\n${report(unresolved)}\n`,
      "These token names reach getThemeProperty()/processStyleValue() as strings but are not " +
        "defined in both themes. They bypass CSS, so nothing else would catch them."
    ).toBe("");
  });
});
