import { describe, it, expect, beforeEach } from "vitest";

import { NexAnnotationEditorController } from "@renderer/appIde/DocumentPanels/Next/annotationEditor/NexAnnotationEditorController";
import type { NexAnnotationEditorEnvironment } from "@renderer/appIde/DocumentPanels/Next/annotationEditor/NexAnnotationEditorModel";
import { WHOLE_BANK_CONFIRM_MESSAGE } from "@renderer/appIde/DocumentPanels/Next/annotationEditor/NexAnnotationEditorViewModel";

import type { DisassemblyItem } from "@renderer/appIde/disassemblers/common-types";

import { createFakePorts, FakeSession, publishedBank, type FakePorts } from "./fakes";
import {
  aLabelledOperandRow,
  anAnnotationModelWithLabels,
  aListing,
  anAnnotationModel,
  anEnvironment,
  anOperandRow,
  aRow,
  BANK,
  SIDECAR
} from "./fixtures";

/*
 * Journey tests: every flow driven by dispatching intents against fakes, with no React and no DOM.
 *
 * `settle()` drains follow-up work transitively, so a handler that starts more work — a dialog whose
 * result triggers a publish, whose snapshot regenerates the listing — is fully awaited.
 */

let fakes: FakePorts;

function open(
  env: Partial<NexAnnotationEditorEnvironment> = {},
  options: Parameters<typeof createFakePorts>[0] & { items?: DisassemblyItem[] } = {}
) {
  const { items, ...portOptions } = options;
  fakes = createFakePorts(portOptions);
  const controller = new NexAnnotationEditorController(fakes.ports, anEnvironment(env));
  return { controller, items: items ?? aListing(6) };
}

/**
 * An opened editor with a listing already reported.
 *
 * The listing is generated by the component around the editor — a dump with no sidecar still
 * disassembles — so it arrives as an intent rather than being fetched.
 */
async function opened(
  env: Partial<NexAnnotationEditorEnvironment> = {},
  options: Parameters<typeof createFakePorts>[0] & { items?: DisassemblyItem[] } = {}
) {
  const { controller, items } = open(env, options);
  await controller.dispatch({ type: "opened" });
  await controller.dispatch({ type: "listingChanged", items });
  await controller.settle();
  return controller;
}

beforeEach(() => {
  fakes = createFakePorts();
});

describe("opening", () => {
  it("subscribes to the session for its own sidecar and bank", async () => {
    const controller = await opened();
    expect(fakes.session.subscribeCalls).toEqual([{ path: SIDECAR, bank: BANK }]);
    expect(controller.state.annotations).toBeDefined();
  });

  it("takes the listing the surrounding component reports", async () => {
    const controller = await opened();
    expect(controller.state.items.length).toEqual(6);
  });

  it("hands the loaded model out for the listing to be generated from", async () => {
    // --- The editor does not generate the listing; it publishes the model the component needs.
    const controller = await opened();
    expect(controller.viewModel.annotations).toBe(controller.state.annotations);
  });

  it("does not subscribe for a document with no sidecar", async () => {
    await opened({ annotationPath: undefined });
    expect(fakes.session.subscribeCalls).toEqual([]);
  });

  it("reports a sidecar that failed to load, and offers no model to annotate by", async () => {
    const session = new FakeSession({ annotations: undefined, loadError: "bad json" });
    const controller = await opened({}, { session });
    expect(controller.state.loadError).toEqual("bad json");
    expect(controller.viewModel.annotations).toEqual(undefined);
  });

  it("still holds the rows of an unannotated dump", async () => {
    // --- A popped-out loading screen has no sidecar but still disassembles, and the editor needs
    // --- those rows: selection works, even though every editing action is disabled.
    const session = new FakeSession({ annotations: undefined });
    const controller = await opened({ annotationPath: undefined }, { session });
    expect(controller.state.items.length).toEqual(6);
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 2, activeIndex: 2 });
    expect(controller.viewModel.menu.every((entry) => entry.kind === "separator" || entry.disabled))
      .toEqual(true);
  });
});

describe("the environment changing", () => {
  it("re-subscribes when the bank changes", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "environmentChanged", env: anEnvironment({ bank: 6 }) });
    await controller.settle();
    expect(fakes.session.subscribeCalls).toEqual([
      { path: SIDECAR, bank: BANK },
      { path: SIDECAR, bank: 6 }
    ]);
    expect(fakes.session.unsubscribeCount).toEqual(1);
  });

  it("does nothing at all for an unchanged environment", async () => {
    const controller = await opened();
    const before = controller.state;
    await controller.dispatch({ type: "environmentChanged", env: anEnvironment() });
    await controller.settle();
    // --- The same state object: the container derives the environment fresh on every render.
    expect(controller.state).toBe(before);
  });

  it("persists a changed display setting into the sidecar", async () => {
    const controller = await opened();
    await controller.dispatch({
      type: "environmentChanged",
      env: anEnvironment({ decimalView: true })
    });
    await controller.settle();
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.decimalView).toEqual(true);
  });

  it("does not dirty the sidecar for settings that came out of it", async () => {
    // --- The document opens on the settings the sidecar remembers, so the first environment push
    // --- must not look like an edit.
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: { [String(BANK)]: { offsetIndex: 1, decimalView: true, regions: [] } }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({ decimalView: true }, { session });
    await controller.dispatch({
      type: "environmentChanged",
      env: anEnvironment({ decimalView: true, viewMode: "memory" })
    });
    await controller.settle();
    // --- `viewMode` did change, so that one *is* an edit; `decimalView` alone would not have been.
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.decimalView).toEqual(true);
  });
});

describe("selection", () => {
  it("anchors a plain click on the clicked row", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 3, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 3, activeIndex: 3 });
  });

  it("keeps the anchor when a click extends the range", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 1, extend: false });
    await controller.dispatch({ type: "rowSelected", index: 4, extend: true });
    expect(controller.state.selection).toEqual({ anchorIndex: 1, activeIndex: 4 });
  });

  it("moves the active row, clamped to the listing", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    await controller.dispatch({ type: "selectionMoved", delta: 2, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 2, activeIndex: 2 });

    // --- Six rows, so index 5 is the last.
    await controller.dispatch({ type: "selectionMoved", delta: 100, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 5, activeIndex: 5 });

    await controller.dispatch({ type: "selectionMoved", delta: -100, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 0, activeIndex: 0 });
  });

  it("extends from the anchor when moving with shift", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    await controller.dispatch({ type: "selectionMoved", delta: 2, extend: true });
    expect(controller.state.selection).toEqual({ anchorIndex: 2, activeIndex: 4 });
  });

  it("does nothing with an empty listing", async () => {
    const controller = await opened({}, { items: [] });
    await controller.dispatch({ type: "selectionMoved", delta: 1, extend: false });
    expect(controller.state.selection).toEqual(undefined);
  });
});

describe("writing", () => {
  /** Make one ordinary edit — a synopsis comment on the first row. */
  async function edit(controller: Awaited<ReturnType<typeof opened>>, synopsis: string, row = 0) {
    fakes.dialogs.answerWith("synopsisComment", { synopsis });
    await controller.dispatch({ type: "rowSelected", index: row, extend: false });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: row });
    await controller.settle();
  }

  it("writes an edit without being asked", async () => {
    const controller = await opened();
    await edit(controller, "entry");

    // --- The edit is published and written in one step; there is no intent that means "save".
    expect(fakes.session.writeCalls).toEqual([SIDECAR]);

    await fakes.session.writesSettled();
    expect(controller.state.dirty).toEqual(false);
    expect(controller.state.saveError).toEqual(undefined);
  });

  it("keeps the edits and reports why when the write fails", async () => {
    const controller = await opened();
    fakes.session.writeError = "read-only";
    await edit(controller, "entry");
    await fakes.session.writesSettled();

    expect(controller.state.saveError).toEqual("read-only");
    expect(controller.state.dirty).toEqual(true);
  });

  /*
   * The regression this policy exists to avoid.
   *
   * `dirty` is true for as long as a write takes, so reporting *it* outward would put an unsaved
   * mark on the tab for a moment on every annotation — a flicker with no meaning, in an editor that
   * has no Save to make it go away.
   */
  it("never marks the document unsaved for an edit that was written", async () => {
    const controller = await opened();
    await edit(controller, "a");
    await fakes.session.writesSettled();
    await edit(controller, "b", 1);
    await fakes.session.writesSettled();

    expect(fakes.unwrittenChanged).not.toHaveBeenCalled();
  });

  it("marks the document unsaved when a write fails, and clears it when one lands", async () => {
    const controller = await opened();

    fakes.session.writeError = "read-only";
    await edit(controller, "a");
    await fakes.session.writesSettled();
    expect(fakes.unwrittenChanged).toHaveBeenCalledWith(true);

    fakes.unwrittenChanged.mockClear();
    fakes.session.writeError = undefined;
    await edit(controller, "b", 1);
    await fakes.session.writesSettled();
    expect(fakes.unwrittenChanged).toHaveBeenCalledWith(false);
  });

  it("reports a change in that state only once", async () => {
    const controller = await opened();
    fakes.session.writeError = "read-only";
    await edit(controller, "a");
    await fakes.session.writesSettled();

    fakes.unwrittenChanged.mockClear();
    await edit(controller, "b", 1);
    await fakes.session.writesSettled();
    // --- Still failing: no news.
    expect(fakes.unwrittenChanged).not.toHaveBeenCalled();
  });

  it("writes nothing without a loaded model", async () => {
    const session = new FakeSession({ annotations: undefined });
    const controller = await opened({}, { session });
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 0 });
    await controller.settle();
    expect(session.writeCalls).toEqual([]);
  });
});

describe("comments", () => {
  it("writes a synopsis comment at the row's own offset", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "the entry point" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 2 });
    await controller.settle();

    expect(fakes.dialogs.callsTo("synopsisComment")[0]).toMatchObject({ bankOffset: 2 });
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.lineAnnotations).toEqual({
      "2": { synopsis: "the entry point" }
    });
  });

  it("offers the existing comment as the dialog's starting value", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            lineAnnotations: { "2": { comment: "old" } }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    fakes.dialogs.answerWith("endOfLineComment", undefined);
    await controller.dispatch({ type: "endOfLineCommentRequested", rowIndex: 2 });
    await controller.settle();
    expect(fakes.dialogs.callsTo("endOfLineComment")[0]).toMatchObject({ initialComment: "old" });
  });

  it("changes nothing when the dialog is dismissed", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", undefined);
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 2 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(false);
  });

  it("clears the comment when the dialog returns an empty one", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "x" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 2 });
    await controller.settle();

    fakes.dialogs.answerWith("synopsisComment", { synopsis: undefined });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 2 });
    await controller.settle();
    // --- An emptied annotation is removed rather than stored as `{}`.
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.lineAnnotations).toEqual(undefined);
  });

  it("acts on the selection when no row is named", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 4, extend: false });
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "from the toolbar" });
    await controller.dispatch({ type: "synopsisCommentRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("synopsisComment")[0]).toMatchObject({ bankOffset: 4 });
  });

  it("does nothing with neither a row nor a selection", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "synopsisCommentRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("synopsisComment")).toEqual([]);
  });
});

describe("bank comment", () => {
  it("opens with the bank's comment and publishes the answer, needing no row", async () => {
    const session = new FakeSession({
      annotations: anAnnotationModel({
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [{ start: 0, end: 0x3fff, type: "disassemble" }],
            comment: "Old"
          }
        }
      })
    });
    const controller = await opened({}, { session });
    fakes.dialogs.answerWith("bankComment", { comment: "Music player\nIM2 handler" });

    await controller.dispatch({ type: "bankCommentRequested" });
    await controller.settle();

    expect(fakes.dialogs.callsTo("bankComment")).toEqual([{ bank: BANK, initialComment: "Old" }]);
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.comment).toEqual(
      "Music player\nIM2 handler"
    );
  });

  it("clears the comment when the dialog answers with none", async () => {
    const session = new FakeSession({
      annotations: anAnnotationModel({
        banks: { [String(BANK)]: { offsetIndex: 1, regions: [], comment: "Old" } }
      })
    });
    const controller = await opened({}, { session });
    fakes.dialogs.answerWith("bankComment", { comment: undefined });

    await controller.dispatch({ type: "bankCommentRequested" });
    await controller.settle();

    expect(publishedBank(fakes.session, SIDECAR, BANK)).not.toHaveProperty("comment");
  });

  it("writes nothing when dismissed or unchanged", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "bankCommentRequested" });
    await controller.settle();
    fakes.dialogs.answerWith("bankComment", { comment: undefined });
    await controller.dispatch({ type: "bankCommentRequested" });
    await controller.settle();
    expect(fakes.session.writeCalls).toEqual([]);
  });

  it("does not open without a loaded model", async () => {
    const session = new FakeSession({ annotations: undefined });
    const controller = await opened({}, { session });
    await controller.dispatch({ type: "bankCommentRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("bankComment")).toEqual([]);
  });

  it("opens the toolbar menu with nothing selected, and leaves no row target behind", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "toolbarMenuRequested" });
    await controller.settle();
    expect(controller.state.contextTarget).toBeUndefined();
    expect(controller.viewModel.toolbar.menuEnabled).toEqual(true);
  });
});

describe("sprites view edits", () => {
  it("writes the sprite format and offset to the bank", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "spriteSettingsChanged", format: "4bit" });
    await controller.dispatch({ type: "spriteSettingsChanged", offset: 3 });
    await controller.settle();

    expect(publishedBank(fakes.session, SIDECAR, BANK)?.sprites).toEqual({ format: "4bit", offset: 3 });
    expect(controller.viewModel.bankSprites).toEqual({ format: "4bit", offset: 3, active: false });
  });

  it("publishes nothing for an unchanged setting", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "spriteSettingsChanged", format: "8bit", offset: 0 });
    await controller.settle();
    expect(fakes.session.writeCalls).toEqual([]);
    expect(controller.viewModel.bankSprites).toEqual({ format: "8bit", offset: 0, active: false });
  });

  it("remembers the Sprites view in the same write as lastView", async () => {
    const controller = await opened({ spritesViewActive: false });
    await controller.dispatch({
      type: "environmentChanged",
      env: anEnvironment({ viewMode: "disassembly", spritesViewActive: true })
    });
    await controller.settle();
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.sprites).toEqual({ active: true });
    const writesAfterShowing = fakes.session.writeCalls.length;

    // --- Back to Memory: `lastView` and `active` change together, in one publish.
    await controller.dispatch({
      type: "environmentChanged",
      env: anEnvironment({ viewMode: "memory", spritesViewActive: false })
    });
    await controller.settle();
    const bank = publishedBank(fakes.session, SIDECAR, BANK);
    expect(bank?.lastView).toBe("memory");
    expect(bank).not.toHaveProperty("sprites");
    expect(fakes.session.writeCalls.length).toBe(writesAfterShowing + 1);
  });

  it("never writes the flag for a document without a Sprites view", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "environmentChanged", env: anEnvironment({ viewMode: "memory" }) });
    await controller.settle();
    expect(publishedBank(fakes.session, SIDECAR, BANK)).not.toHaveProperty("sprites");
  });

  it("marks an exact byte span as a region, without the region dialog", async () => {
    const controller = await opened();
    await controller.dispatch({
      type: "regionSpanMarked",
      start: 0x800,
      end: 0x8ff,
      regionType: "bytes"
    });
    await controller.settle();

    expect(fakes.dialogs.callsTo("region")).toEqual([]);
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.regions).toContainEqual({
      start: 0x800,
      end: 0x8ff,
      type: "bytes"
    });
  });

  it("asks before a span that rewrites the whole bank", async () => {
    const controller = await opened();
    fakes.nativeConfirm.mockReturnValue(false);
    await controller.dispatch({
      type: "regionSpanMarked",
      start: 0,
      end: 0x3fff,
      regionType: "bytes"
    });
    await controller.settle();

    expect(fakes.nativeConfirm).toHaveBeenCalledWith(WHOLE_BANK_CONFIRM_MESSAGE);
    expect(fakes.session.writeCalls).toEqual([]);
  });
});

describe("labels", () => {
  it("opens the dialog on the chosen scope, with both candidate values", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("label", undefined);
    await controller.dispatch({ type: "labelRequested", scope: "global", rowIndex: 2 });
    await controller.settle();

    expect(fakes.dialogs.callsTo("label")[0]).toMatchObject({
      bank: BANK,
      initialScope: "global",
      // --- A global label names a 16-bit address; a local one the bank-relative offset.
      initialGlobalValue: 0x4002,
      initialLocalValue: 2
    });
  });

  it("saves a global label", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("label", {
      action: "save",
      scope: "global",
      name: "Start",
      value: 0x4002
    });
    await controller.dispatch({ type: "labelRequested", scope: "global", rowIndex: 2 });
    await controller.settle();

    const annotations = fakes.session.snapshotFor(SIDECAR).annotations;
    expect(annotations?.globalLabels).toEqual([{ name: "Start", value: 0x4002 }]);
  });

  it("saves a local label onto its own bank", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("label", {
      action: "save",
      scope: "local",
      name: "Loop",
      value: 2
    });
    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.localLabels).toEqual([
      { name: "Loop", value: 2 }
    ]);
  });

  it("confirms every delete before applying it", async () => {
    const controller = await opened();
    const label = { scope: "local" as const, name: "Loop", value: 2 };
    fakes.dialogs.answerWith("label", { action: "delete", ...label, originalLabel: label });

    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();

    expect(fakes.confirm).toHaveBeenCalledTimes(1);
    expect(fakes.confirm.mock.calls[0][0]).toMatchObject({
      title: "Delete label",
      code: "Loop",
      danger: true
    });
  });

  it("applies nothing when the delete is refused", async () => {
    const controller = await opened();
    const label = { scope: "local" as const, name: "Loop", value: 2 };
    fakes.dialogs.answerWith("label", { action: "delete", ...label, originalLabel: label });
    fakes.confirm.mockResolvedValue(false);

    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(false);
  });

  it("counts the operand references a delete would clear", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            localLabels: [{ name: "Loop", value: 2 }],
            operandReferences: {
              "0": [{ operandIndex: 0, scope: "local", name: "Loop" }],
              "1": [{ operandIndex: 0, scope: "local", name: "Loop" }]
            }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    const label = { scope: "local" as const, name: "Loop", value: 2 };
    fakes.dialogs.answerWith("label", { action: "delete", ...label, originalLabel: label });

    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();

    expect(fakes.confirm.mock.calls[0][0].linesAfterCode).toEqual([
      "2 operand references to it will be cleared."
    ]);
    // --- And the references go with the label.
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.operandReferences).toEqual(undefined);
  });

  it("refuses a delete that names nothing to remove", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("label", {
      action: "delete",
      scope: "local",
      name: "Loop",
      value: 2
    });
    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();
    expect(fakes.confirm).not.toHaveBeenCalled();
    expect(controller.state.dirty).toEqual(false);
  });
});

describe("the Labels list", () => {
  it("hands the dialog the bank's labels, with reference counts", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        globalLabels: [{ name: "Start", value: 0x8000 }],
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            localLabels: [{ name: "Loop", value: 2 }],
            operandReferences: { "0": [{ operandIndex: 0, scope: "local", name: "Loop" }] }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    fakes.dialogs.answerWith("manageLabels", undefined);
    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();

    const args = fakes.dialogs.callsTo("manageLabels")[0];
    expect(args.labels).toEqual([
      { name: "Start", value: 0x8000, scope: "global", referenced: false, referenceCount: 0 },
      { name: "Loop", value: 2, scope: "local", bank: BANK, referenced: true, referenceCount: 1 }
    ]);
  });

  it("stays open across an edit, and hands back the refreshed list", async () => {
    // --- The list is a session, not a question: `onAddLabel` runs while it is still mounted.
    const controller = await opened();
    let refreshed: any[] | undefined;
    fakes.dialogs.answerWith("manageLabels", async (args: any) => {
      fakes.dialogs.answerWith("label", {
        action: "save",
        scope: "global",
        name: "Added",
        value: 0x1234
      });
      refreshed = await args.onAddLabel("global");
      return undefined;
    });

    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();

    expect(refreshed).toEqual([
      { name: "Added", value: 0x1234, scope: "global", referenced: false, referenceCount: 0 }
    ]);
  });

  it("deletes from within the list, confirmation and all", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            localLabels: [{ name: "Loop", value: 2 }]
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    let refreshed: any[] | undefined;
    fakes.dialogs.answerWith("manageLabels", async (args: any) => {
      refreshed = await args.onDeleteLabel({ scope: "local", name: "Loop", value: 2 });
      return undefined;
    });

    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();

    expect(fakes.confirm).toHaveBeenCalledTimes(1);
    expect(refreshed).toEqual([]);
  });

  it("navigates on Go To, which is the one action that closes the list", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("manageLabels", {
      action: "go-to",
      label: { scope: "local", name: "Loop", value: 0x20 }
    });
    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();
    // --- A local label is bank-relative, so the address is the display offset plus it.
    expect(fakes.navigateToAddress).toHaveBeenCalledWith(0x4020);
  });

  it("navigates to a global label's own address", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("manageLabels", {
      action: "go-to",
      label: { scope: "global", name: "Start", value: 0x9000 }
    });
    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();
    expect(fakes.navigateToAddress).toHaveBeenCalledWith(0x9000);
  });
});

describe("operand labels", () => {
  it("attaches a label to a decoded operand", async () => {
    const controller = await opened({}, { items: [anOperandRow(0), aRow(3)] });
    fakes.dialogs.answerWith("operandLabel", {
      action: "apply",
      operandIndex: 0,
      scope: "global",
      name: "Target"
    });
    await controller.dispatch({ type: "operandLabelRequested", rowIndex: 0 });
    await controller.settle();

    expect(publishedBank(fakes.session, SIDECAR, BANK)?.operandReferences).toEqual({
      "0": [{ operandIndex: 0, scope: "global", name: "Target" }]
    });
  });

  it("creates and attaches in one step", async () => {
    const controller = await opened({}, { items: [anOperandRow(0)] });
    fakes.dialogs.answerWith("operandLabel", {
      action: "create-label",
      operandIndex: 0,
      scope: "local",
      name: "Made",
      value: 0x30
    });
    await controller.dispatch({ type: "operandLabelRequested", rowIndex: 0 });
    await controller.settle();

    const bank = publishedBank(fakes.session, SIDECAR, BANK);
    expect(bank?.localLabels).toEqual([{ name: "Made", value: 0x30 }]);
    expect(bank?.operandReferences?.["0"]).toEqual([
      { operandIndex: 0, scope: "local", name: "Made" }
    ]);
  });

  it("clears a reference without needing a label", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            operandReferences: { "0": [{ operandIndex: 0, scope: "local", name: "Loop" }] }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session, items: [anOperandRow(0)] });
    fakes.dialogs.answerWith("operandLabel", { action: "clear", operandIndex: 0 });
    await controller.dispatch({ type: "operandLabelRequested", rowIndex: 0 });
    await controller.settle();

    expect(publishedBank(fakes.session, SIDECAR, BANK)?.operandReferences).toEqual(undefined);
  });
});

describe("regions", () => {
  it("marks a row through the region dialog", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("region", { start: 2, end: 2, type: "bytes" });
    await controller.dispatch({ type: "regionTypeMarked", regionType: "bytes", rowIndex: 2 });
    await controller.settle();

    // --- The dialog opens on the span the gesture named, and on the type it asked for.
    expect(fakes.dialogs.callsTo("region")[0]).toMatchObject({
      initialStart: 2,
      initialEnd: 2,
      initialType: "bytes"
    });
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.regions).toEqual([
      { start: 0, end: 1, type: "disassemble" },
      { start: 2, end: 2, type: "bytes" },
      { start: 3, end: 0x3fff, type: "disassemble" }
    ]);
  });

  it("marks the whole selection when the row is inside it", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 1, extend: false });
    await controller.dispatch({ type: "rowSelected", index: 3, extend: true });
    fakes.dialogs.answerWith("region", (args: any) => ({
      start: args.initialStart,
      end: args.initialEnd,
      type: "words"
    }));
    await controller.dispatch({ type: "regionTypeMarked", regionType: "words", rowIndex: 2 });
    await controller.settle();
    expect(fakes.dialogs.callsTo("region")[0]).toMatchObject({ initialStart: 1, initialEnd: 3 });
  });

  it("clears the selection once a region is applied", async () => {
    // --- The listing is about to change shape, so the selection it was made against is stale.
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    fakes.dialogs.answerWith("region", { start: 2, end: 2, type: "bytes" });
    await controller.dispatch({ type: "regionTypeMarked", regionType: "bytes", rowIndex: 2 });
    await controller.settle();
    expect(controller.state.selection).toEqual(undefined);
  });

  it("confirms a change that rewrites the whole bank", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("region", { start: 0, end: 0x3fff, type: "skip" });
    await controller.dispatch({ type: "regionRequested", rowIndex: 0 });
    await controller.settle();
    expect(fakes.nativeConfirm).toHaveBeenCalledWith(WHOLE_BANK_CONFIRM_MESSAGE);
  });

  it("applies nothing when the whole-bank change is refused", async () => {
    const controller = await opened();
    fakes.nativeConfirm.mockReturnValue(false);
    fakes.dialogs.answerWith("region", { start: 0, end: 0x3fff, type: "skip" });
    await controller.dispatch({ type: "regionRequested", rowIndex: 0 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(false);
  });

  it("does not ask about a change that is not the whole bank", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("region", { start: 0, end: 0x3ffe, type: "skip" });
    await controller.dispatch({ type: "regionRequested", rowIndex: 0 });
    await controller.settle();
    expect(fakes.nativeConfirm).not.toHaveBeenCalled();
  });
});

describe("the Regions list", () => {
  it("hands the dialog the bank's regions, bytes and the active offset", async () => {
    const controller = await opened({}, { bankBytes: [9, 8, 7] });
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    fakes.dialogs.answerWith("manageRegions", undefined);
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();

    expect(fakes.dialogs.callsTo("manageRegions")[0]).toMatchObject({
      activeOffset: 2,
      bytes: [9, 8, 7]
    });
  });

  it("navigates on Go To, relative to the display offset", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    fakes.dialogs.answerWith("manageRegions", {
      action: "go-to",
      region: { start: 0x100, end: 0x1ff, type: "bytes" }
    });
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    expect(fakes.navigateToAddress).toHaveBeenCalledWith(0x4100);
  });

  it("reverts a region straight back to disassembly", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    fakes.dialogs.answerWith("manageRegions", {
      action: "revert",
      region: { start: 0, end: 0x10, type: "bytes" }
    });
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    // --- No region dialog in between: revert has no question to ask.
    expect(fakes.dialogs.callsTo("region")).toEqual([]);
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.regions[0]).toMatchObject({
      type: "disassemble"
    });
  });

  it("opens the region dialog to edit a listed region", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    fakes.dialogs.answerWith("manageRegions", {
      action: "edit",
      region: { start: 0x10, end: 0x20, type: "bytes" }
    });
    fakes.dialogs.answerWith("region", undefined);
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("region")[0]).toMatchObject({
      initialStart: 0x10,
      initialEnd: 0x20,
      // --- Editing opens on the region's own type.
      initialType: "bytes"
    });
  });

  it("splits at the active row when it falls inside the region", async () => {
    const controller = await opened({}, { items: [aRow(0), aRow(1), aRow(2, { byteLength: 2 })] });
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    fakes.dialogs.answerWith("manageRegions", {
      action: "split",
      region: { start: 0, end: 0x10, type: "bytes" }
    });
    fakes.dialogs.answerWith("region", undefined);
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    // --- Two bytes at offset 2, so the split covers 2..3, and opens on the *other* type.
    expect(fakes.dialogs.callsTo("region")[0]).toMatchObject({
      initialStart: 2,
      initialEnd: 3,
      initialType: "disassemble"
    });
  });

  it("does nothing without an active row to work from", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("manageRegions")).toEqual([]);
  });
});

describe("clearing row annotations", () => {
  it("removes the comments covering the row and resets its region", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [
              { start: 0, end: 2, type: "bytes" },
              { start: 3, end: 0x3fff, type: "disassemble" }
            ],
            lineAnnotations: { "1": { comment: "note" } }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    await controller.dispatch({ type: "rowAnnotationsCleared", rowIndex: 1 });
    await controller.settle();

    const bank = publishedBank(fakes.session, SIDECAR, BANK);
    expect(bank?.lineAnnotations).toEqual(undefined);
    // --- A row marked as bytes is still annotated once its comment is gone, so "clear" puts the
    // --- span back to disassembly too — but only *that row's* span. The rest of the enclosing
    // --- `bytes` region is somebody else's annotation and is split around it, not swallowed.
    expect(bank?.regions).toEqual([
      { start: 0, end: 0, type: "bytes" },
      { start: 1, end: 1, type: "disassemble" },
      { start: 2, end: 2, type: "bytes" },
      { start: 3, end: 0x3fff, type: "disassemble" }
    ]);
  });

  it("publishes nothing when there was nothing to clear", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowAnnotationsCleared", rowIndex: 1 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(false);
  });
});

describe("closing", () => {
  it("allows the close outright when there is nothing to lose", async () => {
    const controller = await opened();
    await expect(controller.confirmDisposal()).resolves.toEqual(true);
    expect(fakes.nativeConfirm).not.toHaveBeenCalled();
  });

  it("allows the close after an ordinary edit, which is already on disk", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "x" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 0 });
    await controller.settle();
    await fakes.session.writesSettled();

    await expect(controller.confirmDisposal()).resolves.toEqual(true);
    expect(fakes.nativeConfirm).not.toHaveBeenCalled();
  });

  it("asks only when the sidecar could not be written, and refuses when told to", async () => {
    const controller = await opened();
    fakes.session.writeError = "EACCES: read-only";
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "x" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 0 });
    await controller.settle();
    await fakes.session.writesSettled();

    fakes.nativeConfirm.mockReturnValue(false);
    await expect(controller.confirmDisposal()).resolves.toEqual(false);
    // --- The question names the reason: "unsaved changes" would be a puzzle with no Save.
    expect(fakes.nativeConfirm).toHaveBeenCalledWith(
      `${SIDECAR} could not be written (EACCES: read-only).\n\n` +
        "Closing this bank discards the annotation changes it still holds. Close anyway?"
    );
  });
});

describe("lifecycle", () => {
  it("unsubscribes from the session on dispose", async () => {
    const controller = await opened();
    controller.dispose();
    expect(fakes.session.unsubscribeCount).toEqual(1);
  });

  it("comes back alive and re-subscribed after a StrictMode teardown", async () => {
    // --- React runs every effect setup → cleanup → setup in development. A controller that could
    // --- only be disposed would return deaf to the session. Trap 1 in `.ai/ui-mvc-guide.md`.
    const controller = await opened();
    controller.dispose();
    controller.activate();

    expect(controller.isDisposed).toEqual(false);
    expect(fakes.session.subscribeCalls.length).toEqual(2);

    // --- And it still works.
    await controller.dispatch({ type: "rowSelected", index: 1, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 1, activeIndex: 1 });
  });

  it("ignores intents after disposal", async () => {
    const controller = await opened();
    controller.dispose();
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    expect(controller.state.selection).toEqual(undefined);
  });
});

describe("go to definition", () => {
  /** An editor whose sidecar carries a label in this bank and one beyond it. */
  async function withLabels(env: Partial<NexAnnotationEditorEnvironment>, operandValue: number) {
    const session = new FakeSession({ annotations: anAnnotationModelWithLabels() });
    return opened(env, {
      session,
      items: [aLabelledOperandRow(0x0010, operandValue)]
    });
  }

  it("scrolls this document for a definition in the bank on screen", async () => {
    const controller = await withLabels({}, 0x4100);
    await controller.dispatch({ type: "goToDefinitionRequested", rowIndex: 0 });
    await controller.settle();

    expect(fakes.navigateToAddress).toHaveBeenCalledWith(0x4100);
    expect(fakes.revealAddressInBank).not.toHaveBeenCalled();
  });

  it("brings the other bank forward when the machine is running", async () => {
    const controller = await withLabels({ machineRunning: true }, 0xc100);
    await controller.dispatch({ type: "goToDefinitionRequested", rowIndex: 0 });
    await controller.settle();

    expect(fakes.revealAddressInBank).toHaveBeenCalledWith(0xc100);
    expect(fakes.navigateToAddress).not.toHaveBeenCalled();
  });

  it("does nothing for another bank with the machine stopped", async () => {
    /*
     * The menu greys this, but the check is repeated here on purpose: a context menu can be left
     * open while the machine stops underneath it, and the stale click must not reach a jump whose
     * destination can no longer be resolved.
     */
    const controller = await withLabels({ machineRunning: false }, 0xc100);
    await controller.dispatch({ type: "goToDefinitionRequested", rowIndex: 0 });
    await controller.settle();

    expect(fakes.revealAddressInBank).not.toHaveBeenCalled();
    expect(fakes.navigateToAddress).not.toHaveBeenCalled();
  });

  it("does nothing on a row whose operand names no label", async () => {
    const controller = await withLabels({ machineRunning: true }, 0x4999);
    await controller.dispatch({ type: "goToDefinitionRequested", rowIndex: 0 });
    await controller.settle();

    expect(fakes.navigateToAddress).not.toHaveBeenCalled();
    expect(fakes.revealAddressInBank).not.toHaveBeenCalled();
  });
});
