import { describe, it, expect, beforeEach } from "vitest";

import { NexAnnotationEditorController } from "@renderer/appIde/DocumentPanels/Next/annotationEditor/NexAnnotationEditorController";
import type { NexAnnotationEditorEnvironment } from "@renderer/appIde/DocumentPanels/Next/annotationEditor/NexAnnotationEditorModel";
import { WHOLE_BANK_CONFIRM_MESSAGE } from "@renderer/appIde/DocumentPanels/Next/annotationEditor/NexAnnotationEditorViewModel";

import type { DisassemblyItem } from "@renderer/appIde/disassemblers/common-types";

import { createFakePorts, FakeSession, publishedBank, type FakePorts } from "./fakes";
import {
  aListing,
  anAnnotationModel,
  anEnvironment,
  anOperandRow,
  aRow,
  BANK,
  SIDECAR
} from "./fixtures";

/*
 * Journey tests: every flow driven by dispatching intents against fakes, with no React and no DOM.
 *
 * `settle()` drains follow-up work transitively, so a handler that starts more work — a dialog whose
 * result triggers a publish, whose snapshot regenerates the listing — is fully awaited.
 */

let fakes: FakePorts;

function open(
  env: Partial<NexAnnotationEditorEnvironment> = {},
  options: Parameters<typeof createFakePorts>[0] & { items?: DisassemblyItem[] } = {}
) {
  const { items, ...portOptions } = options;
  fakes = createFakePorts(portOptions);
  const controller = new NexAnnotationEditorController(fakes.ports, anEnvironment(env));
  return { controller, items: items ?? aListing(6) };
}

/**
 * An opened editor with a listing already reported.
 *
 * The listing is generated by the component around the editor — a dump with no sidecar still
 * disassembles — so it arrives as an intent rather than being fetched.
 */
async function opened(
  env: Partial<NexAnnotationEditorEnvironment> = {},
  options: Parameters<typeof createFakePorts>[0] & { items?: DisassemblyItem[] } = {}
) {
  const { controller, items } = open(env, options);
  await controller.dispatch({ type: "opened" });
  await controller.dispatch({ type: "listingChanged", items });
  await controller.settle();
  return controller;
}

beforeEach(() => {
  fakes = createFakePorts();
});

describe("opening", () => {
  it("subscribes to the session for its own sidecar and bank", async () => {
    const controller = await opened();
    expect(fakes.session.subscribeCalls).toEqual([{ path: SIDECAR, bank: BANK }]);
    expect(controller.state.annotations).toBeDefined();
  });

  it("takes the listing the surrounding component reports", async () => {
    const controller = await opened();
    expect(controller.state.items.length).toEqual(6);
  });

  it("hands the loaded model out for the listing to be generated from", async () => {
    // --- The editor does not generate the listing; it publishes the model the component needs.
    const controller = await opened();
    expect(controller.viewModel.annotations).toBe(controller.state.annotations);
  });

  it("does not subscribe for a document with no sidecar", async () => {
    await opened({ annotationPath: undefined });
    expect(fakes.session.subscribeCalls).toEqual([]);
  });

  it("reports a sidecar that failed to load, and offers no model to annotate by", async () => {
    const session = new FakeSession({ annotations: undefined, loadError: "bad json" });
    const controller = await opened({}, { session });
    expect(controller.state.loadError).toEqual("bad json");
    expect(controller.viewModel.annotations).toEqual(undefined);
  });

  it("still holds the rows of an unannotated dump", async () => {
    // --- A popped-out loading screen has no sidecar but still disassembles, and the editor needs
    // --- those rows: selection works, even though every editing action is disabled.
    const session = new FakeSession({ annotations: undefined });
    const controller = await opened({ annotationPath: undefined }, { session });
    expect(controller.state.items.length).toEqual(6);
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 2, activeIndex: 2 });
    expect(controller.viewModel.menu.every((entry) => entry.kind === "separator" || entry.disabled))
      .toEqual(true);
  });
});

describe("the environment changing", () => {
  it("re-subscribes when the bank changes", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "environmentChanged", env: anEnvironment({ bank: 6 }) });
    await controller.settle();
    expect(fakes.session.subscribeCalls).toEqual([
      { path: SIDECAR, bank: BANK },
      { path: SIDECAR, bank: 6 }
    ]);
    expect(fakes.session.unsubscribeCount).toEqual(1);
  });

  it("does nothing at all for an unchanged environment", async () => {
    const controller = await opened();
    const before = controller.state;
    await controller.dispatch({ type: "environmentChanged", env: anEnvironment() });
    await controller.settle();
    // --- The same state object: the container derives the environment fresh on every render.
    expect(controller.state).toBe(before);
  });

  it("persists a changed display setting into the sidecar", async () => {
    const controller = await opened();
    await controller.dispatch({
      type: "environmentChanged",
      env: anEnvironment({ decimalView: true })
    });
    await controller.settle();
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.decimalView).toEqual(true);
  });

  it("does not dirty the sidecar for settings that came out of it", async () => {
    // --- The document opens on the settings the sidecar remembers, so the first environment push
    // --- must not look like an edit.
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: { [String(BANK)]: { offsetIndex: 1, decimalView: true, regions: [] } }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({ decimalView: true }, { session });
    await controller.dispatch({
      type: "environmentChanged",
      env: anEnvironment({ decimalView: true, viewMode: "memory" })
    });
    await controller.settle();
    // --- `viewMode` did change, so that one *is* an edit; `decimalView` alone would not have been.
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.decimalView).toEqual(true);
  });
});

describe("selection", () => {
  it("anchors a plain click on the clicked row", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 3, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 3, activeIndex: 3 });
  });

  it("keeps the anchor when a click extends the range", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 1, extend: false });
    await controller.dispatch({ type: "rowSelected", index: 4, extend: true });
    expect(controller.state.selection).toEqual({ anchorIndex: 1, activeIndex: 4 });
  });

  it("moves the active row, clamped to the listing", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    await controller.dispatch({ type: "selectionMoved", delta: 2, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 2, activeIndex: 2 });

    // --- Six rows, so index 5 is the last.
    await controller.dispatch({ type: "selectionMoved", delta: 100, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 5, activeIndex: 5 });

    await controller.dispatch({ type: "selectionMoved", delta: -100, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 0, activeIndex: 0 });
  });

  it("extends from the anchor when moving with shift", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    await controller.dispatch({ type: "selectionMoved", delta: 2, extend: true });
    expect(controller.state.selection).toEqual({ anchorIndex: 2, activeIndex: 4 });
  });

  it("does nothing with an empty listing", async () => {
    const controller = await opened({}, { items: [] });
    await controller.dispatch({ type: "selectionMoved", delta: 1, extend: false });
    expect(controller.state.selection).toEqual(undefined);
  });
});

describe("saving", () => {
  it("writes the sidecar and clears the dirty flag through the session", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "entry" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 0 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(true);

    await controller.dispatch({ type: "saveRequested" });
    await controller.settle();
    expect(fakes.session.saveCalls).toEqual([SIDECAR]);
    expect(controller.state.dirty).toEqual(false);
  });

  it("keeps the edits dirty and reports why when the write fails", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "entry" });
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 0 });
    await controller.settle();

    fakes.session.saveError = new Error("read-only");
    await controller.dispatch({ type: "saveRequested" });
    await controller.settle();

    expect(controller.state.saveError).toEqual("read-only");
    expect(controller.state.dirty).toEqual(true);
  });

  it("does not write without a loaded model", async () => {
    const session = new FakeSession({ annotations: undefined });
    const controller = await opened({}, { session });
    await controller.dispatch({ type: "saveRequested" });
    await controller.settle();
    expect(fakes.session.saveCalls).toEqual([]);
  });

  it("reports the dirty flag outward, and only when it changes", async () => {
    const controller = await opened();
    expect(fakes.dirtyChanged).not.toHaveBeenCalled();

    fakes.dialogs.answerWith("synopsisComment", { synopsis: "a" });
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 0 });
    await controller.settle();
    expect(fakes.dirtyChanged).toHaveBeenCalledWith(true);

    fakes.dirtyChanged.mockClear();
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "b" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 1 });
    await controller.settle();
    // --- Still dirty: no news.
    expect(fakes.dirtyChanged).not.toHaveBeenCalled();
  });
});

describe("comments", () => {
  it("writes a synopsis comment at the row's own offset", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "the entry point" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 2 });
    await controller.settle();

    expect(fakes.dialogs.callsTo("synopsisComment")[0]).toMatchObject({ bankOffset: 2 });
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.lineAnnotations).toEqual({
      "2": { synopsis: "the entry point" }
    });
  });

  it("offers the existing comment as the dialog's starting value", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            lineAnnotations: { "2": { comment: "old" } }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    fakes.dialogs.answerWith("endOfLineComment", undefined);
    await controller.dispatch({ type: "endOfLineCommentRequested", rowIndex: 2 });
    await controller.settle();
    expect(fakes.dialogs.callsTo("endOfLineComment")[0]).toMatchObject({ initialComment: "old" });
  });

  it("changes nothing when the dialog is dismissed", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", undefined);
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 2 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(false);
  });

  it("clears the comment when the dialog returns an empty one", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "x" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 2 });
    await controller.settle();

    fakes.dialogs.answerWith("synopsisComment", { synopsis: undefined });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 2 });
    await controller.settle();
    // --- An emptied annotation is removed rather than stored as `{}`.
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.lineAnnotations).toEqual(undefined);
  });

  it("acts on the selection when no row is named", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 4, extend: false });
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "from the toolbar" });
    await controller.dispatch({ type: "synopsisCommentRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("synopsisComment")[0]).toMatchObject({ bankOffset: 4 });
  });

  it("does nothing with neither a row nor a selection", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "synopsisCommentRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("synopsisComment")).toEqual([]);
  });
});

describe("labels", () => {
  it("opens the dialog on the chosen scope, with both candidate values", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("label", undefined);
    await controller.dispatch({ type: "labelRequested", scope: "global", rowIndex: 2 });
    await controller.settle();

    expect(fakes.dialogs.callsTo("label")[0]).toMatchObject({
      bank: BANK,
      initialScope: "global",
      // --- A global label names a 16-bit address; a local one the bank-relative offset.
      initialGlobalValue: 0x4002,
      initialLocalValue: 2
    });
  });

  it("saves a global label", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("label", {
      action: "save",
      scope: "global",
      name: "Start",
      value: 0x4002
    });
    await controller.dispatch({ type: "labelRequested", scope: "global", rowIndex: 2 });
    await controller.settle();

    const annotations = fakes.session.snapshotFor(SIDECAR).annotations;
    expect(annotations?.globalLabels).toEqual([{ name: "Start", value: 0x4002 }]);
  });

  it("saves a local label onto its own bank", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("label", {
      action: "save",
      scope: "local",
      name: "Loop",
      value: 2
    });
    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.localLabels).toEqual([
      { name: "Loop", value: 2 }
    ]);
  });

  it("confirms every delete before applying it", async () => {
    const controller = await opened();
    const label = { scope: "local" as const, name: "Loop", value: 2 };
    fakes.dialogs.answerWith("label", { action: "delete", ...label, originalLabel: label });

    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();

    expect(fakes.confirm).toHaveBeenCalledTimes(1);
    expect(fakes.confirm.mock.calls[0][0]).toMatchObject({
      title: "Delete label",
      code: "Loop",
      danger: true
    });
  });

  it("applies nothing when the delete is refused", async () => {
    const controller = await opened();
    const label = { scope: "local" as const, name: "Loop", value: 2 };
    fakes.dialogs.answerWith("label", { action: "delete", ...label, originalLabel: label });
    fakes.confirm.mockResolvedValue(false);

    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(false);
  });

  it("counts the operand references a delete would clear", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            localLabels: [{ name: "Loop", value: 2 }],
            operandReferences: {
              "0": [{ operandIndex: 0, scope: "local", name: "Loop" }],
              "1": [{ operandIndex: 0, scope: "local", name: "Loop" }]
            }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    const label = { scope: "local" as const, name: "Loop", value: 2 };
    fakes.dialogs.answerWith("label", { action: "delete", ...label, originalLabel: label });

    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();

    expect(fakes.confirm.mock.calls[0][0].linesAfterCode).toEqual([
      "2 operand references to it will be cleared."
    ]);
    // --- And the references go with the label.
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.operandReferences).toEqual(undefined);
  });

  it("refuses a delete that names nothing to remove", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("label", {
      action: "delete",
      scope: "local",
      name: "Loop",
      value: 2
    });
    await controller.dispatch({ type: "labelRequested", scope: "local", rowIndex: 2 });
    await controller.settle();
    expect(fakes.confirm).not.toHaveBeenCalled();
    expect(controller.state.dirty).toEqual(false);
  });
});

describe("the Labels list", () => {
  it("hands the dialog the bank's labels, with reference counts", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        globalLabels: [{ name: "Start", value: 0x8000 }],
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            localLabels: [{ name: "Loop", value: 2 }],
            operandReferences: { "0": [{ operandIndex: 0, scope: "local", name: "Loop" }] }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    fakes.dialogs.answerWith("manageLabels", undefined);
    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();

    const args = fakes.dialogs.callsTo("manageLabels")[0];
    expect(args.labels).toEqual([
      { name: "Start", value: 0x8000, scope: "global", referenced: false, referenceCount: 0 },
      { name: "Loop", value: 2, scope: "local", bank: BANK, referenced: true, referenceCount: 1 }
    ]);
  });

  it("stays open across an edit, and hands back the refreshed list", async () => {
    // --- The list is a session, not a question: `onAddLabel` runs while it is still mounted.
    const controller = await opened();
    let refreshed: any[] | undefined;
    fakes.dialogs.answerWith("manageLabels", async (args: any) => {
      fakes.dialogs.answerWith("label", {
        action: "save",
        scope: "global",
        name: "Added",
        value: 0x1234
      });
      refreshed = await args.onAddLabel("global");
      return undefined;
    });

    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();

    expect(refreshed).toEqual([
      { name: "Added", value: 0x1234, scope: "global", referenced: false, referenceCount: 0 }
    ]);
  });

  it("deletes from within the list, confirmation and all", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            localLabels: [{ name: "Loop", value: 2 }]
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    let refreshed: any[] | undefined;
    fakes.dialogs.answerWith("manageLabels", async (args: any) => {
      refreshed = await args.onDeleteLabel({ scope: "local", name: "Loop", value: 2 });
      return undefined;
    });

    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();

    expect(fakes.confirm).toHaveBeenCalledTimes(1);
    expect(refreshed).toEqual([]);
  });

  it("navigates on Go To, which is the one action that closes the list", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("manageLabels", {
      action: "go-to",
      label: { scope: "local", name: "Loop", value: 0x20 }
    });
    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();
    // --- A local label is bank-relative, so the address is the display offset plus it.
    expect(fakes.navigateToAddress).toHaveBeenCalledWith(0x4020);
  });

  it("navigates to a global label's own address", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("manageLabels", {
      action: "go-to",
      label: { scope: "global", name: "Start", value: 0x9000 }
    });
    await controller.dispatch({ type: "manageLabelsRequested" });
    await controller.settle();
    expect(fakes.navigateToAddress).toHaveBeenCalledWith(0x9000);
  });
});

describe("operand labels", () => {
  it("attaches a label to a decoded operand", async () => {
    const controller = await opened({}, { items: [anOperandRow(0), aRow(3)] });
    fakes.dialogs.answerWith("operandLabel", {
      action: "apply",
      operandIndex: 0,
      scope: "global",
      name: "Target"
    });
    await controller.dispatch({ type: "operandLabelRequested", rowIndex: 0 });
    await controller.settle();

    expect(publishedBank(fakes.session, SIDECAR, BANK)?.operandReferences).toEqual({
      "0": [{ operandIndex: 0, scope: "global", name: "Target" }]
    });
  });

  it("creates and attaches in one step", async () => {
    const controller = await opened({}, { items: [anOperandRow(0)] });
    fakes.dialogs.answerWith("operandLabel", {
      action: "create-label",
      operandIndex: 0,
      scope: "local",
      name: "Made",
      value: 0x30
    });
    await controller.dispatch({ type: "operandLabelRequested", rowIndex: 0 });
    await controller.settle();

    const bank = publishedBank(fakes.session, SIDECAR, BANK);
    expect(bank?.localLabels).toEqual([{ name: "Made", value: 0x30 }]);
    expect(bank?.operandReferences?.["0"]).toEqual([
      { operandIndex: 0, scope: "local", name: "Made" }
    ]);
  });

  it("clears a reference without needing a label", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [],
            operandReferences: { "0": [{ operandIndex: 0, scope: "local", name: "Loop" }] }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session, items: [anOperandRow(0)] });
    fakes.dialogs.answerWith("operandLabel", { action: "clear", operandIndex: 0 });
    await controller.dispatch({ type: "operandLabelRequested", rowIndex: 0 });
    await controller.settle();

    expect(publishedBank(fakes.session, SIDECAR, BANK)?.operandReferences).toEqual(undefined);
  });
});

describe("regions", () => {
  it("marks a row through the region dialog", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("region", { start: 2, end: 2, type: "bytes" });
    await controller.dispatch({ type: "regionTypeMarked", regionType: "bytes", rowIndex: 2 });
    await controller.settle();

    // --- The dialog opens on the span the gesture named, and on the type it asked for.
    expect(fakes.dialogs.callsTo("region")[0]).toMatchObject({
      initialStart: 2,
      initialEnd: 2,
      initialType: "bytes"
    });
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.regions).toEqual([
      { start: 0, end: 1, type: "disassemble" },
      { start: 2, end: 2, type: "bytes" },
      { start: 3, end: 0x3fff, type: "disassemble" }
    ]);
  });

  it("marks the whole selection when the row is inside it", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 1, extend: false });
    await controller.dispatch({ type: "rowSelected", index: 3, extend: true });
    fakes.dialogs.answerWith("region", (args: any) => ({
      start: args.initialStart,
      end: args.initialEnd,
      type: "words"
    }));
    await controller.dispatch({ type: "regionTypeMarked", regionType: "words", rowIndex: 2 });
    await controller.settle();
    expect(fakes.dialogs.callsTo("region")[0]).toMatchObject({ initialStart: 1, initialEnd: 3 });
  });

  it("clears the selection once a region is applied", async () => {
    // --- The listing is about to change shape, so the selection it was made against is stale.
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    fakes.dialogs.answerWith("region", { start: 2, end: 2, type: "bytes" });
    await controller.dispatch({ type: "regionTypeMarked", regionType: "bytes", rowIndex: 2 });
    await controller.settle();
    expect(controller.state.selection).toEqual(undefined);
  });

  it("confirms a change that rewrites the whole bank", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("region", { start: 0, end: 0x3fff, type: "skip" });
    await controller.dispatch({ type: "regionRequested", rowIndex: 0 });
    await controller.settle();
    expect(fakes.nativeConfirm).toHaveBeenCalledWith(WHOLE_BANK_CONFIRM_MESSAGE);
  });

  it("applies nothing when the whole-bank change is refused", async () => {
    const controller = await opened();
    fakes.nativeConfirm.mockReturnValue(false);
    fakes.dialogs.answerWith("region", { start: 0, end: 0x3fff, type: "skip" });
    await controller.dispatch({ type: "regionRequested", rowIndex: 0 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(false);
  });

  it("does not ask about a change that is not the whole bank", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("region", { start: 0, end: 0x3ffe, type: "skip" });
    await controller.dispatch({ type: "regionRequested", rowIndex: 0 });
    await controller.settle();
    expect(fakes.nativeConfirm).not.toHaveBeenCalled();
  });
});

describe("the Regions list", () => {
  it("hands the dialog the bank's regions, bytes and the active offset", async () => {
    const controller = await opened({}, { bankBytes: [9, 8, 7] });
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    fakes.dialogs.answerWith("manageRegions", undefined);
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();

    expect(fakes.dialogs.callsTo("manageRegions")[0]).toMatchObject({
      activeOffset: 2,
      bytes: [9, 8, 7]
    });
  });

  it("navigates on Go To, relative to the display offset", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    fakes.dialogs.answerWith("manageRegions", {
      action: "go-to",
      region: { start: 0x100, end: 0x1ff, type: "bytes" }
    });
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    expect(fakes.navigateToAddress).toHaveBeenCalledWith(0x4100);
  });

  it("reverts a region straight back to disassembly", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    fakes.dialogs.answerWith("manageRegions", {
      action: "revert",
      region: { start: 0, end: 0x10, type: "bytes" }
    });
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    // --- No region dialog in between: revert has no question to ask.
    expect(fakes.dialogs.callsTo("region")).toEqual([]);
    expect(publishedBank(fakes.session, SIDECAR, BANK)?.regions[0]).toMatchObject({
      type: "disassemble"
    });
  });

  it("opens the region dialog to edit a listed region", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowSelected", index: 0, extend: false });
    fakes.dialogs.answerWith("manageRegions", {
      action: "edit",
      region: { start: 0x10, end: 0x20, type: "bytes" }
    });
    fakes.dialogs.answerWith("region", undefined);
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("region")[0]).toMatchObject({
      initialStart: 0x10,
      initialEnd: 0x20,
      // --- Editing opens on the region's own type.
      initialType: "bytes"
    });
  });

  it("splits at the active row when it falls inside the region", async () => {
    const controller = await opened({}, { items: [aRow(0), aRow(1), aRow(2, { byteLength: 2 })] });
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    fakes.dialogs.answerWith("manageRegions", {
      action: "split",
      region: { start: 0, end: 0x10, type: "bytes" }
    });
    fakes.dialogs.answerWith("region", undefined);
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    // --- Two bytes at offset 2, so the split covers 2..3, and opens on the *other* type.
    expect(fakes.dialogs.callsTo("region")[0]).toMatchObject({
      initialStart: 2,
      initialEnd: 3,
      initialType: "disassemble"
    });
  });

  it("does nothing without an active row to work from", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "manageRegionsRequested" });
    await controller.settle();
    expect(fakes.dialogs.callsTo("manageRegions")).toEqual([]);
  });
});

describe("clearing row annotations", () => {
  it("removes the comments covering the row and resets its region", async () => {
    const session = new FakeSession({
      annotations: {
        schemaVersion: 1,
        banks: {
          [String(BANK)]: {
            offsetIndex: 1,
            regions: [
              { start: 0, end: 2, type: "bytes" },
              { start: 3, end: 0x3fff, type: "disassemble" }
            ],
            lineAnnotations: { "1": { comment: "note" } }
          }
        }
      },
      dirty: false,
      loading: false
    });
    const controller = await opened({}, { session });
    await controller.dispatch({ type: "rowAnnotationsCleared", rowIndex: 1 });
    await controller.settle();

    const bank = publishedBank(fakes.session, SIDECAR, BANK);
    expect(bank?.lineAnnotations).toEqual(undefined);
    // --- A row marked as bytes is still annotated once its comment is gone, so "clear" puts the
    // --- span back to disassembly too — but only *that row's* span. The rest of the enclosing
    // --- `bytes` region is somebody else's annotation and is split around it, not swallowed.
    expect(bank?.regions).toEqual([
      { start: 0, end: 0, type: "bytes" },
      { start: 1, end: 1, type: "disassemble" },
      { start: 2, end: 2, type: "bytes" },
      { start: 3, end: 0x3fff, type: "disassemble" }
    ]);
  });

  it("publishes nothing when there was nothing to clear", async () => {
    const controller = await opened();
    await controller.dispatch({ type: "rowAnnotationsCleared", rowIndex: 1 });
    await controller.settle();
    expect(controller.state.dirty).toEqual(false);
  });
});

describe("closing", () => {
  it("allows the close outright when nothing is unsaved", async () => {
    const controller = await opened();
    await expect(controller.confirmDisposal()).resolves.toEqual(true);
    expect(fakes.nativeConfirm).not.toHaveBeenCalled();
  });

  it("asks before discarding unsaved edits, and refuses when told to", async () => {
    const controller = await opened();
    fakes.dialogs.answerWith("synopsisComment", { synopsis: "x" });
    await controller.dispatch({ type: "synopsisCommentRequested", rowIndex: 0 });
    await controller.settle();

    fakes.nativeConfirm.mockReturnValue(false);
    await expect(controller.confirmDisposal()).resolves.toEqual(false);
    expect(fakes.nativeConfirm).toHaveBeenCalledWith(
      `Discard unsaved annotation changes in ${SIDECAR}?`
    );
  });
});

describe("lifecycle", () => {
  it("unsubscribes from the session on dispose", async () => {
    const controller = await opened();
    controller.dispose();
    expect(fakes.session.unsubscribeCount).toEqual(1);
  });

  it("comes back alive and re-subscribed after a StrictMode teardown", async () => {
    // --- React runs every effect setup → cleanup → setup in development. A controller that could
    // --- only be disposed would return deaf to the session. Trap 1 in `.ai/ui-mvc-guide.md`.
    const controller = await opened();
    controller.dispose();
    controller.activate();

    expect(controller.isDisposed).toEqual(false);
    expect(fakes.session.subscribeCalls.length).toEqual(2);

    // --- And it still works.
    await controller.dispatch({ type: "rowSelected", index: 1, extend: false });
    expect(controller.state.selection).toEqual({ anchorIndex: 1, activeIndex: 1 });
  });

  it("ignores intents after disposal", async () => {
    const controller = await opened();
    controller.dispose();
    await controller.dispatch({ type: "rowSelected", index: 2, extend: false });
    expect(controller.state.selection).toEqual(undefined);
  });
});
