export default {
  "project-explorer": "The Project Explorer",
  "editing-code": "Editing Code",
  navigation: "Navigating Back and Forward",
  "run-debug": "Running & Debugging Code",
  "exporting-code": "Exporting Code",
  zxb: "ZXBASIC Integration",
  sjasmp: "SJASMPLUS Integration",
  pasta80: "PASTA/80 Integration",
  settings: "Settings",
  "ide-settings": { display: "hidden" },
  cpu: "The CPU View",
  ula: "The ULA View",
  copper: "The Copper View",
  "sprite-inspector": "The Sprite Inspector",
  "tilemap-inspector": "The Tilemap Inspector",
  "layer2-inspector": "The Layer 2 Inspector",
  layers: "Video Layers",
  "beam-position": "The Beam Position",
  "execution-history": "The Execution History",
  "reverse-debugging": "Reverse Debugging",
  "code-coverage": "Code Coverage and the Heat Map",
  memory: "The Memory View",
  disassembly: "The Disassembly View",
  watch: "Watch Expressions",
  breakpoints: "The Breakpoints View",
  "system-vars": "The System Variables View",
  basic: "The BASIC Listing",
  commands: "Interactive Commands",
  "build-system": "The Build System"
};
