import type { UiReducer } from "@mvc/core/types";
import type { DisassemblyItem } from "@renderer/appIde/disassemblers/common-types";

import type {
  NexAnnotationBankView,
  NexAnnotationOffsetIndex,
  NexFileAnnotations
} from "../nexAnnotations";
import { getNexBankOffsetIndex } from "../nexAnnotations";
import type { NexAnnotationSessionSnapshot } from "./NexAnnotationEditorPorts";

// ─── Vocabulary ──────────────────────────────────────────────────────────────

/**
 * What the editor reads from outside itself: which bank of which sidecar it is editing, and how that
 * bank is currently displayed.
 *
 * Pushed in as data, so no layer below the container needs to know the document hub or Redux exists.
 * `annotationPath` absent means this document is not annotated at all — a plain memory dump of a
 * loading screen, say — and every editing affordance is unavailable.
 */
export type NexAnnotationEditorEnvironment = {
  annotationPath?: string;
  bank?: number;
  /** Which view the document is showing; the sidecar remembers it as the bank's `lastView`. */
  viewMode: NexAnnotationBankView;
  decimalView: boolean;
  disassOffset: number;
};

/**
 * The rows a gesture is acting on.
 *
 * `anchorIndex` is where the selection started and `activeIndex` where it now ends; either order is
 * legal, because a range can be dragged upwards. The editor stores the pair rather than a normalized
 * span so that extending a selection knows which end to move.
 */
export type NexAnnotationSelection = {
  anchorIndex: number;
  activeIndex: number;
};

/** What a menu was opened on: a specific row, or the current selection. */
export type NexAnnotationContextTarget = {
  rowIndex: number;
  /** True when the gesture named a range rather than a single row. */
  isRange: boolean;
};

/**
 * Which asynchronous job is in flight.
 *
 * Only saving: the listing is generated by the component around the editor, because it has a second
 * path the editor knows nothing about — a dump with no sidecar still disassembles, plainly.
 */
export const NO_ANNOTATIONS_MESSAGE = "This bank has no annotation sidecar.";

// ─── State ───────────────────────────────────────────────────────────────────

export type NexAnnotationEditorState = {
  env: NexAnnotationEditorEnvironment;
  annotations?: NexFileAnnotations;
  loading: boolean;
  loadError?: string;
  saveError?: string;
  dirty: boolean;
  /** The generated listing for the current annotations, or `[]` when there is none. */
  items: DisassemblyItem[];
  selection?: NexAnnotationSelection;
  contextTarget?: NexAnnotationContextTarget;
};

export function initialState(env: NexAnnotationEditorEnvironment): NexAnnotationEditorState {
  return {
    env,
    loading: false,
    dirty: false,
    items: []
  };
}

// ─── Events ──────────────────────────────────────────────────────────────────

export type NexAnnotationEditorEvent =
  | { type: "envReplaced"; env: NexAnnotationEditorEnvironment }
  // --- The shared session reported a new snapshot: annotations, dirty flag, or an error.
  | { type: "sessionSnapshotReceived"; snapshot: NexAnnotationSessionSnapshot }
  // --- The listing the surrounding component generated, annotated or plain.
  | { type: "listingSettled"; items: DisassemblyItem[] }
  | { type: "selectionChanged"; selection: NexAnnotationSelection }
  | { type: "selectionCleared" }
  | { type: "contextTargetChanged"; target: NexAnnotationContextTarget }
  | { type: "contextTargetCleared" };

// ─── Reducer ─────────────────────────────────────────────────────────────────

export const reduce: UiReducer<NexAnnotationEditorState, NexAnnotationEditorEvent> = (
  state,
  event
) => {
  switch (event.type) {
    case "envReplaced": {
      // --- An unrelated view-state write reaches the container as a fresh object; ignoring an
      // --- equal one here is what stops a re-render loop (trap 4 in `.ai/ui-mvc-guide.md`).
      if (sameEnvironment(state.env, event.env)) return state;
      // --- Moving to a different bank or sidecar invalidates the selection: the row indices meant
      // --- positions in the *old* listing.
      const rebased = state.env.bank !== event.env.bank ||
        state.env.annotationPath !== event.env.annotationPath;
      return {
        ...state,
        env: event.env,
        selection: rebased ? undefined : state.selection,
        contextTarget: rebased ? undefined : state.contextTarget
      };
    }

    case "sessionSnapshotReceived": {
      const { snapshot } = event;
      if (
        state.annotations === snapshot.annotations &&
        state.dirty === snapshot.dirty &&
        state.loading === snapshot.loading &&
        state.loadError === snapshot.loadError &&
        state.saveError === snapshot.saveError
      ) {
        // --- The session broadcasts to every subscriber of a sidecar, so an unchanged snapshot
        // --- arrives whenever a *sibling* bank document edits something in another bank.
        return state;
      }
      return {
        ...state,
        annotations: snapshot.annotations,
        dirty: snapshot.dirty,
        loading: snapshot.loading,
        loadError: snapshot.loadError,
        saveError: snapshot.saveError
      };
    }

    case "listingSettled":
      if (state.items === event.items) return state;
      return {
        ...state,
        items: event.items,
        // --- A regenerated listing can be shorter than the one the selection was made against.
        selection: clampSelection(state.selection, event.items.length),
        contextTarget: clampContextTarget(state.contextTarget, event.items.length)
      };

    case "selectionChanged":
      return sameSelection(state.selection, event.selection)
        ? state
        : { ...state, selection: event.selection };

    case "selectionCleared":
      return state.selection === undefined && state.contextTarget === undefined
        ? state
        : { ...state, selection: undefined, contextTarget: undefined };

    case "contextTargetChanged":
      return { ...state, contextTarget: event.target };

    case "contextTargetCleared":
      return state.contextTarget === undefined ? state : { ...state, contextTarget: undefined };
  }
};

// ─── Derivations shared by the controller and the view model ─────────────────

/** Are annotations available to edit at all? */
export function isAnnotationEnabled(state: NexAnnotationEditorState): boolean {
  return (
    !!state.env.annotationPath && state.env.bank !== undefined && !!state.annotations
  );
}

/**
 * The selection as an inclusive, ordered row span.
 *
 * `undefined` when nothing is selected. Every range-taking action goes through this rather than
 * comparing the anchor and active indices itself.
 */
export function selectedRange(
  state: NexAnnotationEditorState
): { start: number; end: number } | undefined {
  const selection = state.selection;
  if (!selection) return undefined;
  return {
    start: Math.min(selection.anchorIndex, selection.activeIndex),
    end: Math.max(selection.anchorIndex, selection.activeIndex)
  };
}

/**
 * The rows an action should apply to, given the row a gesture named.
 *
 * A menu opened on a row *inside* the current selection acts on the whole selection — that is what
 * makes "mark as bytes" work on a dragged range. A menu opened elsewhere acts on that row alone,
 * and re-anchors the selection there.
 */
export function actionRange(
  state: NexAnnotationEditorState,
  rowIndex: number | undefined
): { start: number; end: number } | undefined {
  const range = selectedRange(state);
  if (rowIndex === undefined) return range;
  if (range && rowIndex >= range.start && rowIndex <= range.end) return range;
  return { start: rowIndex, end: rowIndex };
}

/**
 * The bank-relative offset span the rows of `range` cover, from the listing's own metadata.
 *
 * Taken as min/max over the *annotated* rows in the range, not from its boundary rows: a synopsis
 * comment is rendered as a prefix row carrying no annotation of its own, so a range that starts or
 * ends on one would otherwise have no offset at all.
 */
export function offsetSpanOf(
  state: NexAnnotationEditorState,
  range: { start: number; end: number } | undefined
): { start: number; end: number } | undefined {
  if (!range) return undefined;
  const annotated = state.items
    .slice(range.start, range.end + 1)
    .map((item) => item.annotation)
    .filter((annotation) => annotation?.bankOffset !== undefined);
  if (annotated.length === 0) return undefined;
  return {
    start: Math.min(...annotated.map((annotation) => annotation!.bankOffset)),
    // --- Inclusive of the last row's bytes, so marking a range covers all of it.
    end: Math.max(
      ...annotated.map(
        (annotation) => annotation!.bankOffset + Math.max(1, annotation!.byteLength ?? 1) - 1
      )
    )
  };
}

/** The offset index the current display offset corresponds to, for writing back to the sidecar. */
export function offsetIndexOf(
  state: NexAnnotationEditorState
): NexAnnotationOffsetIndex | undefined {
  return getNexBankOffsetIndex(state.env.disassOffset);
}

// ─── Equality helpers ────────────────────────────────────────────────────────

function sameEnvironment(
  left: NexAnnotationEditorEnvironment,
  right: NexAnnotationEditorEnvironment
): boolean {
  return (
    left.annotationPath === right.annotationPath &&
    left.bank === right.bank &&
    left.viewMode === right.viewMode &&
    left.decimalView === right.decimalView &&
    left.disassOffset === right.disassOffset
  );
}

function sameSelection(
  left: NexAnnotationSelection | undefined,
  right: NexAnnotationSelection | undefined
): boolean {
  if (!left || !right) return left === right;
  return left.anchorIndex === right.anchorIndex && left.activeIndex === right.activeIndex;
}

function clampSelection(
  selection: NexAnnotationSelection | undefined,
  length: number
): NexAnnotationSelection | undefined {
  if (!selection) return undefined;
  if (length === 0) return undefined;
  const last = length - 1;
  if (selection.anchorIndex <= last && selection.activeIndex <= last) return selection;
  return {
    anchorIndex: Math.min(selection.anchorIndex, last),
    activeIndex: Math.min(selection.activeIndex, last)
  };
}

function clampContextTarget(
  target: NexAnnotationContextTarget | undefined,
  length: number
): NexAnnotationContextTarget | undefined {
  if (!target) return undefined;
  if (length === 0) return undefined;
  return target.rowIndex < length ? target : undefined;
}
