import type { ThemeDefinition } from "xmlui";

const kliveShellFontFamily =
  "-apple-system, BlinkMacSystemFont, Helvetica, Neue-Light, Ubuntu, Droid Sans, sans-serif";

const sp48KeyboardFontThemeVars = {
  "fontFamily-EmuKeyboard": kliveShellFontFamily,
  "fontSize-mainKey-EmuKeyboard": "36px",
  "fontSize-keywordKey-EmuKeyboard": "22px",
  "fontSize-symbolKey-EmuKeyboard": "28px",
  "fontSize-topSymbolKey-EmuKeyboard": "24px",
  "fontSize-symbolWordKey-EmuKeyboard": "18px",
  "fontSize-aboveKey-EmuKeyboard": "20px",
  "fontSize-belowKey-EmuKeyboard": "20px",
  "fontSize-centerKey-EmuKeyboard": "28px",
  "fontSize-shiftKey-EmuKeyboard": "20px",
  "fontSize-topNumberKey-EmuKeyboard": "20px",
};

const ideThemeVars = {
  "backgroundColor-ActivityBar": "$color-surface-100",
  "backgroundColor-ActivityBar--active": "rgba(0, 122, 204, 0.18)",
  "textColor-ActivityBar": "$color-surface-700",
  "textColor-ActivityBar--active": "#ffffff",
  "borderColor-ActivityBar--active": "#007acc",
  "backgroundColor-SideBar": "$color-surface-50",
  "backgroundColor-SideBarHeader": "$color-surface-100",
  "backgroundColor-SideBarPanelHeader": "$color-surface-50",
  "backgroundColor-SideBarViewPreview": "$color-surface-0",
  "backgroundColor-dropIndicator-SideBarPanelStack": "$borderColor-active-Tabs",
  "boxShadow-dropIndicator-SideBarPanelStack": "0 0 0 1px $borderColor-active-Tabs",
  "height-dropIndicator-SideBarPanelStack": "3px",
  "zIndex-dropIndicator-SideBarPanelStack": "50",
  "backgroundColor-DocumentsPanel": "$color-surface-50",
  "borderColor-SideBarPanel": "$color-surface-200",
  "textColor-SideBarHeader": "$color-surface-950",
  "textColor-SideBarPanelHeader": "$color-surface-900",
  "textColor-SideBar": "$color-surface-950",
  "textColor-SideBarSubtle": "$color-surface-700",
  "backgroundColor-Editor": "$color-surface-0",
  "backgroundColor-EditorGroup": "$color-surface-50",
  "backgroundColor-EditorGroupHeader": "$color-surface-100",
  "backgroundColor-EditorGridToolbar": "$color-surface-100",
  "backgroundColor-DocumentCommandStrip": "$color-surface-100",
  "backgroundColor-DocumentPreview": "$color-surface-0",
  "borderColor-EditorGroup": "$color-surface-200",
  "textColor-Editor": "$color-surface-950",
  "textColor-EditorSubtle": "$color-surface-700",
  "backgroundColor-DocumentTabStrip": "$color-surface-100",
  "backgroundColor-DocumentTab": "$color-surface-200",
  "backgroundColor-DocumentTab--active": "$color-surface-0",
  "textColor-DocumentTab": "$color-surface-700",
  "textColor-DocumentTab--active": "$color-surface-950",
  "borderColor-DocumentTab": "$color-surface-200",
  "backgroundColor-list-Tabs": "$color-surface-100",
  "backgroundColor-Tabs": "$color-surface-0",
  "backgroundColor-trigger-Tabs": "$color-surface-200",
  "backgroundColor-trigger-Tabs--active": "$color-surface-0",
  "backgroundColor-trigger-Tabs--hover": "$color-surface-300",
  "borderColor-Tabs": "$color-surface-200",
  "borderColor-active-Tabs": "#007acc",
  "outlineColor--focus": "transparent",
  "outlineWidth--focus": "0px",
  "outlineStyle--focus": "solid",
  "outlineOffset--focus": "0",
  "textColor-trigger-Tabs": "$color-surface-700",
  "textColor-trigger-Tabs--active": "$color-surface-950",
  "textColor-trigger-Tabs--hover": "$color-surface-950",
  "backgroundColor-ToolsArea": "$color-surface-50",
  "backgroundColor-ToolsHeader": "$color-surface-100",
  "backgroundColor-ToolTab--active": "$color-surface-0",
  "backgroundColor-ToolConsole": "$color-surface-0",
  "textColor-ToolTab": "$color-surface-700",
  "textColor-ToolTab--active": "$color-surface-950",
  "textColor-ToolsArea": "$color-surface-950",
  "textColor-ToolsAreaSubtle": "$color-surface-700",
  "borderColor-ToolsArea": "$color-surface-200",
  "backgroundColor-CommandInput": "$color-surface-0",
  "backgroundColor-ModalDialog": "$color-surface-0",
  "backgroundColor-title-ModalDialog": "$color-surface-50",
  "backgroundColor-overlay-ModalDialog": "rgba(0, 0, 0, 0.46)",
  "borderColor-ModalDialog": "$color-surface-200",
  "textColor-ModalDialog": "$color-surface-950",
  "textColor-ModalDialogSubtle": "$color-surface-700",
  "textColor-title-ModalDialog": "$color-surface-950",
};

export const KliveTheme: ThemeDefinition = {
  id: "klive-theme",
  name: "Klive IDE Theme",
  extends: "xmlui",
  color: "$color-primary-500",
  themeVars: {
    // --- Surface colors
    "const-color-surface-0": "hsl(0, 0%, 100%)",
    "const-color-surface-50": "hsl(0, 0%, 98%)",
    "const-color-surface-100": "hsl(0, 0%, 95%)",
    "const-color-surface-200": "hsl(0, 0%, 83%)",
    "const-color-surface-300": "hsl(0, 0%, 75%)",
    "const-color-surface-400": "hsl(0, 0%, 63%)",
    "const-color-surface-500": "hsl(0, 0%, 70%)", // #B2B2B2
    "const-color-surface-600": "hsl(0, 0%, 60%)",
    "const-color-surface-700": "hsl(0, 0%, 50%)",
    "const-color-surface-800": "hsl(0, 0%, 40%)",
    "const-color-surface-900": "hsl(0, 0%, 30%)",
    "const-color-surface-950": "hsl(0, 0%, 20%)",
    "const-color-surface-1000": "hsl(0, 0%, 12%)",
    "const-color-surface": "$const-color-surface-500",

    "backgroundColor-Toolbar": "$color-surface-50",
    "backgroundColor-EmuStatusBar": "#007acc",
    "backgroundColor-IdeStatusBar": "#007acc",
    "textColor-EmuStatusBar": "#ffffff",
    "textColor-IdeStatusBar": "#ffffff",
    "textColor-IdeStatusBar--muted": "#86bee8",
    "backgroundColor-resizer-Splitter": "#007acc",
    "backgroundColor-KeyboardArea": "$color-surface-0",
    "backgroundColor-EmulatorPanel": "$color-surface-100",
    "backgroundColor-display-EmulatorPanel": "$color-surface-50",
    "color-error-EmulatorPanel": "#ffb4a8",
    "padding-EmuKeyboard": "$space-3",
    "backgroundColor-EmuKeyboard": "#181818",
    "backgroundColor-key-EmuKeyboard": "#707070",
    "backgroundColor-highlightedKey-EmuKeyboard": "#0B486B",
    "color-mainKey-EmuKeyboard": "#e0e0e0",
    "color-symbolKey-EmuKeyboard": "#c00000",
    "color-aboveKey-EmuKeyboard": "#00a000",
    "color-belowKey-EmuKeyboard": "#d02000",
    "color-highlightKey-EmuKeyboard": "#0048c0",
    ...sp48KeyboardFontThemeVars,

    "borderRadius-list-Tabs": "0px",
    "borderRadius-trigger-Tabs": "0px",
    "borderWidth-Tabs": "1px",
    "padding-trigger-Tabs": "0 10px",
    "paddingTop-TabItem": "0px",
    "borderWidth-ModalDialog": "1px",
    "borderStyle-ModalDialog": "solid",
    "borderRadius-ModalDialog": "6px",
    ...ideThemeVars,
  },
  resources: {},
};

export default KliveTheme;
