import type { ThemeDefinition } from "xmlui";

const kliveShellFontFamily =
  "-apple-system, BlinkMacSystemFont, Helvetica, Neue-Light, Ubuntu, Droid Sans, sans-serif";

const sp48KeyboardFontThemeVars = {
  "fontFamily-EmuKeyboard": kliveShellFontFamily,
  "fontSize-mainKey-EmuKeyboard": "36px",
  "fontSize-keywordKey-EmuKeyboard": "22px",
  "fontSize-symbolKey-EmuKeyboard": "28px",
  "fontSize-topSymbolKey-EmuKeyboard": "24px",
  "fontSize-symbolWordKey-EmuKeyboard": "18px",
  "fontSize-aboveKey-EmuKeyboard": "20px",
  "fontSize-belowKey-EmuKeyboard": "20px",
  "fontSize-centerKey-EmuKeyboard": "28px",
  "fontSize-shiftKey-EmuKeyboard": "20px",
  "fontSize-topNumberKey-EmuKeyboard": "20px",
};

export const KliveTheme: ThemeDefinition = {
  id: "klive-theme",
  name: "Klive IDE Theme",
  extends: "xmlui",
  color: "$color-primary-500",
  themeVars: {
    // --- Surface colors
    "const-color-surface-50": "hsl(0, 0%, 98%)",
    "const-color-surface-100": "hsl(0, 0%, 95%)",
    "const-color-surface-200": "hsl(0, 0%, 83%)",
    "const-color-surface-300": "hsl(0, 0%, 75%)",
    "const-color-surface-400": "hsl(0, 0%, 63%)",
    "const-color-surface-500": "hsl(0, 0%, 70%)", // #B2B2B2
    "const-color-surface-600": "hsl(0, 0%, 60%)",
    "const-color-surface-700": "hsl(0, 0%, 50%)",
    "const-color-surface-800": "hsl(0, 0%, 40%)",
    "const-color-surface-900": "hsl(0, 0%, 30%)",
    "const-color-surface-950": "hsl(0, 0%, 20%)",
    "const-color-surface": "$const-color-surface-500",

    "backgroundColor-Toolbar": "$color-surface-50",
    "backgroundColor-EmuStatusBar": "#007acc",
    "backgroundColor-IdeStatusBar": "#007acc",
    "textColor-EmuStatusBar": "#ffffff",
    "textColor-IdeStatusBar": "#ffffff",
    "textColor-IdeStatusBar--muted": "#86bee8",
    "backgroundColor-resizer-Splitter": "#007acc",
    "backgroundColor-KeyboardArea": "$color-surface-0",
    "backgroundColor-EmulatorPanel": "$color-surface-100",
    "backgroundColor-display-EmulatorPanel": "$color-surface-50",
    "color-error-EmulatorPanel": "#ffb4a8",
    "padding-EmuKeyboard": "$space-3",
    "backgroundColor-EmuKeyboard": "#181818",
    "backgroundColor-key-EmuKeyboard": "#707070",
    "backgroundColor-highlightedKey-EmuKeyboard": "#0B486B",
    "color-mainKey-EmuKeyboard": "#e0e0e0",
    "color-symbolKey-EmuKeyboard": "#c00000",
    "color-aboveKey-EmuKeyboard": "#00a000",
    "color-belowKey-EmuKeyboard": "#d02000",
    "color-highlightKey-EmuKeyboard": "#0048c0",
    ...sp48KeyboardFontThemeVars,

    "backgroundColor-ActivityBar": "#2f3338",
    "backgroundColor-ActivityBar--active": "#3a3f46",
    "textColor-ActivityBar": "#b8bcc3",
    "textColor-ActivityBar--active": "#ffffff",
    "borderColor-ActivityBar--active": "#007acc",
    "backgroundColor-SideBar": "#25282d",
    "backgroundColor-SideBarHeader": "#2b2f35",
    "backgroundColor-SideBarPanelHeader": "#25282d",
    "borderColor-SideBarPanel": "#3a3f46",
    "textColor-SideBarHeader": "#d7dbe0",
    "textColor-SideBarPanelHeader": "#c7cbd1",
    "textColor-SideBar": "#d8dce2",
    "textColor-SideBarSubtle": "#98a0aa",
    "backgroundColor-Editor": "#1f2227",
    "backgroundColor-EditorGroup": "#20242a",
    "backgroundColor-EditorGroupHeader": "#25282d",
    "backgroundColor-EditorGridToolbar": "#202328",
    "backgroundColor-DocumentCommandStrip": "#23262b",
    "backgroundColor-DocumentPreview": "#191b20",
    "borderColor-EditorGroup": "#343941",
    "textColor-Editor": "#e4e8ee",
    "textColor-EditorSubtle": "#9ca5b0",
    "backgroundColor-DocumentTabStrip": "#252930",
    "backgroundColor-DocumentTab": "#2a2f36",
    "backgroundColor-DocumentTab--active": "#1f2227",
    "textColor-DocumentTab": "#aeb5bf",
    "textColor-DocumentTab--active": "#ffffff",
    "borderColor-DocumentTab": "#373d45",
    "backgroundColor-list-Tabs": "#25282d",
    "backgroundColor-Tabs": "#1f2227",
    "backgroundColor-trigger-Tabs": "#2a2f36",
    "backgroundColor-trigger-Tabs--active": "#1f2227",
    "backgroundColor-trigger-Tabs--hover": "#343941",
    "borderColor-Tabs": "#343941",
    "borderColor-active-Tabs": "#007acc",
    "borderRadius-list-Tabs": "0px",
    "borderRadius-trigger-Tabs": "0px",
    "borderWidth-Tabs": "1px",
    "padding-trigger-Tabs": "0 10px",
    "paddingTop-TabItem": "0px",
    "textColor-trigger-Tabs": "#aeb5bf",
    "textColor-trigger-Tabs--active": "#ffffff",
    "textColor-trigger-Tabs--hover": "#ffffff",
    "backgroundColor-ToolsArea": "#20242a",
    "backgroundColor-ToolsHeader": "#252930",
    "backgroundColor-ToolTab--active": "#1f2227",
    "textColor-ToolTab": "#aeb5bf",
    "textColor-ToolTab--active": "#ffffff",
    "textColor-ToolsArea": "#e4e8ee",
    "textColor-ToolsAreaSubtle": "#9ca5b0",
    "borderColor-ToolsArea": "#373d45",
    "backgroundColor-CommandInput": "#171a1f",
  },
  resources: {},
};

export default KliveTheme;
