import type { ThemeDefinition } from "xmlui";

const kliveShellFontFamily =
  "-apple-system, BlinkMacSystemFont, Helvetica, Neue-Light, Ubuntu, Droid Sans, sans-serif";

const sp48KeyboardFontThemeVars = {
  "fontFamily-EmuKeyboard": kliveShellFontFamily,
  "fontSize-mainKey-EmuKeyboard": "36px",
  "fontSize-keywordKey-EmuKeyboard": "22px",
  "fontSize-symbolKey-EmuKeyboard": "28px",
  "fontSize-topSymbolKey-EmuKeyboard": "24px",
  "fontSize-symbolWordKey-EmuKeyboard": "18px",
  "fontSize-aboveKey-EmuKeyboard": "20px",
  "fontSize-belowKey-EmuKeyboard": "20px",
  "fontSize-centerKey-EmuKeyboard": "28px",
  "fontSize-shiftKey-EmuKeyboard": "20px",
  "fontSize-topNumberKey-EmuKeyboard": "20px",
};

const ideDarkThemeVars = {
  "backgroundColor-ActivityBar": "#2f3338",
  "backgroundColor-ActivityBar--active": "#3a3f46",
  "textColor-ActivityBar": "#b8bcc3",
  "textColor-ActivityBar--active": "#ffffff",
  "borderColor-ActivityBar--active": "#007acc",
  "backgroundColor-SideBar": "#25282d",
  "backgroundColor-SideBarHeader": "#2b2f35",
  "backgroundColor-SideBarPanelHeader": "#25282d",
  "backgroundColor-SideBarViewPreview": "#202328",
  "borderColor-SideBarPanel": "#3a3f46",
  "textColor-SideBarHeader": "#d7dbe0",
  "textColor-SideBarPanelHeader": "#c7cbd1",
  "textColor-SideBar": "#d8dce2",
  "textColor-SideBarSubtle": "#98a0aa",
  "backgroundColor-Editor": "#1f2227",
  "backgroundColor-EditorGroup": "#20242a",
  "backgroundColor-EditorGroupHeader": "#25282d",
  "backgroundColor-EditorGridToolbar": "#202328",
  "backgroundColor-DocumentCommandStrip": "#23262b",
  "backgroundColor-DocumentPreview": "#191b20",
  "borderColor-EditorGroup": "#343941",
  "textColor-Editor": "#e4e8ee",
  "textColor-EditorSubtle": "#9ca5b0",
  "backgroundColor-DocumentTabStrip": "#252930",
  "backgroundColor-DocumentTab": "#2a2f36",
  "backgroundColor-DocumentTab--active": "#1f2227",
  "textColor-DocumentTab": "#aeb5bf",
  "textColor-DocumentTab--active": "#ffffff",
  "borderColor-DocumentTab": "#373d45",
  "backgroundColor-list-Tabs": "#25282d",
  "backgroundColor-Tabs": "#1f2227",
  "backgroundColor-trigger-Tabs": "#2a2f36",
  "backgroundColor-trigger-Tabs--active": "#1f2227",
  "backgroundColor-trigger-Tabs--hover": "#343941",
  "borderColor-Tabs": "#343941",
  "borderColor-active-Tabs": "#007acc",
  "textColor-trigger-Tabs": "#aeb5bf",
  "textColor-trigger-Tabs--active": "#ffffff",
  "textColor-trigger-Tabs--hover": "#ffffff",
  "backgroundColor-ToolsArea": "#20242a",
  "backgroundColor-ToolsHeader": "#252930",
  "backgroundColor-ToolTab--active": "#1f2227",
  "backgroundColor-ToolConsole": "#171a1f",
  "textColor-ToolTab": "#aeb5bf",
  "textColor-ToolTab--active": "#ffffff",
  "textColor-ToolsArea": "#e4e8ee",
  "textColor-ToolsAreaSubtle": "#9ca5b0",
  "borderColor-ToolsArea": "#373d45",
  "backgroundColor-CommandInput": "#171a1f",
  "backgroundColor-ModalDialog": "#252930",
  "backgroundColor-title-ModalDialog": "#252930",
  "backgroundColor-overlay-ModalDialog": "rgba(0, 0, 0, 0.46)",
  "borderColor-ModalDialog": "#3a3f46",
  "textColor-ModalDialog": "#e4e8ee",
  "textColor-ModalDialogSubtle": "#9ca5b0",
  "textColor-title-ModalDialog": "#ffffff",
};

const ideLightThemeVars = {
  "backgroundColor-ActivityBar": "#e6e8eb",
  "backgroundColor-ActivityBar--active": "#ffffff",
  "textColor-ActivityBar": "#5a6069",
  "textColor-ActivityBar--active": "#1f2328",
  "borderColor-ActivityBar--active": "#007acc",
  "backgroundColor-SideBar": "#f3f4f6",
  "backgroundColor-SideBarHeader": "#ffffff",
  "backgroundColor-SideBarPanelHeader": "#f3f4f6",
  "backgroundColor-SideBarViewPreview": "#ffffff",
  "borderColor-SideBarPanel": "#d5d9df",
  "textColor-SideBarHeader": "#20242a",
  "textColor-SideBarPanelHeader": "#343a43",
  "textColor-SideBar": "#1f2328",
  "textColor-SideBarSubtle": "#69717d",
  "backgroundColor-Editor": "#ffffff",
  "backgroundColor-EditorGroup": "#f7f8fa",
  "backgroundColor-EditorGroupHeader": "#eef0f3",
  "backgroundColor-EditorGridToolbar": "#f4f6f8",
  "backgroundColor-DocumentCommandStrip": "#f1f3f6",
  "backgroundColor-DocumentPreview": "#ffffff",
  "borderColor-EditorGroup": "#d9dde3",
  "textColor-Editor": "#1f2328",
  "textColor-EditorSubtle": "#66707d",
  "backgroundColor-DocumentTabStrip": "#eef0f3",
  "backgroundColor-DocumentTab": "#e5e8ec",
  "backgroundColor-DocumentTab--active": "#ffffff",
  "textColor-DocumentTab": "#5d6672",
  "textColor-DocumentTab--active": "#1f2328",
  "borderColor-DocumentTab": "#d2d7de",
  "backgroundColor-list-Tabs": "#eef0f3",
  "backgroundColor-Tabs": "#ffffff",
  "backgroundColor-trigger-Tabs": "#e5e8ec",
  "backgroundColor-trigger-Tabs--active": "#ffffff",
  "backgroundColor-trigger-Tabs--hover": "#dce1e7",
  "borderColor-Tabs": "#d2d7de",
  "borderColor-active-Tabs": "#007acc",
  "textColor-trigger-Tabs": "#5d6672",
  "textColor-trigger-Tabs--active": "#1f2328",
  "textColor-trigger-Tabs--hover": "#1f2328",
  "backgroundColor-ToolsArea": "#f7f8fa",
  "backgroundColor-ToolsHeader": "#eef0f3",
  "backgroundColor-ToolTab--active": "#ffffff",
  "backgroundColor-ToolConsole": "#ffffff",
  "textColor-ToolTab": "#5d6672",
  "textColor-ToolTab--active": "#1f2328",
  "textColor-ToolsArea": "#1f2328",
  "textColor-ToolsAreaSubtle": "#66707d",
  "borderColor-ToolsArea": "#d2d7de",
  "backgroundColor-CommandInput": "#ffffff",
  "backgroundColor-ModalDialog": "#ffffff",
  "backgroundColor-title-ModalDialog": "#f6f7f9",
  "backgroundColor-overlay-ModalDialog": "rgba(32, 36, 42, 0.34)",
  "borderColor-ModalDialog": "#cfd5dd",
  "textColor-ModalDialog": "#1f2328",
  "textColor-ModalDialogSubtle": "#66707d",
  "textColor-title-ModalDialog": "#1f2328",
};

export const KliveTheme: ThemeDefinition = {
  id: "klive-theme",
  name: "Klive IDE Theme",
  extends: "xmlui",
  color: "$color-primary-500",
  themeVars: {
    // --- Surface colors
    "const-color-surface-50": "hsl(0, 0%, 98%)",
    "const-color-surface-100": "hsl(0, 0%, 95%)",
    "const-color-surface-200": "hsl(0, 0%, 83%)",
    "const-color-surface-300": "hsl(0, 0%, 75%)",
    "const-color-surface-400": "hsl(0, 0%, 63%)",
    "const-color-surface-500": "hsl(0, 0%, 70%)", // #B2B2B2
    "const-color-surface-600": "hsl(0, 0%, 60%)",
    "const-color-surface-700": "hsl(0, 0%, 50%)",
    "const-color-surface-800": "hsl(0, 0%, 40%)",
    "const-color-surface-900": "hsl(0, 0%, 30%)",
    "const-color-surface-950": "hsl(0, 0%, 20%)",
    "const-color-surface": "$const-color-surface-500",

    "backgroundColor-Toolbar": "$color-surface-50",
    "backgroundColor-EmuStatusBar": "#007acc",
    "backgroundColor-IdeStatusBar": "#007acc",
    "textColor-EmuStatusBar": "#ffffff",
    "textColor-IdeStatusBar": "#ffffff",
    "textColor-IdeStatusBar--muted": "#86bee8",
    "backgroundColor-resizer-Splitter": "#007acc",
    "backgroundColor-KeyboardArea": "$color-surface-0",
    "backgroundColor-EmulatorPanel": "$color-surface-100",
    "backgroundColor-display-EmulatorPanel": "$color-surface-50",
    "color-error-EmulatorPanel": "#ffb4a8",
    "padding-EmuKeyboard": "$space-3",
    "backgroundColor-EmuKeyboard": "#181818",
    "backgroundColor-key-EmuKeyboard": "#707070",
    "backgroundColor-highlightedKey-EmuKeyboard": "#0B486B",
    "color-mainKey-EmuKeyboard": "#e0e0e0",
    "color-symbolKey-EmuKeyboard": "#c00000",
    "color-aboveKey-EmuKeyboard": "#00a000",
    "color-belowKey-EmuKeyboard": "#d02000",
    "color-highlightKey-EmuKeyboard": "#0048c0",
    ...sp48KeyboardFontThemeVars,

    "borderRadius-list-Tabs": "0px",
    "borderRadius-trigger-Tabs": "0px",
    "borderWidth-Tabs": "1px",
    "padding-trigger-Tabs": "0 10px",
    "paddingTop-TabItem": "0px",
    "borderWidth-ModalDialog": "1px",
    "borderStyle-ModalDialog": "solid",
    "borderRadius-ModalDialog": "6px",
  },
  tones: {
    light: {
      themeVars: ideLightThemeVars,
    },
    dark: {
      themeVars: ideDarkThemeVars,
    },
  },
  resources: {},
};

export default KliveTheme;
