title: Klive IDE
email: dotneteer@hotmail.com
description: >- 
  Full-fledged ZX Spectrum IDE with Electron Shell
baseurl: "/kliveide" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: istvannovak
github_username:  dotneteer

# Build settings

markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
