export const NEW_PROJECT_DIALOG = 1;
export const EXPORT_CODE_DIALOG = 2;
export const EXCLUDED_PROJECT_ITEMS_DIALOG = 3;
export const FIRST_STARTUP_DIALOG_EMU = 4;
export const FIRST_STARTUP_DIALOG_IDE = 5;
