name: Build artifacts

on: workflow_dispatch

jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install npm dependencies
      run: npm run bootstrap:ci

    - name: Build the packages
      run: npm run build

    - name: Test the packages
      run: npm run test

    - name: Build Electron app on windows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run build:win

    - name: Add install Emulator install kit to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: setup-kit
        path: artifacts/*.exe


