name: Release latest version

on: workflow_dispatch

jobs:
  release-latest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install npm dependencies
      run: npm run bootstrap:ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GT_WORKAROUND_PAT }}

    - name: Build the packages
      run: npm run build

    - name: Test the packages
      run: npm run test

    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        github_token: ${{ secrets.github_token }}
        release: true